import {test,expect,type Page,type Locator} from '@playwright/test';
import {randomUUID} from 'node:crypto';
const nav=(page:Page)=>page.getByRole('navigation',{name:'工作模組',exact:true});
async function view(page:Page){const r=await page.request.get('/api/workspace/view');expect(r.status()).toBe(200);return r.json();}
async function setup(page:Page,crmOnly=false){
 await page.goto('/');if(process.env.EXPECTED_PUBLIC_ASSET)await expect(page.locator('script[src]')).toHaveAttribute('src','/assets/'+process.env.EXPECTED_PUBLIC_ASSET);
 await page.getByLabel('店名／工作室名稱',{exact:true}).fill('合成：美術與互動驗證');await page.getByRole('button',{name:/^一般企業/}).click();if(crmOnly){await page.getByRole('checkbox',{name:'商品庫存',exact:true}).uncheck();await page.getByRole('checkbox',{name:'測試幣流水',exact:true}).uncheck();}
 await page.getByRole('button',{name:'建立我的測試系統',exact:true}).click();await expect(page.getByRole('heading',{name:'合成：美術與互動驗證',exact:true})).toBeVisible();
}
async function appearance(page:Page,theme:'light'|'dark'|'system',density:'comfortable'|'compact'='comfortable'){
 const panel=page.getByTestId('appearance-settings');if(!await panel.evaluate(el=>(el as HTMLDetailsElement).open))await panel.locator('summary').click();await page.getByTestId('interface-theme').selectOption(theme);await page.getByTestId('interface-density').selectOption(density);await panel.locator('summary').click();await expect(page.locator('html')).toHaveAttribute('data-density',density);
}
async function fixture(page:Page){let current=await view(page);return async(action:string,payload:any)=>{const r=await page.request.post('/api/workspace/commands',{headers:{Origin:new URL(page.url()).origin,'x-csrf-token':current.csrf,'Idempotency-Key':randomUUID(),'If-Match-Version':String(current.version)},data:{action,payload}});const body=await r.json();expect(r.status(),JSON.stringify(body)).toBe(200);current={...current,...body};return body;};}
function record(page:Page,kind:string,id:string){return page.getByTestId('records-'+kind).locator(`article[data-record-id="${id}"]`);}
async function submit(page:Page){await page.getByRole('dialog').getByRole('button',{name:'確認模擬操作',exact:true}).click();await expect(page.getByRole('dialog')).toHaveCount(0);}
async function readable(locator:Locator,minimum:number){await expect(locator).toBeVisible();const ratio=await locator.evaluate(el=>{
 const rgb=(v:string)=>{const m=v.match(/[\d.]+/g);return m?m.slice(0,3).map(Number):[255,255,255];};
 let parent:Element|null=el,background='rgb(255, 255, 255)';while(parent){const color=getComputedStyle(parent).backgroundColor;if(color!=='transparent'&&color!=='rgba(0, 0, 0, 0)'){background=color;break;}parent=parent.parentElement;}
 const light=(values:number[])=>values.map(v=>{const n=v/255;return n<=0.04045?n/12.92:((n+0.055)/1.055)**2.4;}).reduce((n,v,i)=>n+v*[0.2126,0.7152,0.0722][i],0);const a=light(rgb(getComputedStyle(el).color)),b=light(rgb(background));return (Math.max(a,b)+0.05)/(Math.min(a,b)+0.05);
 });expect(ratio).toBeGreaterThanOrEqual(minimum);}

test('appearance disclosure saves light, dark, system and density without changing workspace data',async({page})=>{
 await setup(page);const stable=(await view(page)).workspace;await appearance(page,'light');await expect(page.locator('html')).toHaveAttribute('data-theme','light');await page.screenshot({path:test.info().outputPath('art-light-desktop.png'),fullPage:false});await appearance(page,'dark','compact');await expect(page.locator('html')).toHaveAttribute('data-theme','dark');await page.screenshot({path:test.info().outputPath('art-dark-desktop.png'),fullPage:false});await page.reload();await expect(page.locator('html')).toHaveAttribute('data-theme','dark');await expect(page.locator('html')).toHaveAttribute('data-density','compact');expect((await view(page)).workspace).toEqual(stable);
 await page.emulateMedia({colorScheme:'light'});await appearance(page,'system','compact');await expect(page.locator('html')).toHaveAttribute('data-theme','light');await page.emulateMedia({colorScheme:'dark'});await expect(page.locator('html')).toHaveAttribute('data-theme','dark');expect((await view(page)).workspace).toEqual(stable);
});

test('dark filled modules, lesson and confirmation dialog remain readable with contained focus',async({page})=>{
 await setup(page);const create=await fixture(page),w=(await view(page)).workspace;const business=w.wallets.find((v:any)=>v.kind==='business'),buyer=w.wallets.find((v:any)=>v.kind==='buyer'),product=w.products[0];await create('contact.create',{name:'ART示範聯絡人',customer_id:w.customers[0].id});await create('quote.create',{case_id:w.cases[0].id,amount_minor:10000,expires_at:new Date(Date.now()+86400000).toISOString()});await create('wallet.fund',{wallet_id:business.id,amount_minor:1000000});await create('inventory.receive',{product_id:product.id,quantity:2});await create('wallet.fund',{wallet_id:buyer.id,amount_minor:product.price_minor});const order=await create('order.create',{buyer_wallet_id:buyer.id,lines:[{product_id:product.id,quantity:1}]});await create('order.pay',{id:order.result,amount_minor:product.price_minor});await create('workOrder.create',{bom_id:w.boms[0].id,quantity:1});await page.reload();await appearance(page,'dark');const stable=(await view(page)).workspace;
 for(const name of ['商品庫存','客戶與商機','模擬訂單','測試幣流水','報價與服務','BOM 與製造','任務與里程碑','模擬報表','設定與資料']){await nav(page).getByRole('button',{name,exact:true}).click();await readable(page.locator('main h1').first(),3);await readable(page.locator('main .page-heading p').first(),4.5);}
 await nav(page).getByRole('button',{name:'沉浸教學',exact:true}).click();await readable(page.getByTestId('learning-studio').locator('h1').first(),3);await readable(page.locator('.learning-scene-body'),4.5);await page.screenshot({path:test.info().outputPath('art-dark-learning.png'),fullPage:false});await page.getByTestId('quick-create-open').click();await page.getByTestId('quick-create-customer').click();const dialog=page.getByRole('dialog');await readable(dialog.getByRole('heading',{name:'新增客戶',exact:true}),3);expect(await dialog.evaluate(el=>el.contains(document.activeElement))).toBe(true);await page.screenshot({path:test.info().outputPath('art-dark-dialog.png'),fullPage:false});await dialog.getByRole('button',{name:'取消',exact:true}).click();expect((await view(page)).workspace).toEqual(stable);
});

test('pinned task title follows a real update and survives reload, navigation and unpin without extra mutations',async({page})=>{
 await setup(page);const initial=(await view(page)).workspace,task=initial.tasks[0];await nav(page).getByRole('button',{name:'任務與里程碑',exact:true}).click();await page.getByTestId('pin-record-'+task.id).click();await expect(page.getByTestId('pin-record-'+task.id)).toHaveAttribute('aria-pressed','true');expect((await view(page)).workspace).toEqual(initial);await record(page,'task',task.id).getByRole('button',{name:'更新進度',exact:true}).click();await page.getByRole('dialog').getByLabel(/^名稱/).fill('ART新的釘選任務名稱');await submit(page);const stable=(await view(page)).workspace;expect(stable.version).toBe(initial.version+1);await nav(page).getByRole('button',{name:'工作總覽',exact:true}).click();let pin=page.getByTestId('pinned-records').locator(`[data-record-id="${task.id}"]`);await expect(pin).toContainText('ART新的釘選任務名稱');await page.reload();await expect(pin).toContainText('ART新的釘選任務名稱');await pin.getByRole('button',{name:/ART新的釘選任務名稱/}).click();await expect(record(page,'task',task.id)).toBeFocused();await nav(page).getByRole('button',{name:'工作總覽',exact:true}).click();await pin.getByRole('button',{name:'取消釘選',exact:true}).click();await expect(page.getByTestId('pinned-record')).toHaveCount(0);await page.reload();await expect(page.getByTestId('pinned-record')).toHaveCount(0);expect((await view(page)).workspace).toEqual(stable);
});

test('new generation clears pinned references while keeping appearance preferences independent of business data',async({page})=>{
 await setup(page);await appearance(page,'dark');await readable(page.locator('.learning-entry h2'),3);await readable(page.locator('.learning-entry p'),4.5);const old=(await view(page)).workspace;await nav(page).getByRole('button',{name:'客戶與商機',exact:true}).click();await page.getByTestId('pin-record-'+old.customers[0].id).click();await nav(page).getByRole('button',{name:'工作總覽',exact:true}).click();await expect(page.getByTestId('pinned-record')).toHaveCount(1);await nav(page).getByRole('button',{name:'設定與資料',exact:true}).click();await page.getByRole('button',{name:'清除測試資料',exact:true}).click();await submit(page);await expect(page.getByRole('button',{name:'建立我的測試系統',exact:true})).toBeVisible();await page.getByLabel('店名／工作室名稱',{exact:true}).fill('ART新世代');await page.getByRole('button',{name:/^一般企業/}).click();await page.getByRole('button',{name:'建立我的測試系統',exact:true}).click();await expect(page.getByRole('heading',{name:'ART新世代',exact:true})).toBeVisible();const fresh=(await view(page)).workspace;expect(fresh.generation_id).not.toBe(old.generation_id);await expect(page.getByTestId('pinned-record')).toHaveCount(0);await expect(page.locator('html')).toHaveAttribute('data-theme','dark');await nav(page).getByRole('button',{name:'客戶與商機',exact:true}).click();await expect(page.getByTestId('pin-record-'+fresh.customers[0].id)).toHaveAttribute('aria-pressed','false');expect((await view(page)).workspace).toEqual(fresh);
});

test('quick menu cancels without writes, excludes other dialogs and confirms customer and task exactly once',async({page})=>{
 await setup(page);const initial=(await view(page)).workspace,writes:any[]=[];page.on('request',r=>{if(r.url().endsWith('/api/workspace/commands'))writes.push({key:r.headers()['idempotency-key'],body:r.postDataJSON()});});const opener=page.getByTestId('quick-create-open');await opener.click();for(const kind of ['customer','product','order','wallet','service','workOrder','task','milestone'])await expect(page.getByTestId('quick-create-'+kind)).toHaveCount(1);await page.keyboard.press('Control+k');await expect(page.getByTestId('workspace-search-dialog')).toHaveCount(0);await expect(page.getByRole('dialog')).toHaveCount(1);await page.keyboard.press('Escape');await expect(opener).toBeFocused();
 await opener.click();await page.getByTestId('quick-create-customer').click();await expect(page.getByTestId('quick-create-dialog')).toHaveCount(0);await expect(page.getByRole('dialog')).toHaveCount(1);await page.keyboard.press('Control+k');await expect(page.getByTestId('workspace-search-dialog')).toHaveCount(0);await page.getByRole('dialog').getByRole('button',{name:'取消',exact:true}).click();expect((await view(page)).workspace).toEqual(initial);expect(writes).toHaveLength(0);
 await opener.click();await page.getByTestId('quick-create-customer').click();await page.getByRole('dialog').getByLabel(/^客戶名稱/).fill('ART快速客戶');expect((await view(page)).workspace).toEqual(initial);await submit(page);await opener.click();await page.getByTestId('quick-create-task').click();await page.getByRole('dialog').getByLabel(/^任務名稱/).fill('ART快速任務');await submit(page);const w=(await view(page)).workspace;expect(w.version).toBe(initial.version+2);expect(w.customers.filter((v:any)=>v.name==='ART快速客戶')).toHaveLength(1);expect(w.tasks.filter((v:any)=>v.title==='ART快速任務')).toHaveLength(1);expect(writes).toHaveLength(2);expect(writes.map(v=>v.body.action)).toEqual(['customer.create','task.create']);expect(writes[0].key).not.toBe(writes[1].key);expect(w.wallets).toEqual(initial.wallets);expect(w.ledger).toEqual(initial.ledger);
});

test('quick entry prerequisites and disabled modules are explained before any form or mutation',async({page})=>{
 await setup(page);let stable=(await view(page)).workspace;expect(stable.products.every((v:any)=>v.on_hand-v.reserved===0)).toBe(true);await page.getByTestId('quick-create-open').click();await expect(page.getByTestId('quick-create-order')).toBeDisabled();await expect(page.getByTestId('quick-create-order')).toContainText('可用商品庫存');await page.keyboard.press('Escape');expect((await view(page)).workspace).toEqual(stable);
 await nav(page).getByRole('button',{name:'設定與資料',exact:true}).click();await page.getByRole('button',{name:'清除測試資料',exact:true}).click();await submit(page);await page.getByLabel('店名／工作室名稱',{exact:true}).fill('ART僅CRM與任務');await page.getByRole('button',{name:/^一般企業/}).click();await page.getByRole('checkbox',{name:'商品庫存',exact:true}).uncheck();await page.getByRole('checkbox',{name:'測試幣流水',exact:true}).uncheck();await page.getByRole('button',{name:'建立我的測試系統',exact:true}).click();await expect(page.getByRole('heading',{name:'ART僅CRM與任務',exact:true})).toBeVisible();stable=(await view(page)).workspace;await page.getByTestId('quick-create-open').click();for(const kind of ['product','order','wallet','service','workOrder']){await expect(page.getByTestId('quick-create-'+kind)).toBeDisabled();await expect(page.getByTestId('quick-create-'+kind)).toContainText('尚未啟用此模組');}await expect(page.getByTestId('quick-create-customer')).toBeEnabled();await expect(page.getByTestId('quick-create-task')).toBeEnabled();await page.keyboard.press('Escape');expect((await view(page)).workspace).toEqual(stable);
});

test('work queue tabs show real attention and next counts without changing data',async({page})=>{
 await setup(page);const create=await fixture(page),w=(await view(page)).workspace,business=w.wallets.find((v:any)=>v.kind==='business'),buyer=w.wallets.find((v:any)=>v.kind==='buyer');await create('wallet.fund',{wallet_id:business.id,amount_minor:100000});await create('inventory.receive',{product_id:w.products[0].id,quantity:1});const order=await create('order.create',{buyer_wallet_id:buyer.id,lines:[{product_id:w.products[0].id,quantity:1}]}),task=await create('task.create',{title:'ART逾期待辦',status:'todo',due_at:'2001-01-01T00:00:00.000Z'});await page.reload();const stable=(await view(page)).workspace,queue=page.getByTestId('work-queue');await expect(queue.locator('li[data-queue-id]')).toHaveCount(5);await expect(page.getByTestId('work-queue-filter-all')).toContainText('5');await expect(page.getByTestId('work-queue-filter-attention')).toContainText('2');await expect(page.getByTestId('work-queue-filter-next')).toContainText('3');await page.getByTestId('work-queue-filter-attention').click();await expect(queue.locator('li[data-queue-id]')).toHaveCount(2);await expect(queue.locator(`li[data-queue-id="order:${order.result}:pay"]`)).toBeVisible();await expect(queue.locator(`li[data-queue-id="task:${task.result}:progress"]`)).toBeVisible();await page.getByTestId('work-queue-filter-next').click();await expect(queue.locator('li[data-queue-id]')).toHaveCount(3);await expect(queue.locator(`li[data-queue-id="order:${order.result}:pay"]`)).toHaveCount(0);await page.getByTestId('work-queue-filter-all').click();await expect(queue.locator('li[data-queue-id]')).toHaveCount(5);expect((await view(page)).workspace).toEqual(stable);
});

test('320px dark compact appearance, pins and keyboard quick dialog fit with reduced motion',async({page})=>{
 await page.setViewportSize({width:320,height:850});await page.emulateMedia({reducedMotion:'reduce'});await setup(page);const stable=(await view(page)).workspace;await appearance(page,'dark','compact');await nav(page).getByRole('button',{name:'客戶與商機',exact:true}).click();const pin=page.getByTestId('pin-record-'+stable.customers[0].id);expect((await pin.boundingBox())!.height).toBeGreaterThanOrEqual(44);await pin.click();await nav(page).getByRole('button',{name:'工作總覽',exact:true}).click();await expect(page.getByTestId('pinned-record')).toHaveCount(1);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);const opener=page.getByTestId('quick-create-open');expect((await opener.boundingBox())!.height).toBeGreaterThanOrEqual(44);await opener.focus();await page.keyboard.press('Enter');const dialog=page.getByTestId('quick-create-dialog');await expect(dialog).toBeVisible();expect(await dialog.evaluate(el=>el.scrollWidth<=el.clientWidth+1)).toBe(true);expect((await page.getByTestId('quick-create-customer').boundingBox())!.height).toBeGreaterThanOrEqual(44);await page.keyboard.press('Tab');expect(await dialog.evaluate(el=>el.contains(document.activeElement))).toBe(true);await page.screenshot({path:test.info().outputPath('art-dark-mobile-320.png'),fullPage:false});await page.keyboard.press('Escape');await expect(opener).toBeFocused();expect(await page.evaluate(()=>matchMedia('(prefers-reduced-motion: reduce)').matches)).toBe(true);expect((await view(page)).workspace).toEqual(stable);
});
