import {test,expect,type Page,type Download} from '@playwright/test';
import {readFile} from 'node:fs/promises';
import {inflateRawSync} from 'node:zlib';

const profiles=['retail','wholesale','service','restaurant','manufacturing','ecommerce','projects','general'];
const literalCompany='合成：O\'Reilly "雙引號" $() & 工作室';
const mutationPaths=new Set(['/api/workspace/setup','/api/workspace/clear','/api/workspace/import','/api/workspace/commands']);
type Write={path:string;key:string;body:any};
function watchWrites(page:Page){const writes:Write[]=[];page.on('request',request=>{const path=new URL(request.url()).pathname;if(request.method()==='POST'&&mutationPaths.has(path))writes.push({path,key:request.headers()['idempotency-key'],body:request.postDataJSON()});});return writes;}
async function view(page:Page){const response=await page.request.get('/api/workspace/view');expect(response.status()).toBe(200);return response.json();}
async function visit(page:Page,path='/'){await page.goto(path);if(process.env.EXPECTED_PUBLIC_ASSET)await expect(page.locator('script[src]')).toHaveAttribute('src','/assets/'+process.env.EXPECTED_PUBLIC_ASSET);await expect(page.getByTestId('build-center-open')).toBeVisible();}
async function openBuilder(page:Page){await page.getByTestId('build-center-open').click();await expect(page.getByTestId('build-center')).toBeVisible();await expect(page).toHaveURL(/#build$/);}
async function plan(page:Page,{industry='general',company=literalCompany,local=false}:{industry?:string;company?:string;local?:boolean}={}){await openBuilder(page);await page.getByTestId('build-template-'+industry).click();await page.getByTestId('build-next').click();await page.getByTestId('build-company').fill(company);await page.getByTestId('build-next').click();if(local)await page.getByTestId('build-destination-local').check();await expect(page.getByTestId('build-plan')).toContainText(company);}
async function bytes(download:Download):Promise<Uint8Array>{expect(await download.failure()).toBeNull();const path=await download.path();expect(path).not.toBeNull();return readFile(path!);}
async function download(page:Page,id:string){const waiting=page.waitForEvent('download');await page.getByTestId(id).click();return waiting;}
const decode=(bytes:Uint8Array)=>new TextDecoder().decode(bytes);
function crc32(bytes:Uint8Array){let crc=0xffffffff;for(const byte of bytes){crc^=byte;for(let bit=0;bit<8;bit++)crc=(crc>>>1)^((crc&1)?0xedb88320:0);}return (crc^0xffffffff)>>>0;}
/** Independent ZIP reader checks central/local headers, real file bytes and CRCs. */
function unzip(bytes:Uint8Array){
 const data=new DataView(bytes.buffer,bytes.byteOffset,bytes.byteLength),u16=(offset:number)=>data.getUint16(offset,true),u32=(offset:number)=>data.getUint32(offset,true);
 let end=-1;for(let offset=bytes.length-22;offset>=Math.max(0,bytes.length-65557);offset--)if(u32(offset)===0x06054b50){end=offset;break;}expect(end).toBeGreaterThanOrEqual(0);
 expect(u16(end+4)).toBe(0);expect(u16(end+6)).toBe(0);const count=u16(end+10);expect(u16(end+8)).toBe(count);expect(end+22+u16(end+20)).toBe(bytes.length);
 let offset=u32(end+16);const centralEnd=offset+u32(end+12);expect(centralEnd).toBe(end);const files=new Map<string,Uint8Array>();
 for(let i=0;i<count;i++){
  expect(u32(offset)).toBe(0x02014b50);const flags=u16(offset+8),method=u16(offset+10),crc=u32(offset+16),compressed=u32(offset+20),size=u32(offset+24),nameSize=u16(offset+28),extraSize=u16(offset+30),commentSize=u16(offset+32),local=u32(offset+42);const name=decode(bytes.subarray(offset+46,offset+46+nameSize));
  expect(flags&1).toBe(0);expect([0,8]).toContain(method);expect(name).not.toMatch(/[/\\]|^\./);expect(files.has(name)).toBe(false);expect(u32(local)).toBe(0x04034b50);expect(u16(local+8)).toBe(method);
  const localNameSize=u16(local+26),localExtraSize=u16(local+28);expect(decode(bytes.subarray(local+30,local+30+localNameSize))).toBe(name);const start=local+30+localNameSize+localExtraSize;expect(start+compressed).toBeLessThanOrEqual(u32(end+16));const packed=bytes.subarray(start,start+compressed),content=method===8?inflateRawSync(packed):packed;expect(content.length).toBe(size);expect(crc32(content)).toBe(crc);files.set(name,content);offset+=46+nameSize+extraSize+commentSize;
 }expect(offset).toBe(centralEnd);return files;
}

test('builder choices and dependent modules produce a literal local plan without workspace writes',async({page})=>{
 await visit(page);const initial=await view(page),writes=watchWrites(page);await openBuilder(page);await expect(page.locator('[data-testid^="build-template-"]')).toHaveCount(8);for(const profile of profiles){await page.getByTestId('build-template-'+profile).click();await expect(page.getByTestId('build-template-'+profile)).toHaveAttribute('aria-pressed','true');}
 await page.getByTestId('build-next').click();await page.getByTestId('build-company').fill(literalCompany);await page.getByTestId('build-module-inventory').uncheck();await expect(page.getByTestId('build-module-sales')).not.toBeChecked();await expect(page.getByTestId('build-module-manufacturing')).not.toBeChecked();await page.getByTestId('build-module-manufacturing').check();await expect(page.getByTestId('build-module-inventory')).toBeChecked();await expect(page.getByTestId('build-module-wallets')).toBeChecked();await page.getByTestId('build-next').click();await page.getByTestId('build-destination-local').check();await expect(page.getByTestId('build-plan')).toContainText(literalCompany);await expect(page.getByTestId('build-plan')).toContainText('SIM');
 await page.screenshot({path:'test-results/build-center-desktop.png',fullPage:true});
 const config=JSON.parse(decode(await bytes(await download(page,'build-download-config'))));expect(config.format).toBe('freedom-erp-launch-v1');expect(config.company_name).toBe(literalCompany);expect(config.industry).toBe('general');expect(new Set(config.modules)).toEqual(new Set(['inventory','wallets','services','crm','projects','manufacturing']));expect(config.port).toBe('auto');expect(config.auto_setup).toBe(true);expect(config.simulation).toBe(true);expect(config.real_finance).toBe(false);expect(config.directory).toBe('./freedom-data');expect((await view(page)).workspace).toEqual(initial.workspace);expect((await view(page)).version).toBe(initial.version);expect(writes).toEqual([]);
});

test('one public confirmation creates one real template version and enters teaching without automatic transactions',async({page})=>{
 await visit(page);const initial=await view(page),writes=watchWrites(page);expect(initial.workspace).toBeNull();await plan(page,{industry:'manufacturing',company:'合成：快速上手製造工廠'});expect(writes).toEqual([]);await expect(page.getByTestId('build-create')).toBeEnabled();await page.getByTestId('build-create').click();await expect(page.getByTestId('learning-studio')).toBeVisible();await expect(page).toHaveURL(/#learning$/);const created=await view(page);
 expect(writes).toHaveLength(1);expect(writes[0].path).toBe('/api/workspace/setup');expect(writes[0].key).toBeTruthy();expect(writes[0].body).toMatchObject({industry:'manufacturing',company_name:'合成：快速上手製造工廠'});expect(created.version).toBe(initial.version+1);expect(created.workspace.version).toBe(created.version);expect(created.workspace.industry).toBe('manufacturing');expect(created.workspace.currency).toBe('SIM');expect(created.workspace.real_finance).toBe(false);expect(created.workspace.products.every((row:any)=>row.on_hand===0&&row.reserved===0)).toBe(true);expect(created.workspace.ledger).toEqual([]);expect(created.workspace.orders).toEqual([]);expect(created.workspace.workOrders).toEqual([]);
 await page.getByTestId('learning-exit').click();await expect(page.getByRole('heading',{name:'合成：快速上手製造工廠',exact:true})).toBeVisible();await page.getByRole('navigation',{name:'工作模組',exact:true}).getByRole('button',{name:'沉浸教學',exact:true}).click();await expect(page.getByTestId('learning-studio')).toBeVisible();expect((await view(page)).workspace).toEqual(created.workspace);expect(writes).toHaveLength(1);
});

test('an existing workspace is protected while another local plan can be downloaded and the current workspace resumed',async({page})=>{
 await visit(page);await page.getByLabel('店名／工作室名稱',{exact:true}).fill('合成：原有資料保留');await page.getByRole('button',{name:/^一般企業/}).click();await page.getByRole('button',{name:'建立我的測試系統',exact:true}).click();await expect(page.getByRole('heading',{name:'合成：原有資料保留',exact:true})).toBeVisible();const stable=await view(page),writes=watchWrites(page);await plan(page,{industry:'service',company:'合成：另一套本機服務'});await expect(page.getByTestId('build-existing')).toBeVisible();await expect(page.getByTestId('build-create')).toHaveCount(0);await page.getByTestId('build-destination-local').check();const config=JSON.parse(decode(await bytes(await download(page,'build-download-config'))));expect(config.company_name).toBe('合成：另一套本機服務');expect(config.industry).toBe('service');await page.getByTestId('build-destination-public').check();await page.getByTestId('build-existing-open').click();await expect(page.getByRole('heading',{name:'合成：原有資料保留',exact:true})).toBeVisible();expect((await view(page)).workspace).toEqual(stable.workspace);expect((await view(page)).version).toBe(stable.version);expect(writes).toEqual([]);
});

test('downloaded ZIP has valid file CRCs, exact JSON and no shell-sensitive names in its launchers',async({page})=>{
 await visit(page);const stable=await view(page),writes=watchWrites(page);await plan(page,{local:true});const result=await download(page,'build-download-kit');expect(result.suggestedFilename()).toMatch(/\.zip$/i);const files=unzip(await bytes(result));expect([...files.keys()].sort()).toEqual(['README.txt','freedom-launch.json','launch-schema.mjs','launch.mjs','start.cmd','start.sh','template-catalog.json']);const json=decode(files.get('freedom-launch.json')!),config=JSON.parse(json);expect(config.company_name).toBe(literalCompany);expect(config.industry).toBe('general');expect(config.port).toBe('auto');expect(config.simulation).toBe(true);expect(config.real_finance).toBe(false);const catalog=JSON.parse(decode(files.get('template-catalog.json')!));expect(catalog.templates.map((entry:any)=>entry.id)).toEqual(profiles);expect(decode(files.get('launch-schema.mjs')!)).toContain('normalizeLaunchConfig');
 for(const filename of ['start.cmd','start.sh','launch.mjs']){const source=decode(files.get(filename)!);expect(source).not.toContain(literalCompany);expect(source).not.toContain('O\'Reilly');expect(source).not.toMatch(/curl[^\r\n]*\|\s*(?:sh|bash|powershell)|Invoke-Expression|\bIEX\b/i);}
 expect(decode(files.get('launch.mjs')!)).toContain('freedom-launch.json');expect(decode(files.get('README.txt')!)).toContain('SIM');expect((await view(page)).workspace).toEqual(stable.workspace);expect((await view(page)).version).toBe(stable.version);expect(writes).toEqual([]);
});

test('an empty or whitespace company cannot advance to a public setup or download',async({page})=>{
 await visit(page);const stable=await view(page),writes=watchWrites(page);await openBuilder(page);await page.getByTestId('build-next').click();for(const value of ['', '   ']){await page.getByTestId('build-company').fill(value);await expect(page.getByTestId('build-next')).toBeDisabled();await expect(page.getByTestId('build-center').getByRole('alert')).toContainText('請填入店名／工作室名稱。');await expect(page.getByTestId('build-step-3')).toBeDisabled();expect(writes).toEqual([]);}await page.getByTestId('build-company').fill('合成：可以繼續');await expect(page.getByTestId('build-next')).toBeEnabled();expect((await view(page)).workspace).toEqual(stable.workspace);expect((await view(page)).version).toBe(stable.version);
});

test('320px dark builder steps, local plan and keyboard controls fit without modifying data',async({page})=>{
 await page.setViewportSize({width:320,height:850});await page.emulateMedia({reducedMotion:'reduce'});await visit(page);const stable=await view(page),writes=watchWrites(page);const settings=page.getByTestId('appearance-settings');await settings.locator('summary').click();await page.getByTestId('interface-theme').selectOption('dark');await settings.locator('summary').click();const opener=page.getByTestId('build-center-open');await opener.focus();await page.keyboard.press('Enter');await expect(page.getByTestId('build-center')).toBeVisible();
 for(const step of [1,2,3]){await expect(page.getByTestId('build-step-'+step)).toHaveAttribute('aria-current','step');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);if(step===2)await page.getByTestId('build-company').fill(literalCompany);if(step<3){await page.getByTestId('build-next').focus();await page.keyboard.press('Enter');}}
 await page.getByTestId('build-destination-local').check();await page.getByTestId('build-back').focus();await page.keyboard.press('Enter');await expect(page.getByTestId('build-step-2')).toHaveAttribute('aria-current','step');await page.getByTestId('build-next').focus();await page.keyboard.press('Enter');await expect(page.getByTestId('build-plan')).toContainText(literalCompany);await expect(page.locator('html')).toHaveAttribute('data-theme','dark');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);await page.screenshot({path:'test-results/build-center-dark-mobile-320.png',fullPage:true});expect((await view(page)).workspace).toEqual(stable.workspace);expect((await view(page)).version).toBe(stable.version);expect(writes).toEqual([]);
});

test('legacy setup remains available and produces the same SIM-only starter with no inventory or financial history',async({page})=>{
 await visit(page);const initial=await view(page),writes=watchWrites(page);await page.getByLabel('店名／工作室名稱',{exact:true}).fill('合成：舊入口回歸');await page.getByRole('button',{name:/^零售商店/}).click();await page.getByRole('button',{name:'建立我的測試系統',exact:true}).click();await expect(page.getByRole('heading',{name:'合成：舊入口回歸',exact:true})).toBeVisible();const created=await view(page);expect(created.version).toBe(initial.version+1);expect(created.workspace.industry).toBe('retail');expect(created.workspace.modules).toEqual(['inventory','sales','wallets','crm']);expect(created.workspace.currency).toBe('SIM');expect(created.workspace.real_finance).toBe(false);expect(created.workspace.products.every((row:any)=>row.on_hand===0&&row.reserved===0)).toBe(true);expect(created.workspace.ledger).toEqual([]);expect(created.workspace.orders).toEqual([]);expect(created.workspace.services).toEqual([]);expect(created.workspace.wallets.every((row:any)=>row.balance_minor===0)).toBe(true);expect(writes).toHaveLength(1);expect(writes[0].path).toBe('/api/workspace/setup');
});
