import {test,expect,type Page} from '@playwright/test';
import {randomUUID} from 'node:crypto';
const ids=['retail','wholesale','service','restaurant','manufacturing','ecommerce','projects','general'];
const names=['零售商店','批發商','服務工作室','餐飲店','製造工廠','電商','專案公司','一般企業'];
async function view(page:Page){return (await page.request.get('/api/workspace/view')).json();}
async function command(page:Page,action:string,payload:any){const v=await view(page);const r=await page.request.post('/api/workspace/commands',{headers:{Origin:new URL(page.url()).origin,'x-csrf-token':v.csrf,'Idempotency-Key':randomUUID(),'If-Match-Version':String(v.version)},data:{action,payload}});const result=await r.json();expect(r.status(),JSON.stringify(result)).toBe(200);return result;}
async function setup(page:Page,index:number,name='合成測試企業'){await page.goto('/#custom');if(process.env.EXPECTED_PUBLIC_ASSET)await expect(page.locator('script[src]')).toHaveAttribute('src','/assets/'+process.env.EXPECTED_PUBLIC_ASSET);await page.getByLabel('店名／工作室名稱',{exact:true}).fill(name);await page.getByRole('button',{name:new RegExp('^'+names[index])}).click();await page.getByRole('button',{name:'建立我的測試系統',exact:true}).click();await expect(page.getByRole('heading',{name,exact:true})).toBeVisible();}
async function nav(page:Page,name:string){await page.getByRole('navigation').getByRole('button',{name,exact:true}).click();}
async function submit(page:Page){await page.getByRole('dialog').getByRole('button',{name:'確認模擬操作',exact:true}).click();await expect(page.getByRole('dialog')).toHaveCount(0);}

for(const [index,id] of ids.entries())test(`${id} builds its own configured industry starter and survives reload`,async({page})=>{const company='合成：'+names[index];await setup(page,index,company);let v=await view(page);expect(v.workspace.industry).toBe(id);expect(v.workspace.company_name).toBe(company);expect(v.workspace.currency).toBe('SIM');expect(v.workspace.real_finance).toBe(false);await page.reload();await expect(page.getByRole('heading',{name:company,exact:true})).toBeVisible();if(['manufacturing','restaurant','general'].includes(id)){await nav(page,'BOM 與製造');expect(v.workspace.boms.length).toBeGreaterThan(0);}});

test('factory material receipt, reservation, start and completion transfer FIFO value into finished stock',async({page})=>{
 await setup(page,4,'合成：製造工單體驗');let v=await view(page);const business=v.workspace.wallets.find((w:any)=>w.kind==='business');await command(page,'wallet.fund',{wallet_id:business.id,amount_minor:1000000});const bom=v.workspace.boms[0];for(const material of bom.components)await command(page,'inventory.receive',{product_id:material.product_id,quantity:material.quantity*3});await page.reload();await nav(page,'BOM 與製造');
 await page.getByRole('button',{name:'新增製造工單',exact:true}).click();const dialog=page.getByRole('dialog');await dialog.getByRole('combobox').selectOption(bom.id);await dialog.getByRole('spinbutton').fill('3');await submit(page);
 await page.getByRole('button',{name:'備料',exact:true}).click();await expect(page.getByRole('button',{name:'開工',exact:true})).toBeEnabled();await page.getByRole('button',{name:'開工',exact:true}).click();await expect(page.getByRole('button',{name:'完工入庫',exact:true})).toBeEnabled();await page.getByRole('button',{name:'完工入庫',exact:true}).click();
 v=await view(page);expect(v.workspace.workOrders[0].status).toBe('completed');expect(v.workspace.products.find((p:any)=>p.id===bom.product_id).on_hand).toBe(3);expect(v.workspace.wallets.reduce((n:number,w:any)=>n+w.balance_minor,0)).toBe(0);await page.screenshot({path:test.info().outputPath('manufacturing-flow.png'),fullPage:true});
});

test('two visitors cannot see or mutate one another and an undelivered operation retries its original key',async({page,browser})=>{
 await setup(page,0,'合成：甲訪客');const other=await browser.newContext();const second=await other.newPage();await second.goto('/#custom');await expect(second.getByRole('button',{name:'建立我的測試系統',exact:true})).toBeVisible();expect((await view(second)).workspace).toBe(null);
 await nav(page,'客戶與商機');const keys:string[]=[];page.on('request',r=>{if(r.url().endsWith('/api/workspace/commands'))keys.push(r.headers()['idempotency-key']);});await page.route('**/api/workspace/commands',r=>r.abort('failed'),{times:1});await page.getByRole('button',{name:'新增客戶',exact:true}).click();await page.getByRole('dialog').getByRole('textbox',{name:/客戶名稱/}).fill('合成重送客戶');await page.getByRole('dialog').getByRole('button',{name:'確認模擬操作',exact:true}).click();await expect(page.getByText(/原操作/).first()).toBeVisible();await page.reload();const recover=page.getByRole('button').filter({hasText:/重送|恢復|確認原操作/});await recover.first().click();await expect(page.getByRole('status')).toContainText('已確認並恢復原操作。');const v=await view(page);expect(v.workspace.customers.filter((x:any)=>x.name==='合成重送客戶')).toHaveLength(1);expect(keys).toHaveLength(2);expect(keys[0]).toBe(keys[1]);expect((await view(second)).workspace).toBe(null);await other.close();
});

for(const width of [1440,768,390,320])test(`general starter modules stay readable at ${width}px`,async({page})=>{await page.setViewportSize({width,height:950});await setup(page,7,'合成：跨產業工作台');for(const name of ['商品庫存','客戶與商機','BOM 與製造','模擬報表','設定與資料']){await nav(page,name);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);}await page.screenshot({path:test.info().outputPath(`workspace-${width}.png`),fullPage:true});});
