import {test,expect,type Page} from '@playwright/test';
import {randomUUID} from 'node:crypto';
test.use({timezoneId:'Asia/Taipei'});
const nav=(page:Page)=>page.getByRole('navigation',{name:'工作模組',exact:true});
async function view(page:Page){const r=await page.request.get('/api/workspace/view');expect(r.status()).toBe(200);return r.json();}
async function setup(page:Page,industry='一般企業'){
 await page.goto('/');if(process.env.EXPECTED_PUBLIC_ASSET)await expect(page.locator('script[src]')).toHaveAttribute('src','/assets/'+process.env.EXPECTED_PUBLIC_ASSET);
 await page.getByLabel('店名／工作室名稱',{exact:true}).fill('合成：工作台驗證');await page.getByRole('button',{name:new RegExp('^'+industry)}).click();await page.getByRole('button',{name:'建立我的測試系統',exact:true}).click();await expect(page.getByRole('heading',{name:'合成：工作台驗證',exact:true})).toBeVisible();
}
// Real API fixtures supply list volume and unrelated domain states only. Search,
// navigation, task editing, lesson inspection and recovery are driven by UI.
async function fixtures(page:Page){let current=await view(page);return async(action:string,payload:any)=>{const r=await page.request.post('/api/workspace/commands',{headers:{Origin:new URL(page.url()).origin,'x-csrf-token':current.csrf,'Idempotency-Key':randomUUID(),'If-Match-Version':String(current.version)},data:{action,payload}});const body=await r.json();expect(r.status(),JSON.stringify(body)).toBe(200);current={...current,...body};return body;};}
function card(page:Page,kind:string,id:string){return page.getByTestId('records-'+kind).locator(`article[data-record-id="${id}"]`);}
async function focused(page:Page,kind:string,id:string){const row=card(page,kind,id);await expect(row).toBeFocused();await expect(row).toBeInViewport();await expect(row).toHaveClass(/target/);return row;}
async function submit(page:Page){await page.getByRole('dialog').getByRole('button',{name:'確認模擬操作',exact:true}).click();await expect(page.getByRole('dialog')).toHaveCount(0);}

test('record lists search literally, paginate at twelve and retain original order numbering after status filtering',async({page})=>{
 await setup(page);const create=await fixtures(page);for(let i=1;i<=13;i++)await create('customer.create',{name:'WB客戶'+String(i).padStart(2,'0')});await create('customer.create',{name:'WB [.*] literal'});
 let w=(await view(page)).workspace;const product=w.products[0],business=w.wallets.find((v:any)=>v.kind==='business'),buyer=w.wallets.find((v:any)=>v.kind==='buyer');await create('wallet.fund',{wallet_id:business.id,amount_minor:1000000});await create('inventory.receive',{product_id:product.id,quantity:30});const orders:any[]=[];for(let i=0;i<15;i++)orders.push(await create('order.create',{buyer_wallet_id:buyer.id,lines:[{product_id:product.id,quantity:1}]}));await create('order.cancel',{id:orders[0].result});await create('order.cancel',{id:orders[14].result});await page.reload();const stable=(await view(page)).workspace;
 const writes:string[]=[];page.on('request',r=>{if(r.method()==='POST')writes.push(r.url());});await nav(page).getByRole('button',{name:'客戶與商機',exact:true}).click();const customers=page.getByTestId('records-customer');await expect(customers.locator('article')).toHaveCount(12);await page.getByTestId('records-pagination-customer').getByRole('button',{name:'下一頁',exact:true}).click();await expect(customers.locator('article').first()).toContainText(stable.customers[12].name);await customers.getByRole('searchbox',{name:'搜尋客戶',exact:true}).fill('WB [.*]');await expect(customers.locator('article')).toHaveCount(1);await expect(customers.locator('article')).toContainText('WB [.*] literal');await customers.getByRole('searchbox',{name:'搜尋客戶',exact:true}).fill('no-such-record');await expect(customers.locator('article')).toHaveCount(0);
 await nav(page).getByRole('button',{name:'模擬訂單',exact:true}).click();const list=page.getByTestId('records-order');await expect(list.locator('article')).toHaveCount(12);await page.getByTestId('records-pagination-order').getByRole('button',{name:'下一頁',exact:true}).click();await expect(list.locator('article').first().getByRole('heading')).toHaveText('訂單 13');await list.getByRole('combobox',{name:'篩選訂單狀態',exact:true}).selectOption('cancelled');await expect(list.locator('article')).toHaveCount(2);await expect(list.locator('article').getByRole('heading')).toHaveText(['訂單 1','訂單 15']);expect((await view(page)).workspace).toEqual(stable);expect(writes).toHaveLength(0);
});

test('global Ctrl K search restores focus on Escape and related results locate the correct module and card',async({page})=>{
 await setup(page);const create=await fixtures(page);const customer=await create('customer.create',{name:'WB搜尋客戶'}),buyer=await create('wallet.create',{name:'WB搜尋客戶',kind:'buyer'}),product=await create('product.create',{name:'WB搜尋商品',sku:'WB-SKU-ONLY',price_minor:300,cost_minor:100});const business=(await view(page)).workspace.wallets.find((v:any)=>v.kind==='business');await create('wallet.fund',{wallet_id:business.id,amount_minor:10000});await create('inventory.receive',{product_id:product.result,quantity:1});const order=await create('order.create',{buyer_wallet_id:buyer.result,lines:[{product_id:product.result,quantity:1}]});await page.reload();const stable=(await view(page)).workspace;
 const opener=page.getByTestId('workspace-search-open');await opener.focus();await page.keyboard.press('Control+k');await expect(page.getByTestId('workspace-search-dialog')).toBeVisible();await expect(page.getByTestId('workspace-search-input')).toBeFocused();await page.keyboard.press('Escape');await expect(page.getByTestId('workspace-search-dialog')).toHaveCount(0);await expect(opener).toBeFocused();
 await opener.click();await page.getByTestId('workspace-search-input').fill('wb-sku-only');await page.getByTestId('workspace-search-dialog').locator(`[data-record-id="${product.result}"]`).click();await focused(page,'product',product.result);await expect(nav(page).getByRole('button',{name:'商品庫存',exact:true})).toHaveClass(/active/);await page.getByTestId('workspace-target-clear').click();
 await opener.click();await page.getByTestId('workspace-search-input').fill('WB搜尋客戶');const dialog=page.getByTestId('workspace-search-dialog');await expect(dialog.locator(`[data-record-id="${customer.result}"]`)).toBeVisible();await expect(dialog.locator(`[data-record-id="${buyer.result}"]`)).toBeVisible();await dialog.locator(`[data-record-id="${order.result}"]`).click();await focused(page,'order',order.result);await expect(nav(page).getByRole('button',{name:'模擬訂單',exact:true})).toHaveClass(/active/);expect((await view(page)).workspace).toEqual(stable);
});

test('global search excludes disabled service and manufacturing module results',async({page})=>{await setup(page,'零售商店');const stable=(await view(page)).workspace;await page.getByTestId('workspace-search-open').click();await page.getByTestId('workspace-search-input').fill('示範');const dialog=page.getByTestId('workspace-search-dialog');await expect(dialog.locator('[data-record-kind="service"],[data-record-kind="workOrder"],[data-record-kind="bom"]')).toHaveCount(0);await page.keyboard.press('Escape');await expect(nav(page).getByRole('button',{name:'報價與服務',exact:true})).toHaveCount(0);await expect(nav(page).getByRole('button',{name:'BOM 與製造',exact:true})).toHaveCount(0);expect((await view(page)).workspace).toEqual(stable);});

test('lesson inspection focuses the actual customer and returning preserves its chapter and checkpoint',async({page})=>{
 await setup(page);const initial=(await view(page)).workspace;await nav(page).getByRole('button',{name:'沉浸教學',exact:true}).click();await page.getByTestId('learning-route-sales').click();await page.getByTestId('learning-execute').click();await expect(page.getByTestId('learning-progress')).toHaveAttribute('aria-valuenow','1');await expect(page.getByTestId('learning-next')).toBeEnabled();const stable=(await view(page)).workspace,customer=stable.customers.find((v:any)=>!initial.customers.some((old:any)=>old.id===v.id));expect(customer.name).toMatch(/^教學客戶 /);await page.getByRole('button',{name:/^到工作台核對/}).click();await focused(page,'customer',customer.id);await nav(page).getByRole('button',{name:'沉浸教學',exact:true}).click();await expect(page.getByTestId('learning-step-customer')).toHaveAttribute('aria-current','step');await expect(page.getByTestId('learning-progress')).toHaveAttribute('aria-valuenow','1');expect((await view(page)).workspace).toEqual(stable);
});

test('overview attention targets zero-balance buyer and missing materials while completed work is absent',async({page})=>{
 await setup(page);const create=await fixtures(page);let w=(await view(page)).workspace;const business=w.wallets.find((v:any)=>v.kind==='business'),buyer=w.wallets.find((v:any)=>v.kind==='buyer'),finished=w.products[0],bom=w.boms[0],component=bom.components[0];await create('wallet.fund',{wallet_id:business.id,amount_minor:1000000});await create('inventory.receive',{product_id:finished.id,quantity:3});const pending=await create('order.create',{buyer_wallet_id:buyer.id,lines:[{product_id:finished.id,quantity:1}]}),planned=await create('workOrder.create',{bom_id:bom.id,quantity:2});await create('inventory.receive',{product_id:component.product_id,quantity:component.quantity});const complete=await create('workOrder.create',{bom_id:bom.id,quantity:1});await create('workOrder.reserve',{id:complete.result});await create('workOrder.start',{id:complete.result});await create('workOrder.complete',{id:complete.result});await page.reload();const stable=(await view(page)).workspace,queue=page.getByTestId('work-queue');await expect(queue).toBeVisible();await expect(queue.locator('[data-queue-id*="'+complete.result+'"]')).toHaveCount(0);await queue.locator('button[data-queue-id="order:'+pending.result+':pay"]').click();await focused(page,'wallet',buyer.id);await nav(page).getByRole('button',{name:'工作總覽',exact:true}).click();await queue.locator('button[data-queue-id="workOrder:'+planned.result+':planned"]').click();await focused(page,'product',component.product_id);await nav(page).getByRole('button',{name:'模擬訂單',exact:true}).click();await expect(card(page,'order',pending.result).getByTestId('readiness-order')).toContainText('沒有可用測試幣');await nav(page).getByRole('button',{name:'BOM 與製造',exact:true}).click();await expect(card(page,'workOrder',planned.result).getByTestId('readiness-workOrder')).toContainText('需要');expect((await view(page)).workspace).toEqual(stable);
});

test('task UI converts Taipei local deadlines to ISO, requires a title and clears deadline to null on update',async({page})=>{
 await setup(page);await nav(page).getByRole('button',{name:'任務與里程碑',exact:true}).click();await page.getByRole('button',{name:'新增任務',exact:true}).click();let dialog=page.getByRole('dialog');const before=await view(page);await dialog.getByRole('button',{name:'確認模擬操作',exact:true}).click();await expect(dialog).toBeVisible();expect((await view(page)).version).toBe(before.version);await dialog.getByLabel(/^任務名稱/).fill('WB台北逾期任務');await dialog.getByLabel('到期時間',{exact:true}).fill('2001-01-02T03:04');await submit(page);let w=(await view(page)).workspace,task=w.tasks.find((v:any)=>v.title==='WB台北逾期任務');expect(task.due_at).toBe('2001-01-01T19:04:00.000Z');expect(task.status).toBe('todo');
 await nav(page).getByRole('button',{name:'工作總覽',exact:true}).click();const queue=page.getByTestId('work-queue');await queue.locator('button[data-queue-id="task:'+task.id+':progress"]').click();const row=await focused(page,'task',task.id);await row.getByRole('button',{name:'更新進度',exact:true}).click();dialog=page.getByRole('dialog');await expect(dialog.getByLabel('到期時間',{exact:true})).toHaveValue('2001-01-02T03:04');await dialog.getByLabel('到期時間',{exact:true}).fill('');await dialog.getByRole('combobox',{name:'進度',exact:true}).selectOption('in_progress');await submit(page);w=(await view(page)).workspace;task=w.tasks.find((v:any)=>v.id===task.id);expect(task.due_at).toBe(null);expect(task.status).toBe('in_progress');await nav(page).getByRole('button',{name:'工作總覽',exact:true}).click();await expect(queue.locator('button[data-queue-id="task:'+task.id+':progress"]')).toContainText('更新進度');await expect(queue.locator('button[data-queue-id="task:'+task.id+':progress"]')).not.toContainText('處理逾期待辦');await nav(page).getByRole('button',{name:'任務與里程碑',exact:true}).click();await card(page,'task',task.id).getByRole('button',{name:'更新進度',exact:true}).click();await page.getByRole('dialog').getByRole('combobox',{name:'進度',exact:true}).selectOption('done');await submit(page);expect((await view(page)).workspace.tasks.find((v:any)=>v.id===task.id).status).toBe('done');await nav(page).getByRole('button',{name:'工作總覽',exact:true}).click();await expect(queue).not.toContainText('WB台北逾期任務');
});

test('320px search dialog, list filters and focused record stay within the viewport',async({page})=>{
 await page.setViewportSize({width:320,height:850});await setup(page);const stable=(await view(page)).workspace,product=stable.products[0];await page.getByTestId('workspace-search-open').click();const dialog=page.getByTestId('workspace-search-dialog');await expect(dialog).toBeVisible();expect(await dialog.evaluate(el=>el.scrollWidth<=el.clientWidth+1)).toBe(true);await page.getByTestId('workspace-search-input').fill(product.sku);await dialog.locator(`[data-record-id="${product.id}"]`).click();await focused(page,'product',product.id);const list=page.getByTestId('records-product');await list.getByRole('searchbox',{name:'搜尋商品目錄',exact:true}).fill('missing SKU');await expect(list.locator('article')).toHaveCount(0);await list.getByRole('searchbox',{name:'搜尋商品目錄',exact:true}).fill('');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);expect((await view(page)).workspace).toEqual(stable);await page.screenshot({path:test.info().outputPath('workbench-mobile-320.png'),fullPage:true});
});

test('blocked storage writes retain mounted-tab pending operation and retry the original key exactly once',async({page})=>{
 await setup(page);await page.evaluate(()=>{sessionStorage.setItem('workbench-readable-test','previous');const original=Storage.prototype.setItem;Storage.prototype.setItem=function(this:Storage,key:string,value:string){if(this===sessionStorage)throw new DOMException('Storage writes blocked','QuotaExceededError');return original.call(this,key,value);};});const before=(await view(page)).workspace,keys:string[]=[];page.on('request',r=>{if(r.url().endsWith('/api/workspace/commands'))keys.push(r.headers()['idempotency-key']);});await nav(page).getByRole('button',{name:'客戶與商機',exact:true}).click();await page.route('**/api/workspace/commands',route=>route.abort('failed'),{times:1});await page.getByRole('button',{name:'新增客戶',exact:true}).click();await page.getByRole('dialog').getByLabel(/^客戶名稱/).fill('WB暫存待確認');await page.getByRole('dialog').getByRole('button',{name:'確認模擬操作',exact:true}).click();await expect(page.getByRole('alert').filter({hasText:'上次操作的結果尚未確認'})).toContainText('原操作暫存於本分頁');expect(await page.evaluate(()=>sessionStorage.getItem('workbench-readable-test'))).toBe('previous');expect(keys).toHaveLength(1);expect((await view(page)).workspace).toEqual(before);await page.getByRole('button',{name:'確認原操作結果',exact:true}).click();await expect(page.getByRole('status').filter({hasText:'已確認並恢復原操作。'})).toBeVisible();expect(keys).toHaveLength(2);expect(keys[0]).toBe(keys[1]);const w=(await view(page)).workspace;expect(w.version).toBe(before.version+1);expect(w.customers.filter((v:any)=>v.name==='WB暫存待確認')).toHaveLength(1);expect(w.wallets).toEqual(before.wallets);expect(w.ledger).toEqual(before.ledger);expect(w.simulation).toBe(true);expect(w.real_finance).toBe(false);
});
