import test from 'node:test';
import assert from 'node:assert/strict';
import {createWorld,command,validateWorld} from '../src/engine.js';
const run=(w:any,a:string,p:any)=>command(w,a,p).workspace;
function stock(){let w=createWorld('general','測試店');w=run(w,'wallet.fund',{wallet_id:w.wallets[0].id,amount_minor:1000000});w=run(w,'wallet.fund',{wallet_id:w.wallets[3].id,amount_minor:1000000});return w;}
test('FIFO reservations partial payment shipping returns and conservation',()=>{let w=stock();const id=w.products[0].id;w=run(w,'inventory.receive',{product_id:id,quantity:3});w=run(w,'product.update',{id,cost_minor:7000});w=run(w,'inventory.receive',{product_id:id,quantity:2});w=run(w,'order.create',{buyer_wallet_id:w.wallets[3].id,lines:[{product_id:id,quantity:4}]});const o=w.orders[0];w=run(w,'order.pay',{id:o.id,amount_minor:10000});assert.throws(()=>run(w,'order.ship',{id:o.id,lines:[{line_id:o.lines[0].id,quantity:1}]}));w=run(w,'order.pay',{id:o.id,amount_minor:30000});w=run(w,'order.ship',{id:o.id,lines:[{line_id:o.lines[0].id,quantity:4}]});assert.equal(w.products[0].stock_value_minor,7000);w=run(w,'order.return',{id:o.id,lines:[{line_id:o.lines[0].id,quantity:2}]});assert.equal(w.products[0].stock_value_minor,17000);assert.equal(w.wallets.reduce((s:number,v:any)=>s+v.balance_minor,0),0);validateWorld(w);});
test('manufacturing transfers FIFO material value with integer remainder',()=>{let w=stock();const finished=w.products[0].id,material=w.products[1].id;w=run(w,'inventory.receive',{product_id:material,quantity:10});w=run(w,'bom.create',{product_id:finished,components:[{product_id:material,quantity:3}]});w=run(w,'workOrder.create',{bom_id:w.boms.at(-1).id,quantity:3});const id=w.workOrders[0].id;w=run(w,'workOrder.reserve',{id});w=run(w,'workOrder.start',{id});const money=JSON.stringify(w.wallets);w=run(w,'workOrder.complete',{id});assert.equal(w.products[0].on_hand,3);assert.equal(w.products[0].stock_value_minor,4500);assert.equal(w.products[1].on_hand,1);assert.equal(JSON.stringify(w.wallets),money);assert.throws(()=>run(w,'workOrder.complete',{id}));});
test('insufficient material and module disabled leave source unchanged',()=>{const w=createWorld('retail','甲');const before=JSON.stringify(w);assert.throws(()=>run(w,'bom.create',{product_id:w.products[0].id,components:[{product_id:w.products[1].id,quantity:1}]}));assert.equal(JSON.stringify(w),before);let m=stock();m=run(m,'bom.create',{product_id:m.products[0].id,components:[{product_id:m.products[1].id,quantity:1}]});m=run(m,'workOrder.create',{bom_id:m.boms.at(-1).id,quantity:5});const saved=JSON.stringify(m);assert.throws(()=>run(m,'workOrder.reserve',{id:m.workOrders[0].id}));assert.equal(JSON.stringify(m),saved);});
test('quote latest digest expiration and service latest delivery',()=>{let w=stock();w=run(w,'case.create',{title:'測試服務'});const case_id=w.cases[0].id;w=run(w,'quote.create',{case_id,amount_minor:1000,expires_at:'2099-01-01T00:00:00Z'});w=run(w,'quote.issue',{id:w.quotes[0].id});const old=w.quotes[0];w=run(w,'quote.create',{case_id,amount_minor:2000,expires_at:'2099-01-01T00:00:00Z'});w=run(w,'quote.issue',{id:w.quotes[1].id});assert.throws(()=>run(w,'quote.confirm',{id:old.id,digest:old.digest}));w=run(w,'service.create',{case_id,amount_minor:1000});const id=w.services.at(-1).id;w=run(w,'service.confirm',{id});w=run(w,'service.deliver',{id,artifact_ref:'v1'});const d=w.services.at(-1).deliveries[0];w=run(w,'service.deliver',{id,artifact_ref:'v2'});assert.throws(()=>run(w,'service.accept',{id,delivery_id:d.id,digest:d.digest}));});
test('import rejects collision and foreign links',()=>{const w=stock();const a=structuredClone(w);a.products[0].id=a.wallets[0].id;assert.throws(()=>validateWorld(a));const b=structuredClone(w);b.contacts.push({id:'bad',customer_id:'foreign'});assert.throws(()=>validateWorld(b));});test('manufacturing cost remainder stays in finished FIFO layers',()=>{let w=stock();const material=w.products[1].id,finished=w.products[0].id;w=run(w,'product.update',{id:material,cost_minor:500});w=run(w,'inventory.receive',{product_id:material,quantity:2});w=run(w,'product.update',{id:material,cost_minor:501});w=run(w,'inventory.receive',{product_id:material,quantity:1});w=run(w,'bom.create',{product_id:finished,components:[{product_id:material,quantity:1}]});w=run(w,'workOrder.create',{bom_id:w.boms.at(-1).id,quantity:3});const id=w.workOrders[0].id;w=run(w,'workOrder.reserve',{id});w=run(w,'workOrder.start',{id});w=run(w,'workOrder.complete',{id});assert.equal(w.products[0].stock_value_minor,1501);assert.equal(w.products[0].lots.reduce((s:number,l:any)=>s+l.quantity*l.cost_minor,0),1501);assert.equal(w.workOrders[0].actual_cost_minor,1501);});
