import test from 'node:test';
import assert from 'node:assert/strict';
import {createWorld,command,validateWorld} from '../src/engine.js';
import {availablePaths,createLearningSession,evaluateLearning,prepareLearningCommand,captureLearningCheckpoint,isLearningSession,type LearningPathId,type LearningSession} from '../web/learning.js';
function executeStep(w:any,s:LearningSession){const progress=evaluateLearning(w,s);const step=progress.steps[progress.nextIndex].step;const prepared=prepareLearningCommand(w,s,step.id);if('blocked'in prepared)assert.fail(prepared.blocked);const before=JSON.stringify(w);const applied=command(w,prepared.action,prepared.payload);assert.equal(JSON.stringify(w),before,'preparation and engine must preserve original snapshot');assert.equal(applied.workspace.version,w.version+1,'each step performs exactly one command');const next=captureLearningCheckpoint(s,step.id,prepared,applied.result,applied.workspace);assert.equal(next.checkpoints.length,s.checkpoints.length+1);assert.equal(s.checkpoints.length,next.checkpoints.length-1,'capturing leaves previous session intact');return {w:applied.workspace,s:next};}
for(const [path,industry,count]of [['sales','retail',8],['manufacturing','manufacturing',6],['service','service',12]]as const)test(`actual engine completes ${path} with isolated records and SIM conservation`,()=>{let w=createWorld(industry,'教學測試');let s=createLearningSession(w,path);const seedOrders=w.orders.length,seedWork=w.workOrders.length;for(let i=0;i<count;i++)({w,s}=executeStep(w,s));const result=evaluateLearning(w,s);assert.equal(result.complete,true);assert.equal(result.nextIndex,count);assert.ok(result.steps.every(v=>v.complete&&v.evidence.length>0));assert.equal(w.currency,'SIM');assert.equal(w.real_finance,false);assert.equal(w.wallets.reduce((sum:number,v:any)=>sum+v.balance_minor,0),0);validateWorld(w);if(path==='sales'){const o=w.orders.at(-1);assert.equal(w.orders.length,seedOrders+1);assert.equal(o.learning_run_id,s.runId);assert.equal(o.status,'shipped');assert.equal(o.buyer_wallet_id,s.checkpoints.find(c=>c.stepId==='buyer')?.result);}if(path==='manufacturing'){const o=w.workOrders.at(-1);assert.equal(w.workOrders.length,seedWork+1);assert.equal(o.learning_run_id,s.runId);assert.equal(o.status,'completed');assert.equal(o.actual_cost_minor,w.purchases.at(-1).total_minor);}if(path==='service'){assert.equal(w.services.at(-1).paid_minor,100000);assert.equal(w.quotes.at(-1).legal_confirmation,false);}});
test('disabled modules remove unavailable paths and cannot create a session',()=>{const w=createWorld('retail','店');assert.deepEqual(availablePaths(w).map(p=>p.id),['sales']);assert.throws(()=>createLearningSession(w,'service'));const crm=createWorld('general','CRM',['crm']);assert.deepEqual(availablePaths(crm),[]);});
test('generation changes invalidate checkpoints and never inherit finished state',()=>{let w=createWorld('retail','甲');let s=createLearningSession(w,'sales');({w,s}=executeStep(w,s));const other=createWorld('retail','乙');other.version=w.version;assert.equal(isLearningSession(s,other),false);assert.equal(evaluateLearning(other,s).steps[0].complete,false);assert.ok('blocked'in prepareLearningCommand(other,s,'customer'));});
test('ordinary existing records and history cannot complete a fresh learning session',()=>{let w=createWorld('service','服務');w=command(w,'customer.create',{name:'既有客戶'}).workspace;const fresh=createLearningSession(w,'service');assert.equal(evaluateLearning(w,fresh).nextIndex,0);const history=w.history.at(-1);const forged={...fresh,checkpoints:[{stepId:'customer',action:'customer.create',payload:{name:'既有客戶'},result:history.result,version:history.version}]};assert.equal(evaluateLearning(w,forged).steps[0].complete,false);});
test('session validation rejects malformed, oversized, mismatched and duplicate storage safely',()=>{const w=createWorld('retail','甲');const s=createLearningSession(w,'sales');for(const malformed of [null,[],{}, {...s,path:'unknown'}, {...s,runId:'bad'}, {...s,extra:true}, {...s,checkpoints:[null]}, {...s,checkpoints:[{stepId:'customer',action:'customer.create',result:'a',version:1,payload:{name:'x'.repeat(40000)}}]}])assert.equal(isLearningSession(malformed,w),false);const circular:any={};circular.x=circular;assert.equal(isLearningSession({...s,checkpoints:[{stepId:'customer',action:'customer.create',result:'a',version:0,payload:circular}]},w),false);assert.equal(isLearningSession(s,w,'service'),false);});
test('checkpoints require precise action/result/version history and actual entity evidence',()=>{const w=createWorld('retail','甲');const s=createLearningSession(w,'sales');const prepared=prepareLearningCommand(w,s,'customer');assert.ok(!('blocked'in prepared));if('blocked'in prepared)throw new Error();const applied=command(w,prepared.action,prepared.payload);assert.throws(()=>captureLearningCheckpoint(s,'customer',prepared,'foreign',applied.workspace));const missing=structuredClone(applied.workspace);missing.history=[];assert.throws(()=>captureLearningCheckpoint(s,'customer',prepared,applied.result,missing));const next=captureLearningCheckpoint(s,'customer',prepared,applied.result,applied.workspace);const wrong=structuredClone(next);wrong.checkpoints[0].version++;assert.equal(evaluateLearning(applied.workspace,wrong).steps[0].complete,false);assert.ok('blocked'in prepareLearningCommand(applied.workspace,next,'ship'));});
test('multi-component BOM is blocked without silently buying multiple products',()=>{let w=createWorld('manufacturing','廠');w.boms[0].components.push({product_id:w.products[0].id,quantity:1});const s=createLearningSession(w,'manufacturing');const before=JSON.stringify(w);assert.ok('blocked'in prepareLearningCommand(w,s,'fund-business'));assert.equal(JSON.stringify(w),before);});
test('later manufactured state preserves earlier reserve and start checkpoints',()=>{let w=createWorld('manufacturing','廠');let s=createLearningSession(w,'manufacturing');for(let i=0;i<6;i++)({w,s}=executeStep(w,s));const result=evaluateLearning(w,s);assert.equal(result.steps.find(v=>v.step.id==='reserve')?.complete,true);assert.equal(result.steps.find(v=>v.step.id==='start')?.complete,true);});
test('receipt version recovers a lost response after an unrelated later write',()=>{let w=createWorld('retail','甲');const s=createLearningSession(w,'sales');const prepared=prepareLearningCommand(w,s,'customer');if('blocked'in prepared)throw new Error(prepared.blocked);const applied=command(w,prepared.action,prepared.payload);const receiptVersion=applied.workspace.version;w=command(applied.workspace,'customer.create',{name:'另一分頁的客戶'}).workspace;assert.throws(()=>captureLearningCheckpoint(s,'customer',prepared,applied.result,w));const recovered=captureLearningCheckpoint(s,'customer',prepared,applied.result,w,receiptVersion);assert.equal(recovered.checkpoints[0].version,receiptVersion);assert.equal(evaluateLearning(w,recovered).nextIndex,1);});
test('preview shows a human description and procurement funding is exact',()=>{let w=createWorld('retail','甲');let s=createLearningSession(w,'sales');({w,s}=executeStep(w,s));({w,s}=executeStep(w,s));const prepared=prepareLearningCommand(w,s,'fund-business');if('blocked'in prepared)throw new Error(prepared.blocked);assert.equal(prepared.payload.amount_minor,w.products[0].cost_minor);assert.ok(prepared.preview.includes('SIM'));assert.ok(!prepared.preview.includes(s.runId));assert.ok(!prepared.preview.includes('wallet_id'));});
test('a mismatched funding command is not acknowledged as the exact learning step',()=>{let w=createWorld('retail','甲');let s=createLearningSession(w,'sales');({w,s}=executeStep(w,s));({w,s}=executeStep(w,s));const business=w.wallets.find((v:any)=>v.kind==='business');const wrong={action:'wallet.fund',payload:{wallet_id:business.id,amount_minor:1}};const applied=command(w,wrong.action,wrong.payload);assert.throws(()=>captureLearningCheckpoint(s,'fund-business',wrong,applied.result,applied.workspace));});
