import test from 'node:test';
import assert from 'node:assert/strict';
import {createWorld,command} from '../src/engine.js';
import {createLearningSession,prepareLearningCommand,captureLearningCheckpoint,evaluateLearning,type LearningSession} from '../web/learning.js';
import {emptyLearningView,learningFacts,readLearningView,writeLearningView,type LearningViewState} from '../web/learning-view.js';
const storage=new Map<string,string>();let denied=false;
Object.defineProperty(globalThis,'sessionStorage',{configurable:true,value:{getItem(key:string){if(denied)throw new Error('blocked');return storage.get(key)??null;},setItem(key:string,value:string){if(denied)throw new Error('blocked');storage.set(key,value);}}});
const key=(w:any,s:LearningSession)=>`freedom-erp.learning-view.v1.${encodeURIComponent(w.generation_id)}.${s.path}.${s.runId}`;
function advance(w:any,s:LearningSession){const p=evaluateLearning(w,s);const cmd=prepareLearningCommand(w,s,p.steps[p.nextIndex].step.id);if('blocked'in cmd)throw new Error(cmd.blocked);const applied=command(w,cmd.action,cmd.payload);return {w:applied.workspace,s:captureLearningCheckpoint(s,p.steps[p.nextIndex].step.id,cmd,applied.result,applied.workspace)};}
function finish(industry:string,path:'sales'|'service'|'manufacturing'){let w=createWorld(industry,'教學');let s=createLearningSession(w,path);while(!evaluateLearning(w,s).complete)({w,s}=advance(w,s));return {w,s};}
const values=(facts:ReturnType<typeof learningFacts>)=>Object.fromEntries(facts.map(v=>[v.label,v.value]));
test('sales facts isolate the run buyer, customer and order from unrelated records',()=>{let {w,s}=finish('retail','sales');w=command(w,'wallet.create',{name:'其他買家',kind:'buyer'}).workspace;const other=w.wallets.at(-1);w=command(w,'wallet.fund',{wallet_id:other.id,amount_minor:999999}).workspace;w=command(w,'customer.create',{name:'其他顧客'}).workspace;let second=createLearningSession(w,'sales');while(!evaluateLearning(w,second).complete)({w,s:second}=advance(w,second));const lesson=values(learningFacts(w,s));const workspace=values(learningFacts(w,s,'workspace'));assert.equal(lesson['本輪顧客'],'1 位');assert.equal(lesson['本輪訂單'],'1 筆');assert.equal(workspace['工作區訂單'],'2 筆');assert.equal(lesson['本輪已出貨'],'1 件');assert.equal(lesson['本輪買家測試幣'],'0 SIM');assert.notEqual(workspace['工作區買家測試幣'],lesson['本輪買家測試幣']);assert.ok(learningFacts(w,s).some(f=>f.label.startsWith('共用商品')));});
test('service facts exclude the seed and another completed lesson',()=>{let {w,s}=finish('service','service');let second=createLearningSession(w,'service');while(!evaluateLearning(w,second).complete)({w,s:second}=advance(w,second));const own=values(learningFacts(w,s));const all=values(learningFacts(w,s,'workspace'));assert.equal(own['本輪案件'],'1 件');assert.equal(own['本輪報價'],'1 份');assert.equal(own['本輪交付版本'],'1 份');assert.equal(own['本輪服務收款'],'1,000 SIM');assert.equal(all['工作區服務收款'],'2,000 SIM');assert.equal(all['工作區案件'],'3 件');});
test('manufacturing facts follow own frozen BOM rather than first workspace BOM',()=>{let w=createWorld('manufacturing','廠');const first=w.boms[0];w=command(w,'product.create',{name:'本輪新成品',sku:'OWN-FG',price_minor:10000,cost_minor:500}).workspace;const finished=w.products.at(-1);w=command(w,'product.create',{name:'本輪新材料',sku:'OWN-MAT',price_minor:1000,cost_minor:777}).workspace;const material=w.products.at(-1);w=command(w,'bom.create',{product_id:finished.id,components:[{product_id:material.id,quantity:2}]}).workspace;const ownBom=w.boms.at(-1);w=command(w,'product.update',{id:first.product_id,active:false}).workspace;let s=createLearningSession(w,'manufacturing');while(!evaluateLearning(w,s).complete)({w,s}=advance(w,s));assert.notEqual(ownBom.id,first.id);const facts=learningFacts(w,s);assert.ok(facts.some(f=>f.label==='共用材料現有量 · 本輪新材料'&&f.value==='0 件'));assert.ok(facts.some(f=>f.label==='共用成品現有量 · 本輪新成品'&&f.value==='1 件'));assert.equal(values(facts)['本輪完工成本'],'15.54 SIM');assert.equal(values(facts)['本輪完工數量'],'1 件');});
test('a new lesson shows no existing run totals or unrelated buyer balance',()=>{const {w}=finish('retail','sales');const fresh=createLearningSession(w,'sales');const facts=values(learningFacts(w,fresh));assert.equal(facts['本輪訂單'],'0 筆');assert.equal(facts['本輪顧客'],'0 位');assert.equal(facts['本輪買家測試幣'],'0 SIM');});
test('view state resumes chapter answer scope compact and historical snapshot without completing a step',()=>{let w=createWorld('retail','甲');let s=createLearningSession(w,'sales');({w,s}=advance(w,s));const c=s.checkpoints[0];const state:LearningViewState={selectedStep:'ship',choice:1,scope:'workspace',compact:true,snapshots:{customer:{version:c.version,result:c.result,rows:[{label:'本輪顧客',before:'0 位',after:'1 位'}]}}};writeLearningView(w,s,state);assert.deepEqual(readLearningView(w,s),state);assert.equal(evaluateLearning(w,s).nextIndex,1);w=command(w,'customer.create',{name:'另一位'}).workspace;assert.deepEqual(readLearningView(w,s),state,'later unrelated mutation retains historical readings');const reset=createWorld('retail','乙');assert.deepEqual(readLearningView(reset,s),emptyLearningView());const next=createLearningSession(w,'sales');assert.deepEqual(readLearningView(w,next),emptyLearningView());});
test('cached snapshots are dropped when receipt history or checkpoint result/version is absent',()=>{let w=createWorld('retail','甲');let s=createLearningSession(w,'sales');({w,s}=advance(w,s));const c=s.checkpoints[0];const state={...emptyLearningView(),selectedStep:'customer',snapshots:{customer:{version:c.version,result:c.result,rows:[{label:'顧客',before:'0',after:'1'}]}}};writeLearningView(w,s,state);const noHistory=structuredClone(w);noHistory.history=[];assert.deepEqual(readLearningView(noHistory,s).snapshots,{});storage.set(key(w,s),JSON.stringify({...state,snapshots:{customer:{...state.snapshots.customer,result:'other'},buyer:{version:c.version,result:c.result,rows:[]}}}));assert.deepEqual(readLearningView(w,s).snapshots,{});});
test('malformed and oversized browser cache returns safe defaults or discards invalid snapshots',()=>{const w=createWorld('retail','甲');const s=createLearningSession(w,'sales');for(const raw of ['{bad','null',JSON.stringify({...emptyLearningView(),choice:3}),JSON.stringify({...emptyLearningView(),selectedStep:'unknown'}),JSON.stringify({...emptyLearningView(),scope:'unsafe'}),JSON.stringify({...emptyLearningView(),extra:true}),' '.repeat(65537)]){storage.set(key(w,s),raw);assert.deepEqual(readLearningView(w,s),emptyLearningView());}const cyclic:any=emptyLearningView();cyclic.snapshots.loop=cyclic;assert.doesNotThrow(()=>writeLearningView(w,s,cyclic));});
test('blocked browser storage preserves this page view in memory without crossing runs',()=>{const w=createWorld('service','甲');const s=createLearningSession(w,'service');const state={...emptyLearningView(),selectedStep:'deliver',choice:2,compact:true};denied=true;try{writeLearningView(w,s,state);assert.deepEqual(readLearningView(w,s),state);assert.deepEqual(readLearningView(w,createLearningSession(w,'service')),emptyLearningView());}finally{denied=false;}});
test('shared stock before the first procurement is the actual preview product stock',()=>{let w=createWorld('retail','店');w=command(w,'wallet.fund',{wallet_id:w.wallets.find((v:any)=>v.kind==='business').id,amount_minor:100000}).workspace;w=command(w,'inventory.receive',{product_id:w.products[0].id,quantity:5}).workspace;const s=createLearningSession(w,'sales');assert.ok(learningFacts(w,s).some(f=>f.label.startsWith('共用商品現有量')&&f.value==='5 件'));assert.equal(values(learningFacts(w,s))['本輪訂單'],'0 筆');});
test('malformed snapshot rows and excessive snapshots do not survive validation',()=>{let w=createWorld('retail','甲');let s=createLearningSession(w,'sales');({w,s}=advance(w,s));const c=s.checkpoints[0];storage.set(key(w,s),JSON.stringify({...emptyLearningView(),selectedStep:'customer',snapshots:{customer:{version:c.version,result:c.result,rows:Array.from({length:13},()=>({label:'顧客',before:'0',after:'1'}))}}}));assert.deepEqual(readLearningView(w,s).snapshots,{});const snapshot={version:c.version,result:c.result,rows:[{label:'顧客',before:'0',after:1}]};storage.set(key(w,s),JSON.stringify({...emptyLearningView(),snapshots:{customer:snapshot}}));assert.deepEqual(readLearningView(w,s).snapshots,{});});
