import {randomUUID} from 'node:crypto';
import {apply as legacyApply,freshWorld,report} from './domain.js';
import {digest,ok} from './problem.js';
import {getTemplate,modules,moduleDependencies} from './templates.js';
export {report};
export type World=ReturnType<typeof createWorld>;
const collections=['customers','contacts','deals','cases','quotes','milestones','tasks','boms','workOrders','history'] as const;
export function createWorld(industry:string,company_name:string,enabled?:string[],version=0){const t=getTemplate(industry);ok(t,422,'industry_invalid','無效產業範本');ok(typeof company_name==='string'&&company_name.trim().length>0&&company_name.length<=100,422,'name_invalid','請填店名');const selected=enabled??t.modules;ok(Array.isArray(selected)&&selected.every(m=>modules.includes(m as any))&&new Set(selected).size===selected.length,422,'module_invalid','無效模組');for(const m of selected)ok((moduleDependencies[m]??[]).every(dep=>selected.includes(dep)),422,'module_dependency',m+' 需要 '+(moduleDependencies[m]??[]).join('、'));const w:any={...freshWorld(),schemaVersion:1,templateVersion:t.version,version,generation_id:randomUUID(),industry,company_name:company_name.trim(),modules:selected,currency:'SIM',simulation:true,real_finance:false};for(const c of collections)w[c]=[];w.products.push({id:randomUUID(),sku:t.sample.sku,name:t.sample.product,price_minor:t.sample.price_minor,cost_minor:t.sample.cost_minor,active:true,on_hand:0,reserved:0,stock_value_minor:0,lots:[]},{id:randomUUID(),sku:'MAT-001',name:t.sample.component,price_minor:1000,cost_minor:500,active:true,on_hand:0,reserved:0,stock_value_minor:0,lots:[]});w.wallets.push({id:randomUUID(),name:'示範買家',kind:'buyer',balance_minor:0});w.customers.push({id:randomUUID(),name:t.sample.customer,created_at:new Date().toISOString()});if(selected.includes('crm')){const c={id:randomUUID(),title:t.sample.service,customer_id:w.customers[0].id,status:'open',created_at:new Date().toISOString()};w.cases.push(c);w.deals.push({id:randomUUID(),name:t.sample.service,customer_id:w.customers[0].id,status:'new',notes:'這是可清除的產業示範商機',created_at:new Date().toISOString()});if(selected.includes('services'))legacyApply(w,'service.create',{case_id:c.id,amount_minor:t.sample.price_minor},{case:{id:c.id,title:c.title},price_source:'industry_template_demo'});}if(selected.includes('manufacturing'))w.boms.push({id:randomUUID(),product_id:w.products[0].id,components:[{product_id:w.products[1].id,quantity:t.sample.bom_quantity??1}],revision:1,created_at:new Date().toISOString()});if(selected.includes('projects')){w.tasks.push({id:randomUUID(),title:t.sample.task??'確認需求',status:'todo',created_at:new Date().toISOString()});w.milestones.push({id:randomUUID(),title:t.sample.milestone??'原型驗收',status:'planned',created_at:new Date().toISOString()});}return w;}
function find(a:any[],id:string){const v=a.find(x=>x.id===id);ok(v,404,'record_missing','找不到工作區紀錄');return v;}
function integer(n:any,min=0){ok(Number.isSafeInteger(n)&&n>=min&&n<=1e9,422,'number_invalid','數量或金額必須是範圍內整數');}
const gate:Record<string,string>={product:'inventory',inventory:'inventory',order:'sales',wallet:'wallets',service:'services',customer:'crm',contact:'crm',deal:'crm',case:'crm',followup:'crm',quote:'crm',task:'projects',milestone:'projects',bom:'manufacturing',workOrder:'manufacturing'};
export function validateWorld(w:any){ok(w&&w.schemaVersion===1&&w.currency==='SIM'&&w.simulation===true&&w.real_finance===false,422,'simulation_required','只接受模擬資料');ok(getTemplate(w.industry)&&Array.isArray(w.modules)&&w.modules.every((m:any)=>modules.includes(m)),422,'schema_invalid','範本或模組不符');for(const m of w.modules)ok((moduleDependencies[m]??[]).every(dep=>w.modules.includes(dep)),422,'module_dependency','模組依賴不符');integer(w.version);ok(typeof w.generation_id==='string'&&typeof w.company_name==='string',422,'schema_invalid','工作區欄位不符');const ids=new Set<string>();for(const c of ['products','wallets','orders','services','ledger','purchases',...collections]){ok(Array.isArray(w[c])&&w[c].length<=500,422,'record_limit','紀錄超出上限');for(const row of w[c]){ok(row&&typeof row.id==='string'&&!ids.has(row.id),422,'id_collision','紀錄識別重複');ids.add(row.id);}}for(const p of w.products){integer(p.on_hand);integer(p.reserved);integer(p.stock_value_minor);integer(p.price_minor);integer(p.cost_minor);ok(p.reserved<=p.on_hand&&Array.isArray(p.lots),422,'stock_invalid','庫存不符');ok(p.lots.reduce((s:number,l:any)=>{integer(l.quantity,1);integer(l.cost_minor);return s+l.quantity;},0)===p.on_hand&&p.lots.reduce((s:number,l:any)=>s+l.quantity*l.cost_minor,0)===p.stock_value_minor,422,'stock_invalid','成本層不符');}for(const v of w.wallets){ok(['business','supplier','faucet','buyer'].includes(v.kind)&&Number.isSafeInteger(v.balance_minor)&&(v.kind==='faucet'||v.balance_minor>=0),422,'wallet_invalid','錢包不符');}ok(w.wallets.reduce((s:number,v:any)=>s+v.balance_minor,0)===0,422,'money_conservation','測試幣不守恆');for(const kind of ['business','supplier','faucet'])ok(w.wallets.filter((v:any)=>v.kind===kind).length===1,422,'wallet_invalid','系統錢包不符');for(const l of w.ledger){ok(Array.isArray(l.entries)&&l.entries.reduce((s:number,e:any)=>{find(w.wallets,e.wallet_id);ok(Number.isSafeInteger(e.amount_minor),422,'ledger_invalid','流水不符');return s+e.amount_minor;},0)===0,422,'ledger_invalid','流水不守恆');}for(const o of w.orders){find(w.wallets,o.buyer_wallet_id);for(const l of o.lines)find(w.products,l.product_id);}for(const b of w.boms){find(w.products,b.product_id);for(const c of b.components)find(w.products,c.product_id);}for(const x of w.workOrders)find(w.boms,x.bom_id);for(const c of [...w.contacts,...w.deals,...w.cases,...w.tasks,...w.milestones]){if(c.customer_id)find(w.customers,c.customer_id);if(c.case_id)find(w.cases,c.case_id);}for(const s of [...w.services,...w.quotes])find(w.cases,s.case_id);validateIntegrity(w);ok(JSON.stringify(w).length<=1000000,422,'workspace_limit','工作區超出容量');}
export function command(original:any,action:string,p:any){const w=structuredClone(original);ok(p&&typeof p==='object'&&!Array.isArray(p),422,'payload_invalid','參數不符');ok(!Object.keys(p).some(k=>/(bank|payer|finance|legal|payment_url)/i.test(k)),422,'simulation_required','不允許真實金融欄位');const prefix=action.split('.')[0];ok(gate[prefix]&&w.modules.includes(gate[prefix]),403,'module_disabled','模組未啟用');ok(!['currency','simulation','real_finance','balance_minor','on_hand','reserved','lots','stock_value_minor'].some(k=>k in p),422,'protected_field','不能覆寫系統欄位');const now=new Date().toISOString();let result:string;
 if('learning_run_id' in p)ok(['order.create','workOrder.create'].includes(action)&&typeof p.learning_run_id==='string'&&/^[A-Za-z0-9_-]{8,80}$/.test(p.learning_run_id),422,'learning_id_invalid','教學識別不符');
 if(['product.create','product.update'].includes(action)){if(action==='product.create'){ok(typeof p.name==='string'&&p.name.length>0&&p.name.length<=100&&typeof p.sku==='string',422,'product_invalid','請填商品名稱及SKU');}for(const k of ['price_minor','cost_minor'])if(k in p)integer(p[k]);ok(Object.keys(p).every(k=>['id','name','sku','price_minor','cost_minor','active'].includes(k)),422,'product_invalid','商品欄位不符');}
 if(action==='wallet.create')ok(p.kind==='buyer'&&typeof p.name==='string',422,'wallet_invalid','只能建立買家錢包');
 for(const k of ['quantity','amount_minor'])if(k in p)integer(p[k],1);if(p.lines){ok(Array.isArray(p.lines)&&p.lines.length>0&&p.lines.length<=50,422,'lines_invalid','品項不符');for(const l of p.lines)integer(l.quantity,1);}
 const crud:Record<string,string>={customer:'customers',contact:'contacts',deal:'deals',case:'cases',task:'tasks',milestone:'milestones'};
 if(crud[prefix]&&['create','update'].includes(action.split('.')[1])){ok(Object.keys(p).every(k=>['id','name','title','customer_id','case_id','status','notes','lost_reason','due_at','email','phone','amount_minor'].includes(k)),422,'fields_invalid','欄位不符');ok(JSON.stringify(p).length<=4000,422,'text_limit','文字過長');if(p.status==='lost')ok(typeof p.lost_reason==='string'&&p.lost_reason.trim(),422,'lost_reason_required','請填失單原因');const row=action.endsWith('.create')?{...p,id:randomUUID(),created_at:now}:find(w[crud[prefix]],p.id);Object.assign(row,p,{id:row.id,updated_at:now});if(action.endsWith('.create'))w[crud[prefix]].push(row);result=row.id;}
 else if(action==='followup.create'){const d=find(w.deals,p.deal_id);ok(typeof p.note==='string'&&p.note.length<=2000,422,'note_invalid','請填追蹤內容');d.followups??=[];d.followups.push({id:randomUUID(),note:p.note,created_at:now});result=d.id;}
 else if(action.startsWith('quote.')){if(action==='quote.create'){find(w.cases,p.case_id);integer(p.amount_minor);ok(typeof p.expires_at==='string'&&Number.isFinite(Date.parse(p.expires_at)),422,'expiry_invalid','請填有效期限');const q={id:randomUUID(),case_id:p.case_id,amount_minor:p.amount_minor,expires_at:p.expires_at,status:'draft',legal_confirmation:false,created_at:now};w.quotes.push(q);result=q.id;}else{const q=find(w.quotes,p.id);if(action==='quote.issue'){ok(q.status==='draft',409,'quote_immutable','已發出報價不可修改');q.status='issued';q.issued_at=now;q.digest=digest({id:q.id,case_id:q.case_id,amount_minor:q.amount_minor,expires_at:q.expires_at});for(const old of w.quotes.filter((x:any)=>x.case_id===q.case_id&&x.id!==q.id&&x.status==='issued'))old.status='superseded';}else{ok(action==='quote.confirm'&&q.status==='issued'&&q.digest===p.digest&&Date.parse(q.expires_at)>Date.now(),409,'quote_outdated','報價已過期或不是最新版本');q.status='simulated_confirmed';}result=q.id;}}
 else if(action==='bom.create'){find(w.products,p.product_id);ok(Array.isArray(p.components)&&p.components.length>0&&p.components.length<=30,422,'bom_invalid','請指定材料');const seen=new Set();for(const c of p.components){find(w.products,c.product_id);integer(c.quantity,1);ok(c.product_id!==p.product_id&&!seen.has(c.product_id),422,'bom_cycle','材料不能重複或包含成品');seen.add(c.product_id);}const edges=new Map<string,string[]>();for(const b of w.boms)edges.set(b.product_id,b.components.map((c:any)=>c.product_id));edges.set(p.product_id,p.components.map((c:any)=>c.product_id));const visit=(id:string,path:Set<string>)=>{ok(!path.has(id),422,'bom_cycle','BOM不能循環');for(const next of edges.get(id)??[])visit(next,new Set([...path,id]));};visit(p.product_id,new Set());const b={id:randomUUID(),product_id:p.product_id,components:structuredClone(p.components),revision:w.boms.filter((x:any)=>x.product_id===p.product_id).length+1,created_at:now};w.boms.push(b);result=b.id;}
 else if(action.startsWith('workOrder.')){if(action==='workOrder.create'){const b=find(w.boms,p.bom_id);integer(p.quantity,1);const o={id:randomUUID(),...(p.learning_run_id?{learning_run_id:p.learning_run_id}:{}),bom_id:b.id,bom_snapshot:structuredClone(b),quantity:p.quantity,status:'planned',created_at:now};w.workOrders.push(o);result=o.id;}else{const o=find(w.workOrders,p.id);if(action==='workOrder.reserve'){ok(o.status==='planned',409,'production_state','請先建立計畫');for(const c of o.bom_snapshot.components){const v=find(w.products,c.product_id);const n=c.quantity*o.quantity;integer(n,1);ok(v.on_hand-v.reserved>=n,409,'materials_insufficient','材料不足');v.reserved+=n;}o.status='reserved';}else if(action==='workOrder.start'){ok(o.status==='reserved',409,'production_state','請先預留材料');o.status='started';}else if(action==='workOrder.complete'){ok(o.status==='started',409,'production_state','請先開工');let cost=0;o.consumed_material_lots=[];for(const c of o.bom_snapshot.components){const v=find(w.products,c.product_id);let n=c.quantity*o.quantity;v.on_hand-=n;v.reserved-=n;while(n){const lot=v.lots[0];ok(lot,409,'stock_invalid','材料成本層不足');const take=Math.min(n,lot.quantity);o.consumed_material_lots.push({product_id:v.id,quantity:take,cost_minor:lot.cost_minor});cost+=take*lot.cost_minor;v.stock_value_minor-=take*lot.cost_minor;lot.quantity-=take;n-=take;if(!lot.quantity)v.lots.shift();}}integer(cost);const v=find(w.products,o.bom_snapshot.product_id);const unit=Math.floor(cost/o.quantity),extra=cost%o.quantity;if(extra)v.lots.push({quantity:extra,cost_minor:unit+1});if(o.quantity-extra)v.lots.push({quantity:o.quantity-extra,cost_minor:unit});v.on_hand+=o.quantity;v.stock_value_minor+=cost;o.actual_cost_minor=cost;o.status='completed';}else if(action==='workOrder.cancel'){ok(['planned','reserved','started'].includes(o.status),409,'production_state','製作單不能取消');if(o.status!=='planned')for(const c of o.bom_snapshot.components)find(w.products,c.product_id).reserved-=c.quantity*o.quantity;o.status='cancelled';}else ok(false,422,'action_invalid','無效操作');o.updated_at=now;result=o.id;}}
 else {const allowed=['product.create','product.update','wallet.create','wallet.fund','inventory.receive','order.create','order.pay','order.cancel','order.ship','order.return','service.create','service.confirm','service.deliver','service.accept','service.request_changes','service.pay'];ok(allowed.includes(action),422,'action_invalid','無效操作');let source;if(action==='service.create'){const c=find(w.cases,p.case_id);source={case:{id:c.id,title:c.title??c.name??'模擬服務'},price_source:'explicit_simulation_input'};}result=legacyApply(w,action,p,source);}
 for(const l of w.ledger)if(!l.created_at){l.created_at=now;l.reference_id=result!;}for(const c of ['products','wallets','orders','services','purchases'])for(const row of w[c])if(row.id===result!)row.updated_at=now;
 w.version++;w.history.push({id:randomUUID(),action,result:result!,created_at:now,version:w.version});validateWorld(w);return {workspace:w,result:result!};}
function validateIntegrity(w:any){
 for(const row of [...w.orders,...w.workOrders])if('learning_run_id' in row)ok(typeof row.learning_run_id==='string'&&/^[A-Za-z0-9_-]{8,80}$/.test(row.learning_run_id),422,'learning_id_invalid','教學識別不符');
 const primaryIds=new Set([...w.products,...w.wallets,...w.orders,...w.services,...w.ledger,...w.purchases,...w.customers,...w.contacts,...w.deals,...w.cases,...w.quotes,...w.tasks,...w.milestones,...w.boms,...w.workOrders,...w.history].map((v:any)=>v.id));
 for(const p of w.products)ok(typeof p.name==='string'&&p.name.length>0&&p.name.length<=100&&typeof p.sku==='string'&&typeof p.active==='boolean',422,'product_invalid','商品欄位不符');
 for(const l of w.ledger)ok(primaryIds.has(l.reference_id)&&typeof l.created_at==='string'&&Number.isFinite(Date.parse(l.created_at)),422,'ledger_invalid','流水來源不符');
 for(const p of w.purchases){find(w.products,p.product_id);integer(p.quantity,1);integer(p.cost_minor);integer(p.total_minor);ok(p.total_minor===p.quantity*p.cost_minor,422,'purchase_invalid','採購金額不符');}
 for(const d of w.deals)if(d.status==='lost')ok(typeof d.lost_reason==='string'&&d.lost_reason.trim(),422,'lost_reason_required','請填失單原因');
 const issuedCases=new Set();for(const q of w.quotes)if(q.status==='issued'){ok(!issuedCases.has(q.case_id),422,'quote_invalid','同案件不能有兩份有效報價');issuedCases.add(q.case_id);}
 const forbidden=new Set(['bank_account','bank_url','payer_url','payment_url','real_finance','legal_confirmation','currency','simulation']);
 const scan=(v:any,key='')=>{if(v===null||typeof v!=='object')return;for(const [k,x] of Object.entries(v)){ok(!/(bank|payer|payment_url|finance|legal)/i.test(k)||['real_finance','legal_confirmation'].includes(k),422,'simulation_required','不允許真實金融欄位');if(forbidden.has(k)){ok((k==='real_finance'||k==='legal_confirmation')?x===false:k==='currency'?x==='SIM':k==='simulation'?x===true:false,422,'simulation_required','匯入僅能含模擬資料');}ok(k!=='__proto__'&&k!=='constructor'&&k!=='prototype',422,'schema_invalid','不允許此欄位');scan(x,k);}};scan(w);
  const business=w.wallets.find((v:any)=>v.kind==='business');const supplier=w.wallets.find((v:any)=>v.kind==='supplier');const faucet=w.wallets.find((v:any)=>v.kind==='faucet');const movements=new Map<string,Record<string,number>>();
 for(const l of w.ledger){ok(['wallet.fund','inventory.receive','order.pay','order.cancel','order.return','service.pay'].includes(l.kind),422,'ledger_invalid','未知流水種類');let from:string,to:string;const credit=l.entries.find((e:any)=>e.amount_minor>=0)?.amount_minor??0;if(l.kind==='wallet.fund'){from=faucet.id;to=l.entries.find((e:any)=>e.wallet_id!==faucet.id)?.wallet_id;ok(['buyer','business'].includes(find(w.wallets,to).kind)&&l.reference_id===l.id,422,'ledger_invalid','補幣流水不符');}else if(l.kind==='inventory.receive'){const p=find(w.purchases,l.reference_id);from=business.id;to=supplier.id;ok(credit===p.total_minor,422,'ledger_invalid','進貨流水不符');}else if(l.kind.startsWith('order.')){const o=find(w.orders,l.reference_id);from=l.kind==='order.pay'?o.buyer_wallet_id:business.id;to=l.kind==='order.pay'?business.id:o.buyer_wallet_id;}else {const service=find(w.services,l.reference_id);from=l.entries.find((e:any)=>e.wallet_id!==business.id)?.wallet_id;ok(find(w.wallets,from).kind==='buyer',422,'ledger_invalid','服務付款流水不符');to=business.id;}
 ok(l.entries.some((e:any)=>e.wallet_id===from&&e.amount_minor===-credit)&&l.entries.some((e:any)=>e.wallet_id===to&&e.amount_minor===credit)&&from!==to,422,'ledger_invalid','流水對象不符');const sums=movements.get(l.reference_id)??{};sums[l.kind]=(sums[l.kind]??0)+credit;movements.set(l.reference_id,sums);}
 for(const o of w.orders){const sums=movements.get(o.id)??{};ok(o.paid_minor===(sums['order.pay']??0)&&o.refunded_minor===(sums['order.return']??0)+(sums['order.cancel']??0),422,'order_invalid','訂單付款與流水不符');if(o.status==='pending')ok(o.paid_minor===0,422,'order_invalid','待付款狀態不符');if(o.status==='partially_paid')ok(o.paid_minor>0&&o.paid_minor<o.total_minor,422,'order_invalid','部分付款狀態不符');if(o.status==='paid')ok(o.paid_minor===o.total_minor,422,'order_invalid','付款狀態不符');}
 for(const service of w.services)ok(service.paid_minor===(movements.get(service.id)?.['service.pay']??0),422,'service_invalid','服務付款與流水不符');for(const p of w.purchases)ok(p.total_minor===(movements.get(p.id)?.['inventory.receive']??0),422,'purchase_invalid','採購付款與流水不符');const balances=new Map<string,number>(w.wallets.map((v:any)=>[v.id,0]));for(const l of w.ledger){ok(typeof l.kind==='string'&&l.entries.length===2,422,'ledger_invalid','流水不符');for(const e of l.entries)balances.set(e.wallet_id,balances.get(e.wallet_id)!+e.amount_minor);}for(const v of w.wallets)ok(balances.get(v.id)===v.balance_minor,422,'ledger_balance_invalid','錢包與流水不符');
 const reserved=new Map<string,number>(w.products.map((v:any)=>[v.id,0]));const nestedIds=new Set<string>([...w.products,...w.wallets,...w.orders,...w.services,...w.ledger,...w.purchases,...w.customers,...w.contacts,...w.deals,...w.cases,...w.quotes,...w.tasks,...w.milestones,...w.boms,...w.workOrders,...w.history].map((v:any)=>v.id));const unique=(id:any)=>{ok(typeof id==='string'&&!nestedIds.has(id),422,'id_collision','子紀錄識別重複');nestedIds.add(id);};
 for(const o of w.orders){ok(Array.isArray(o.lines)&&o.lines.length>0&&o.lines.length<=50,422,'order_invalid','訂單品項不符');for(const key of ['total_minor','paid_minor','refunded_minor'])integer(o[key]);ok(o.paid_minor<=o.total_minor&&o.refunded_minor<=o.paid_minor,422,'order_invalid','訂單金額不符');let total=0;const seen=new Set();for(const l of o.lines){unique(l.id);ok(!seen.has(l.product_id),422,'order_invalid','商品重複');seen.add(l.product_id);integer(l.quantity,1);integer(l.shipped_quantity);integer(l.returned_quantity);integer(l.price_minor);integer(l.cost_minor);ok(l.returned_quantity<=l.shipped_quantity&&l.shipped_quantity<=l.quantity,422,'order_invalid','出貨退貨不符');total+=l.quantity*l.price_minor;ok(Array.isArray(l.shipped_cost_lots),422,'order_invalid','成本層不符');let shipped=0,returned=0;for(const lot of l.shipped_cost_lots){integer(lot.quantity,1);integer(lot.cost_minor);integer(lot.returned);ok(lot.returned<=lot.quantity,422,'order_invalid','退貨成本層不符');shipped+=lot.quantity;returned+=lot.returned;}ok(shipped===l.shipped_quantity&&returned===l.returned_quantity,422,'order_invalid','出貨成本層不符');if(o.status!=='cancelled')reserved.set(l.product_id,reserved.get(l.product_id)!+l.quantity-l.shipped_quantity);}ok(total===o.total_minor,422,'order_invalid','訂單總額不符');ok(['pending','partially_paid','paid','partially_shipped','shipped','partially_returned','returned','cancelled'].includes(o.status),422,'order_invalid','訂單狀態不符');if(o.status==='cancelled')ok(o.paid_minor===o.refunded_minor&&o.lines.every((l:any)=>l.shipped_quantity===0),422,'order_invalid','取消訂單不符');if(o.lines.some((l:any)=>l.shipped_quantity>0))ok(o.paid_minor===o.total_minor,422,'order_invalid','出貨付款不符');}
 for(const b of w.boms){integer(b.revision,1);ok(Array.isArray(b.components)&&b.components.length>0&&b.components.length<=30,422,'bom_invalid','BOM不符');const seen=new Set();for(const c of b.components){integer(c.quantity,1);ok(c.product_id!==b.product_id&&!seen.has(c.product_id),422,'bom_invalid','材料重複或循環');seen.add(c.product_id);}}
 const edges=new Map<string,Set<string>>();for(const b of w.boms){const e=edges.get(b.product_id)??new Set();for(const c of b.components)e.add(c.product_id);edges.set(b.product_id,e);}const visit=(id:string,path:Set<string>)=>{ok(!path.has(id),422,'bom_cycle','BOM不能循環');for(const next of edges.get(id)??[])visit(next,new Set([...path,id]));};for(const id of edges.keys())visit(id,new Set());
 for(const o of w.workOrders){integer(o.quantity,1);const b=find(w.boms,o.bom_id);ok(JSON.stringify(o.bom_snapshot)===JSON.stringify(b)&&['planned','reserved','started','completed','cancelled'].includes(o.status),422,'production_invalid','製作單快照不符');if(['reserved','started'].includes(o.status))for(const c of b.components)reserved.set(c.product_id,reserved.get(c.product_id)!+c.quantity*o.quantity);if(o.status==='completed'){integer(o.actual_cost_minor);ok(Array.isArray(o.consumed_material_lots)&&o.consumed_material_lots.reduce((sum:number,l:any)=>{find(w.products,l.product_id);integer(l.quantity,1);integer(l.cost_minor);return sum+l.quantity*l.cost_minor;},0)===o.actual_cost_minor,422,'production_invalid','材料成本紀錄不符');for(const c of b.components)ok(o.consumed_material_lots.filter((l:any)=>l.product_id===c.product_id).reduce((sum:number,l:any)=>sum+l.quantity,0)===c.quantity*o.quantity,422,'production_invalid','材料用量不符');}}
 const purchasedValue=w.purchases.reduce((sum:number,p:any)=>sum+p.total_minor,0);const heldValue=w.products.reduce((sum:number,p:any)=>sum+p.stock_value_minor,0);const shippedValue=w.orders.reduce((sum:number,o:any)=>sum+o.lines.reduce((subtotal:number,l:any)=>subtotal+l.shipped_cost_lots.reduce((cost:number,lot:any)=>cost+(lot.quantity-lot.returned)*lot.cost_minor,0),0),0);ok(purchasedValue===heldValue+shippedValue,422,'stock_value_conservation','庫存及出貨成本不守恆');for(const p of w.products)ok(reserved.get(p.id)===p.reserved,422,'reservation_invalid','預留數量不符');
 for(const s of w.services){integer(s.amount_minor);integer(s.paid_minor);ok(s.currency==='SIM'&&s.legal_confirmation===false&&s.paid_minor<=s.amount_minor&&['draft','confirmed','submitted','changes_requested','accepted'].includes(s.status)&&Array.isArray(s.deliveries),422,'service_invalid','服務狀態不符');for(const d of s.deliveries){unique(d.id);integer(d.revision,1);ok(typeof d.artifact_ref==='string'&&d.digest===digest({service_id:s.id,revision:d.revision,artifact_ref:d.artifact_ref}),422,'delivery_invalid','交付摘要不符');}ok(s.latest_delivery_id===(s.deliveries.at(-1)?.id??null),422,'delivery_invalid','最新交付不符');if(s.paid_minor>0)ok(s.status==='accepted',422,'service_invalid','服務付款不符');}
 for(const q of w.quotes){integer(q.amount_minor);ok(q.legal_confirmation===false&&Number.isFinite(Date.parse(q.expires_at))&&['draft','issued','superseded','simulated_confirmed'].includes(q.status),422,'quote_invalid','報價不符');if(q.status!=='draft')ok(q.digest===digest({id:q.id,case_id:q.case_id,amount_minor:q.amount_minor,expires_at:q.expires_at}),422,'quote_invalid','報價摘要不符');}
}