import {useEffect,useRef,useState} from 'react';
import type {FormEvent,KeyboardEvent} from 'react';
import type {Workspace} from './api';
import {addDays,attendanceDifferences,formatDateTime,formatSIM,formatTime,inputToISO,localInput,monday,netMinutes,officeCSV,officeFilename,officeData,officeStatus,officeTabs,requestNames,simMinor,taipeiDate,validMonday,weekDates,type OfficeChange,type OfficeData,type OfficeRequest,type OfficeRow,type OfficeTab} from './administration-model';
import './administration.css';

export interface AdministrationDeskProps {workspace:Workspace;busy:boolean;pending:boolean;onCommand:(action:string,payload:Record<string,any>)=>Promise<{result:string;workspace:Workspace}|null>}
type Option={value:string;label:string};
type Field={key:string;label:string;type?:'text'|'textarea'|'select'|'number'|'datetime-local'|'date'|'checkbox';required?:boolean;value?:string|number|boolean;options?:Option[];nullable?:boolean;min?:number;max?:number;maxLength?:number;step?:string};
type FormConfig={title:string;action:string;description:string;fields:Field[];base?:Record<string,any>};
const optionNames=(names:Record<string,string>):Option[]=>Object.entries(names).map(([value,label])=>({value,label}));
const idField=(row:OfficeRow)=>({id:row.id});
const timeFields:Field[]=[{key:'start_at',label:'開始時間（臺北）',type:'datetime-local',required:true},{key:'end_at',label:'結束時間（臺北）',type:'datetime-local',required:true}];
const breakField:Field={key:'break_minutes',label:'休息分鐘',type:'number',min:0,max:2879,required:true,value:0};
const noteField:Field={key:'note',label:'備註（限模擬內容）',type:'textarea',maxLength:1000};
const reasonField:Field={key:'reason',label:'更正或作廢原因',type:'textarea',required:true,maxLength:1000};

export default function AdministrationDesk({workspace,busy,pending,onCommand}:AdministrationDeskProps){
 const data=officeData(workspace),enabled=workspace.modules.includes('administration');
 const [tab,setTab]=useState<OfficeTab>('shifts'),[query,setQuery]=useState(''),[unit,setUnit]=useState(''),[week,setWeek]=useState(monday()),[requestType,setRequestType]=useState(''),[requestStatus,setRequestStatus]=useState('');
 const [unitState,setUnitState]=useState(''),[staffStatus,setStaffStatus]=useState(''),[shiftStatus,setShiftStatus]=useState(''),[attendanceState,setAttendanceState]=useState('active'),[equipmentState,setEquipmentState]=useState(''),[reservationStatus,setReservationStatus]=useState(''),[noticeState,setNoticeState]=useState('active');
 const [form,setForm]=useState<FormConfig|null>(null),[saving,setSaving]=useState(false),[message,setMessage]=useState(''),[highlighted,setHighlighted]=useState(''),[now,setNow]=useState(()=>Date.now());
 useEffect(()=>{const timer=window.setInterval(()=>setNow(Date.now()),30000);return()=>window.clearInterval(timer)},[]);
 const lockRef=useRef(false),locked=busy||pending||saving;
 useEffect(()=>{setForm(null);setMessage('');setQuery('');setUnit('');setTab('shifts');setHighlighted('');setUnitState('');setStaffStatus('');setShiftStatus('');setAttendanceState('active');setRequestType('');setRequestStatus('');setEquipmentState('');setReservationStatus('');setNoticeState('active')},[workspace.generation_id]);
 const activeUnits=data.units.filter(row=>row.active),activeStaff=data.staff.filter(row=>row.status==='active'&&activeUnits.some(organization=>organization.id===row.unit_id));
 const unitName=(id:string|null)=>data.units.find(row=>row.id===id)?.name||'全體';
 const staffName=(id:string|null)=>data.staff.find(row=>row.id===id)?.alias||'未指定';
 const equipmentName=(id:string)=>data.equipment.find(row=>row.id===id)?.name||'未找到設備';
 const unitOptions=activeUnits.map(row=>({value:row.id,label:row.name})),staffOptions=activeStaff.map(row=>({value:row.id,label:`${row.alias} · ${unitName(row.unit_id)}`}));
 const today=taipeiDate(new Date(now)),days=weekDates(week),weekEnd=addDays(week,7);
 const matches=(row:any,text:string)=> (!unit||row.unit_id===unit)&&text.toLocaleLowerCase().includes(query.trim().toLocaleLowerCase());
 const chooseTab=(next:OfficeTab)=>{setTab(next);setQuery('')};
 const tabKeys=(event:KeyboardEvent<HTMLButtonElement>,index:number)=>{let next:number|undefined;if(event.key==='ArrowRight')next=(index+1)%8;if(event.key==='ArrowLeft')next=(index+7)%8;if(event.key==='Home')next=0;if(event.key==='End')next=7;if(next!==undefined){event.preventDefault();chooseTab(officeTabs[next].id);document.getElementById(`office-tab-${officeTabs[next].id}`)?.focus()}};
 const start=(config:FormConfig)=>{if(locked||lockRef.current)return;setMessage('');setForm(config)};
 const confirm=(action:string,title:string,row:OfficeRow,description:string,fields:Field[]=[])=>start({action,title,description,base:idField(row),fields});
 const execute=async(action:string,payload:Record<string,any>)=>{
  if(locked||lockRef.current)return false;lockRef.current=true;setSaving(true);setMessage('');
  try{const result=await onCommand(action,payload);if(!result)return false;
   setMessage(action==='office.enable'?'行政模擬已啟用，請先新增組織與假員工。':`已儲存「${form?.title||'行政操作'}」。`);setForm(null);setQuery('');setUnit('');setHighlighted(result.result);
   if(action.startsWith('office.unit.'))setUnitState('');if(action.startsWith('office.staff.'))setStaffStatus('');
   if(action.startsWith('office.shift.')){setShiftStatus('');if(payload.start_at)setWeek(monday(taipeiDate(payload.start_at)));else if(action==='office.shift.copy_week')setWeek(payload.to_date);}
   if(action.startsWith('office.attendance.')){setAttendanceState(action==='office.attendance.void'?'all':'active');if(payload.start_at)setWeek(monday(taipeiDate(payload.start_at)));}
   if(action.startsWith('office.request.')){setRequestType('');setRequestStatus('');}
   if(action.startsWith('office.equipment.'))setEquipmentState('');if(action.startsWith('office.reservation.'))setReservationStatus('');
   if(action.startsWith('office.notice.'))setNoticeState(action==='office.notice.archive'?'all':'active');
   if(action==='office.demo.create'){setWeek(payload.week_start);setTab('shifts');setShiftStatus('');}
   window.requestAnimationFrame(()=>document.querySelector<HTMLElement>(`.office-desk [data-record-id="${CSS.escape(result.result)}"]`)?.scrollIntoView({block:'nearest'}));return true}

  finally{lockRef.current=false;setSaving(false)}
 };
 const organizationReason=activeUnits.length?'':'先新增一個使用中的門市或部門。';
 const peopleReason=activeStaff.length?'':'先新增使用中組織與假員工。';
 const equipmentReason=data.equipment.some(row=>row.state==='available'&&activeUnits.some(organization=>organization.id===row.unit_id))?'':'先新增可借用設備。';
 const addUnit=()=>start({title:'新增組織',action:'office.unit.create',description:'先建立門市，再依需要加入部門。只填模擬名稱。',fields:[{key:'name',label:'組織名稱',required:true,maxLength:80},{key:'kind',label:'組織類型',type:'select',required:true,value:'branch',options:[{value:'branch',label:'門市'},{value:'department',label:'部門'}]},{key:'parent_id',label:'所屬門市（選填）',type:'select',nullable:true,options:activeUnits.filter(row=>row.kind==='branch').map(row=>({value:row.id,label:row.name}))}]});
 const addStaff=()=>start({title:'新增假員工',action:'office.staff.create',description:'使用代號與暱稱練習，不填真實姓名、電話或證件資料。',fields:[{key:'code',label:'假員工代號',required:true,maxLength:32},{key:'alias',label:'假員工暱稱',required:true,maxLength:80},{key:'unit_id',label:'所屬組織',type:'select',required:true,options:unitOptions},{key:'role_label',label:'職務稱呼（選填）',maxLength:80}]});
 const addTime=(attendance:boolean)=>start({title:attendance?'新增手動出勤':'新增班次',action:attendance?'office.attendance.create':'office.shift.create',description:'日期與時間以臺北時區記錄，可跨夜、最長 48 小時。休息時間手動填寫整數分鐘。',fields:[{key:'staff_id',label:'假員工',type:'select',required:true,options:staffOptions},...timeFields,breakField,noteField]});
 const addRequest=()=>start({title:'新增模擬申請',action:'office.request.create',description:'請假只記錄時段，最長 31 日；請購與費用只記錄 SIM 測試幣金額，不扣款。整理完成仍待獨立覆核。',fields:[{key:'type',label:'申請類型',type:'select',required:true,value:'general',options:optionNames(requestNames)},{key:'unit_id',label:'所屬組織',type:'select',required:true,options:unitOptions},{key:'staff_id',label:'假員工（選填）',type:'select',nullable:true,options:staffOptions},{key:'title',label:'申請標題',required:true,maxLength:100},{key:'description',label:'申請內容（限模擬內容）',type:'textarea',maxLength:1000}]});
 const addEquipment=()=>start({title:'新增設備',action:'office.equipment.create',description:'使用模擬設備，不會建立商品庫存或採購訂單。',fields:[{key:'code',label:'設備代號',required:true,maxLength:32},{key:'name',label:'設備名稱',required:true,maxLength:80},{key:'unit_id',label:'所屬組織',type:'select',required:true,options:unitOptions}]});
 const addReservation=()=>start({title:'預約設備',action:'office.reservation.create',description:'同一設備的預約時段不能重疊。時段以臺北時區記錄，最長 31 日。',fields:[{key:'equipment_id',label:'設備',type:'select',required:true,options:data.equipment.filter(row=>row.state==='available'&&activeUnits.some(organization=>organization.id===row.unit_id)).map(row=>({value:row.id,label:`${row.name} · ${unitName(row.unit_id)}`}))},{key:'staff_id',label:'假員工',type:'select',required:true,options:staffOptions},...timeFields,{key:'purpose',label:'借用用途（選填）',type:'textarea',maxLength:500}]});
 const noticeFields:Field[]=[{key:'title',label:'公告標題',required:true,maxLength:100},{key:'body',label:'公告內容（限模擬內容）',type:'textarea',maxLength:2000},{key:'unit_id',label:'公告對象（選填）',type:'select',nullable:true,options:unitOptions},{key:'pinned',label:'置頂公告',type:'checkbox',value:false},{key:'due_at',label:'截止時間（臺北，選填）',type:'datetime-local',nullable:true}];
 const addNotice=()=>start({title:'新增公告',action:'office.notice.create',description:'供這個訪客工作區查看。只放模擬公告，不會發送訊息給任何人。',fields:noticeFields});
 const creates:Record<OfficeTab,{id:string;label:string;run:()=>void;reason:string}>={units:{id:'unit',label:'新增組織',run:addUnit,reason:''},staff:{id:'staff',label:'新增假員工',run:addStaff,reason:organizationReason},shifts:{id:'shift',label:'新增班次',run:()=>addTime(false),reason:peopleReason},attendance:{id:'attendance',label:'新增手動出勤',run:()=>addTime(true),reason:peopleReason},requests:{id:'request',label:'新增模擬申請',run:addRequest,reason:organizationReason},equipment:{id:'equipment',label:'新增設備',run:addEquipment,reason:organizationReason},reservations:{id:'reservation',label:'預約設備',run:addReservation,reason:peopleReason||equipmentReason},notices:{id:'notice',label:'新增公告',run:addNotice,reason:''}};
 const pendingRequests=data.requests.filter(row=>row.status==='submitted'||row.status==='returned');
 const deadlines=data.notices.filter(row=>!row.archived&&row.due_at).sort((a,b)=>Date.parse(a.due_at!)-Date.parse(b.due_at!));
 const nextDeadline=deadlines.find(row=>Date.parse(row.due_at!)>=now);
 const available=data.equipment.filter(row=>activeUnits.some(organization=>organization.id===row.unit_id)&&row.state==='available'&&!data.reservations.some(booking=>booking.equipment_id===row.id&&booking.status==='reserved'&&Date.parse(booking.start_at)<=now&&Date.parse(booking.end_at)>now));
 const differences=attendanceDifferences(data,week,unit),differenceCount=differences.filter(row=>row.difference!==0).length;
 const visibleUnits=data.units.filter(row=>matches({...row,unit_id:row.id},`${row.name} ${unitName(row.parent_id)}`)&&(!unitState||(row.active?'active':'inactive')===unitState));
 const visibleStaff=data.staff.filter(row=>matches(row,`${row.code} ${row.alias} ${row.role_label}`)&&(!staffStatus||row.status===staffStatus));
 const visibleShifts=data.shifts.filter(row=>taipeiDate(row.start_at)>=week&&taipeiDate(row.start_at)<weekEnd&&matches(row,`${staffName(row.staff_id)} ${row.note}`)&&(!shiftStatus||row.status===shiftStatus)).sort((a,b)=>Date.parse(a.start_at)-Date.parse(b.start_at));
 const visibleAttendance=data.attendance.filter(row=>taipeiDate(row.start_at)>=week&&taipeiDate(row.start_at)<weekEnd&&matches(row,`${staffName(row.staff_id)} ${row.note}`)&&(attendanceState==='all'||(attendanceState==='voided'?!!row.voided:!row.voided))).sort((a,b)=>Date.parse(b.start_at)-Date.parse(a.start_at));
 const requestMatch=(row:OfficeRequest)=>matches(row,`${row.title} ${row.description} ${staffName(row.staff_id)} ${row.processing_note} ${(row.transitions||[]).map(event=>event.note).join(' ')}`)&&(!requestType||row.type===requestType)&&(!requestStatus||row.status===requestStatus);
 const visibleRequests=data.requests.filter(requestMatch).sort((a,b)=>Date.parse(b.updated_at)-Date.parse(a.updated_at));
 const visibleEquipment=data.equipment.filter(row=>matches(row,`${row.code} ${row.name}`)&&(!equipmentState||(equipmentState==='available_now'?available.some(item=>item.id===row.id):row.state===equipmentState)));
 const visibleReservations=data.reservations.filter(row=>(!unit||data.equipment.find(item=>item.id===row.equipment_id)?.unit_id===unit)&&`${equipmentName(row.equipment_id)} ${staffName(row.staff_id)} ${row.purpose}`.toLocaleLowerCase().includes(query.trim().toLocaleLowerCase())&&(!reservationStatus||row.status===reservationStatus)).sort((a,b)=>Date.parse(b.start_at)-Date.parse(a.start_at));
 const visibleNotices=data.notices.filter(row=>(!unit||row.unit_id===null||row.unit_id===unit)&&`${row.title} ${row.body}`.toLocaleLowerCase().includes(query.trim().toLocaleLowerCase())&&(noticeState==='all'||(noticeState==='archived'?!!row.archived:!row.archived))).sort((a,b)=>Number(!b.archived&&b.pinned)-Number(!a.archived&&a.pinned)||Date.parse(b.updated_at)-Date.parse(a.updated_at));
 const editTime=(row:OfficeData['shifts'][number],attendance:boolean)=>start({title:attendance?'更正手動出勤':'編輯班次時段',action:attendance?'office.attendance.update':'office.shift.update',description:'所屬組織與假員工不變。填寫更正原因；原值、新值與原因會保留在紀錄中。',base:idField(row),fields:[...timeFields.map(field=>({...field,value:localInput(row[field.key as 'start_at'|'end_at'])})),{...breakField,value:row.break_minutes},{...noteField,value:row.note},reasonField]});
 const editReservation=(row:OfficeData['reservations'][number])=>start({title:'更改設備預約',action:'office.reservation.update',description:'設備與假員工保留原紀錄。新時段仍須避開其他有效預約，原值與更改原因會保留。',base:idField(row),fields:[...timeFields.map(field=>({...field,value:localInput(row[field.key as 'start_at'|'end_at'])})),{key:'purpose',label:'借用用途（選填）',type:'textarea',value:row.purpose,maxLength:1000},reasonField]});
 const guideSteps=[{id:'unit',label:'建立組織',detail:'至少一個使用中的門市或部門。',done:activeUnits.length>0,reason:'',run:()=>{chooseTab('units');addUnit()}},{id:'staff',label:'加入假員工',detail:'至少一位使用中假員工，對應使用中組織。',done:activeStaff.length>0,reason:organizationReason,run:()=>{chooseTab('staff');addStaff()}},{id:'shift',label:'排第一個班次',detail:'至少一筆未取消班次，開始這週的流程練習。',done:data.shifts.some(row=>row.status!=='cancelled'),reason:peopleReason,run:()=>{chooseTab('shifts');addTime(false)}}];
 const guideCompleted=guideSteps.filter(step=>step.done).length,demoEmpty=officeTabs.every(({id})=>data[id].length===0)&&data.changes.length===0;
 const startDemo=()=>start({title:'建立合成行政示範',action:'office.demo.create',description:'只在空白行政桌建立 1 個組織、2 位假員工、5 個班次、2 筆手動出勤、1 份請購草稿、1 件設備、1 筆借用及 2 則公告。全部是合成資料；既有客戶、商品、錢包與訂單保留。',fields:[{key:'preset',label:'合成示範類型',type:'select',required:true,value:'store',options:[{value:'store',label:'合成店家示範'},{value:'office',label:'合成辦公室示範'},{value:'factory',label:'合成工廠示範'}]},{key:'week_start',label:'示範週星期一（臺北）',type:'date',required:true,value:week}]});
 const viewRows={units:visibleUnits,staff:visibleStaff,shifts:visibleShifts,attendance:visibleAttendance,requests:visibleRequests,equipment:visibleEquipment,reservations:visibleReservations,notices:visibleNotices};
 const label=officeTabs.find(item=>item.id===tab)!.label;
 const statusScope=({units:unitState?officeStatus[unitState]:'全部狀態',staff:staffStatus?officeStatus[staffStatus]:'全部狀態',shifts:shiftStatus?officeStatus[shiftStatus]:'全部狀態',attendance:attendanceState==='all'?'有效與作廢':attendanceState==='voided'?'已作廢':'有效紀錄',requests:[requestType?requestNames[requestType as keyof typeof requestNames]:'全部類型',requestStatus?officeStatus[requestStatus]:'全部狀態'].join('／'),equipment:equipmentState==='available_now'?'目前可用':equipmentState?officeStatus[equipmentState]:'全部狀態',reservations:reservationStatus==='returned'?'已歸還':reservationStatus?officeStatus[reservationStatus]:'全部狀態',notices:noticeState==='all'?'發布中與封存':noticeState==='archived'?'已封存':'發布中'} as Record<OfficeTab,string>)[tab];
 const period=tab==='shifts'||tab==='attendance'?`${week} 至 ${addDays(week,6)}（依開始日歸週）`:'全部日期';
 const report=officeReport(tab,viewRows[tab],data);
 const reportSummary=tab==='shifts'?`目前篩選的有效班次 ${visibleShifts.filter(row=>row.status!=='cancelled').length} 筆，共 ${visibleShifts.filter(row=>row.status!=='cancelled').reduce((total,row)=>total+netMinutes(row),0)} 分鐘；另保留 ${visibleShifts.filter(row=>row.status==='cancelled').length} 筆取消紀錄。`:
 tab==='attendance'?`目前篩選的有效出勤 ${visibleAttendance.filter(row=>!row.voided).length} 筆，共 ${visibleAttendance.filter(row=>!row.voided).reduce((total,row)=>total+netMinutes(row),0)} 分鐘；另保留 ${visibleAttendance.filter(row=>row.voided).length} 筆作廢紀錄，作廢不計入。`:
 tab==='requests'?`目前篩選的申請登錄合計 ${formatSIM(visibleRequests.reduce((total,row)=>total+row.amount_minor,0))}。此為模擬登錄金額，不代表核准或支付。`:
 tab==='notices'?`目前篩選 ${visibleNotices.filter(row=>!row.archived).length} 則發布中公告、${visibleNotices.filter(row=>row.archived).length} 則封存公告。封存公告不列入最近截止與置頂。`:`目前篩選共 ${viewRows[tab].length} 筆模擬紀錄。`;
 const reportScope=[['模式','SIM 流程練習'],['工作區',workspace.company_name],['工作區版本',String(workspace.version)],['資料類型',label],['組織範圍',unit?unitName(unit):'全部組織'],['搜尋條件',query||'未設定'],['狀態篩選',statusScope],['日期範圍',period],['時區','Asia/Taipei（UTC+08:00）'],['產出時間',formatDateTime(new Date().toISOString())],['篩選統計',reportSummary],['資料來源','目前訪客工作區的模擬紀錄；僅匯出目前篩選結果']];
 const exportCSV=()=>{const content=officeCSV([[...reportScope.map(item=>item[0]),...report.headers],...report.rows.map(row=>[...reportScope.map(item=>item[1]),...row])]);const url=URL.createObjectURL(new Blob([content],{type:'text/csv;charset=utf-8'}));const anchor=document.createElement('a');anchor.href=url;anchor.download=officeFilename(tab);anchor.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setMessage(`已匯出「${label}」目前篩選的 ${report.rows.length} 筆 SIM 紀錄。`)};
 const empty=(text:string)=><p className="office-empty">{query||unit||data[tab].length?'目前篩選、日期與狀態沒有符合的紀錄。可清除篩選、查看其他週，或切換紀錄狀態。':text}</p>;
 const statusBadge=(value:string)=><span className={`office-status office-state-${value}`}>{officeStatus[value]||value}</span>;
 const stamp=(row:OfficeRow)=><small className="office-stamp">更新 {formatDateTime(row.updated_at)}</small>;
 const actionButton=(id:string,label:string,run:()=>void,reason='')=><span className="office-action-item"><button type="button" data-testid={`office-${id}`} disabled={locked||!!reason} title={reason||undefined} onClick={run}>{label}</button>{reason&&<small>{reason}</small>}</span>;
 const timeRow=(row:OfficeData['shifts'][number],attendance=false)=><article className={`office-time-row ${row.voided?'office-row-voided':''}`} key={row.id} data-testid={attendance?'office-attendance':'office-shift'} data-record-id={row.id} data-highlighted={row.id===highlighted}>
  <div className="office-time-range"><strong>{formatTime(row.start_at)} — {formatTime(row.end_at)}</strong>{taipeiDate(row.start_at)!==taipeiDate(row.end_at)&&<small>至 {taipeiDate(row.end_at).slice(5)}（跨夜）</small>}<span>{netMinutes(row)} 分鐘 · 休息 {row.break_minutes} 分鐘</span>{row.voided&&<small>已作廢，統計不計入</small>}</div>
  <div><strong>{staffName(row.staff_id)}</strong><small>{unitName(row.unit_id)}</small>{row.note&&<p>{row.note}</p>}{statusBadge(attendance?(row.voided?'voided':'recorded'):row.status!)}{stamp(row)}</div>
  <RecordHistory changes={data.changes.filter(change=>change.record_id===row.id)}/>
  {!attendance&&row.status==='scheduled'&&<div className="office-actions">{actionButton('edit-shift','編輯班次時段',()=>editTime(row,false))}{actionButton('complete-shift','結束班次',()=>confirm('office.shift.complete','結束班次',row,'只改變已到結束時間的班次狀態，不會新增出勤紀錄。'),Date.parse(row.end_at)>now?'尚未到結束時間；可編輯時段或取消班次。':'')}{actionButton('cancel-shift','取消班次',()=>confirm('office.shift.cancel','取消班次',row,'保留原班次與取消紀錄。'))}</div>}
  {attendance&&!row.voided&&<div className="office-actions">{actionButton('edit-attendance','更正手動出勤',()=>editTime(row,true))}{actionButton('void-attendance','作廢手動出勤',()=>confirm('office.attendance.void','作廢手動出勤',row,'保留原值與作廢原因，停止計入統計。作廢後可新增正確紀錄，原紀錄不再阻擋相同時段。',[reasonField]))}</div>}
 </article>;

 return <section className="office-desk" data-testid="office-desk">
  <header className="office-heading"><div><span className="eyebrow">SIM · 店家行政桌</span><h1>把人、時段與待辦，放在同一張桌上。</h1><p>假員工與模擬流程練習。出勤由手動輸入；申請整理完成仍未覆核。</p></div><span className="office-workspace">{workspace.company_name}<small>這個訪客的獨立工作區</small></span></header>
  {message&&<p className="office-result" role="status" data-testid="office-message">{message}</p>}
  {!enabled?<div className="office-enable-panel"><div className="office-enable-drawing" aria-hidden="true"><svg viewBox="0 0 160 110" fill="none"><rect x="17" y="22" width="126" height="80" rx="5"/><path d="M17 43h126M45 13v21m70-21v21M43 60h21m-21 18h33m19-18h21m-21 18h21"/><path d="m109 4 3 8 8 3-8 3-3 8-3-8-8-3 8-3z"/></svg></div><div><h2>先啟用，再建立第一間模擬門市。</h2><p>啟用後可使用組織、假員工、班表、出勤、申請、設備借用與公告。既有客戶、商品及訂單會保留。</p><button type="button" className="primary" data-testid="office-enable" disabled={locked} onClick={()=>start({title:'啟用行政模擬',action:'office.enable',description:'加入行政模組，建立空白行政桌。既有模擬資料會保留。',fields:[]})}>啟用行政模擬</button></div></div>:<>
   <details className="office-onboarding office-screen-only" data-testid="office-onboarding" open={guideCompleted<3}>
    <summary><strong>行政入門路線</strong><span>已完成 {guideCompleted}／3 步{guideCompleted<3?` · 尚需 ${3-guideCompleted} 步`:' · 可繼續出勤、申請與設備借用'}</span></summary>
    <ol>{guideSteps.map((step,index)=><li key={step.id} className={step.done?'is-done':''}><span className="office-guide-number">{step.done?'✓':index+1}</span><div><strong>{step.label}</strong><p>{step.detail}</p><button type="button" data-testid={`office-guide-${step.id}`} disabled={locked||!!step.reason} onClick={step.run}>{step.done?(step.id==='shift'?'新增另一個班次':'再'+step.label):step.label}</button>{step.reason&&<small>{step.reason}</small>}</div></li>)}</ol>
    <div className="office-demo-entry"><div><strong>想先用一套合成資料練習？</strong><p>{demoEmpty?'選擇店家、辦公室或工廠示範，一次備好班表、出勤差異與其他模擬紀錄。':'示範只能加入空白行政桌。已有行政資料與變更紀錄，請沿用目前資料繼續。'}</p></div><button type="button" data-testid="office-seed-demo" disabled={locked||!demoEmpty} onClick={startDemo}>建立合成示範</button></div>
   </details>
   <div className="office-board" aria-label="行政待辦概覽"><button type="button" onClick={()=>{chooseTab('requests');setUnit('');setRequestType('');setRequestStatus('submitted')}}><span>申請待整理</span><strong>{data.requests.filter(row=>row.status==='submitted').length}<small>件</small></strong><em>{pendingRequests.filter(row=>row.status==='returned').length} 件待補件</em></button><button type="button" onClick={()=>{chooseTab('equipment');setUnit('');setEquipmentState('available_now')}}><span>目前可用設備</span><strong>{available.length}<small>件</small></strong><em>依設備狀態與目前預約計算</em></button><button type="button" onClick={()=>{chooseTab('attendance');setAttendanceState('active')}}><span>{week===monday()?'本週出勤差異':'選定週出勤差異'}</span><strong>{differenceCount}<small>人</small></strong><em>排班與手動紀錄的分鐘差</em></button><button type="button" className="office-next-notice" onClick={()=>{chooseTab('notices');setUnit('');setNoticeState('active');if(nextDeadline)setQuery(nextDeadline.title)}}><span>最近公告截止</span><strong>{nextDeadline?taipeiDate(nextDeadline.due_at!).slice(5):'—'}</strong><em>{nextDeadline?.title||'還沒有即將截止的公告'}</em></button></div>
   <div className="office-tabs" role="tablist" aria-label="行政工作"><div>{officeTabs.map(({id,label},index)=><button type="button" id={`office-tab-${id}`} key={id} data-testid={`office-tab-${id}`} role="tab" aria-selected={tab===id} aria-controls={`office-panel-${id}`} tabIndex={tab===id?0:-1} onKeyDown={event=>tabKeys(event,index)} onClick={()=>chooseTab(id)}>{label}<span>{data[id].length}</span></button>)}</div></div>
   <div className="office-tools"><label><span>搜尋{officeTabs.find(row=>row.id===tab)?.label}</span><input type="search" data-testid="office-search" value={query} maxLength={120} placeholder="輸入暱稱、名稱或內容" onChange={event=>setQuery(event.target.value)}/></label><label><span>組織範圍</span><select data-testid="office-unit-filter" value={unit} onChange={event=>setUnit(event.target.value)}><option value="">全部組織</option>{data.units.map(row=><option key={row.id} value={row.id}>{row.name}{!row.active?'（停用）':''}</option>)}</select></label><div className="office-create"><button className="primary" type="button" data-testid={`office-add-${creates[tab].id}`} disabled={locked||!!creates[tab].reason} onClick={creates[tab].run}>{creates[tab].label}</button>{creates[tab].reason&&<small>{creates[tab].reason}</small>}</div></div>
   <div className="office-view-actions office-screen-only"><span data-testid="office-filter-count">目前篩選 {viewRows[tab].length} 筆 · {statusScope}</span><div><button type="button" data-testid="office-clear-filters" onClick={()=>{setQuery('');setUnit('');setUnitState('');setStaffStatus('');setShiftStatus('');setAttendanceState('active');setRequestType('');setRequestStatus('');setEquipmentState('');setReservationStatus('');setNoticeState('active')}}>清除篩選</button><button type="button" data-testid="office-export-csv" disabled={!report.rows.length} onClick={exportCSV}>匯出目前範圍 CSV</button><button type="button" data-testid="office-print" disabled={!report.rows.length} onClick={()=>window.print()}>列印目前範圍</button></div></div>
   <p className="office-report-summary office-screen-only" data-testid="office-report-summary">{reportSummary}</p>
   <p className="office-report-source office-screen-only">CSV 與列印只包含目前篩選的紀錄。來源：這個訪客工作區的版本 {workspace.version} · {period} · Asia/Taipei。{tab==='attendance'&&'作廢紀錄的有效分鐘為 0。'}</p>
   {tab==='units'&&<StatusFilter label="組織狀態" id="unit-state-filter" value={unitState} onChange={setUnitState} options={[{value:'',label:'全部狀態'},{value:'active',label:'使用中'},{value:'inactive',label:'停用'}]}/>}
   {tab==='staff'&&<StatusFilter label="假員工狀態" id="staff-status-filter" value={staffStatus} onChange={setStaffStatus} options={[{value:'',label:'全部狀態'},{value:'active',label:'使用中'},{value:'inactive',label:'停用'}]}/>}
   {tab==='shifts'&&<StatusFilter label="班次狀態" id="shift-status-filter" value={shiftStatus} onChange={setShiftStatus} options={[{value:'',label:'全部狀態'},...optionNames({scheduled:'已排班',completed:'已結束',cancelled:'已取消'})]}/>}
   {tab==='attendance'&&<StatusFilter label="出勤紀錄" id="attendance-status-filter" value={attendanceState} onChange={setAttendanceState} options={[{value:'active',label:'有效紀錄'},{value:'voided',label:'已作廢'},{value:'all',label:'有效與作廢'}]}/>}
   {tab==='equipment'&&<StatusFilter label="設備狀態" id="equipment-state-filter" value={equipmentState} onChange={setEquipmentState} options={[{value:'',label:'全部狀態'},...optionNames({available_now:'目前可用',available:'可借用',maintenance:'維修中',retired:'已停用'})]}/>}
   {tab==='reservations'&&<StatusFilter label="借用狀態" id="reservation-status-filter" value={reservationStatus} onChange={setReservationStatus} options={[{value:'',label:'全部狀態'},...optionNames({reserved:'已預約',returned:'已歸還',cancelled:'已取消'})]}/>}
   {tab==='notices'&&<StatusFilter label="公告範圍" id="notice-state-filter" value={noticeState} onChange={setNoticeState} options={[{value:'active',label:'發布中'},{value:'archived',label:'已封存'},{value:'all',label:'發布中與封存'}]}/>}
   {(tab==='shifts'||tab==='attendance')&&<div className="office-week-tools"><div><button type="button" aria-label="前一週" onClick={()=>setWeek(addDays(week,-7))}>←</button><strong>{week} 至 {addDays(week,6)}<small>臺北週 · 星期一開始</small></strong><button type="button" aria-label="下一週" onClick={()=>setWeek(addDays(week,7))}>→</button><button type="button" onClick={()=>setWeek(monday())}>本週</button></div>{tab==='shifts'&&<button type="button" data-testid="office-copy-week" disabled={locked||!data.shifts.some(row=>row.status!=='cancelled'&&taipeiDate(row.start_at)>=week&&taipeiDate(row.start_at)<weekEnd)} onClick={()=>start({title:'複製一週班表',action:'office.shift.copy_week',description:'複製來源週的未取消班次。來源與目的日期必須是臺北週的星期一，重疊班次會拒絕整次操作。',fields:[{key:'from_date',label:'來源週星期一',type:'date',required:true,value:week},{key:'to_date',label:'目的週星期一',type:'date',required:true,value:addDays(week,7)}]})}>複製本週班表</button>}</div>}
   {tab==='shifts'&&<p className="office-week-note">依各段開始日歸週；跨夜分鐘完整計入，差異不作薪資依據。</p>}
   <section role="tabpanel" id={`office-panel-${tab}`} aria-labelledby={`office-tab-${tab}`} data-testid={`office-panel-${tab}`}>
    {tab==='units'&&<div className="office-cards">{visibleUnits.map(row=><article className="office-card" key={row.id} data-testid="office-unit" data-record-id={row.id} data-highlighted={row.id===highlighted}><span className="office-card-type">{row.kind==='branch'?'門市':'部門'}</span><h2>{row.name}</h2>{statusBadge(row.active?'active':'inactive')}<p>{row.parent_id?`所屬門市：${unitName(row.parent_id)}`:'獨立組織'} · {data.staff.filter(person=>person.unit_id===row.id).length} 位假員工</p>{stamp(row)}<div className="office-actions">{actionButton('edit-unit','編輯組織',()=>start({title:'編輯組織',action:'office.unit.update',description:'組織類型與所屬門市保留原紀錄。',base:idField(row),fields:[{key:'name',label:'組織名稱',required:true,value:row.name,maxLength:80},{key:'active',label:'使用中',type:'checkbox',value:row.active}]}))}</div></article>)}{!visibleUnits.length&&empty('從一間模擬門市開始，再加入假員工。')}</div>}
    {tab==='staff'&&<div className="office-cards">{visibleStaff.map(row=><article className="office-card" key={row.id} data-testid="office-staff" data-record-id={row.id} data-highlighted={row.id===highlighted}><span className="office-card-type">{row.code} · {unitName(row.unit_id)}</span><h2>{row.alias}</h2>{statusBadge(row.status)}<p>{row.role_label||'未填職務稱呼'}</p>{stamp(row)}<div className="office-actions">{actionButton('edit-staff','編輯假員工',()=>start({title:'編輯假員工',action:'office.staff.update',description:'代號與所屬組織保留原紀錄。僅使用模擬暱稱。',base:idField(row),fields:[{key:'alias',label:'假員工暱稱',required:true,value:row.alias,maxLength:80},{key:'role_label',label:'職務稱呼（選填）',value:row.role_label,maxLength:80},{key:'status',label:'假員工狀態',type:'select',required:true,value:row.status,options:[{value:'active',label:'使用中'},{value:'inactive',label:'停用'}]}]}))}</div></article>)}{!visibleStaff.length&&empty('先建立組織，再新增假員工暱稱與代號。')}</div>}
    {tab==='shifts'&&<div className="office-week-grid">{days.map((day,index)=>{const rows=visibleShifts.filter(row=>taipeiDate(row.start_at)===day);return <section className={`office-day ${day===today?'office-today':''}`} key={day} data-testid="office-week-day" data-date={day}><header><h2>星期{'一二三四五六日'[index]}<span>{day.slice(5)}</span></h2><small>{rows.length} 個班次</small></header>{rows.map(row=>timeRow(row))}{!rows.length&&<p className="office-day-empty">沒有班次</p>}</section>})}</div>}
    {tab==='attendance'&&<><div className="office-difference"><header><h2>排班與手動出勤核對</h2><p>依各段開始日歸週；跨夜分鐘完整計入，差異不作薪資依據。各筆扣除手動休息分鐘，作廢出勤不計入。這張差異表依選定週與組織核對全部有效紀錄，不隨下方搜尋或紀錄狀態重算。</p></header><div className="office-difference-head"><span>假員工</span><span>排班分鐘</span><span>手動分鐘</span><span>差異</span></div>{differences.map(row=><div className={row.difference?'office-difference-row has-difference':'office-difference-row'} key={row.person.id} data-testid="office-attendance-difference"><strong>{row.person.alias}</strong><span>{row.scheduled}</span><span>{row.recorded}</span><b>{row.difference>0?'+':''}{row.difference}</b></div>)}{!differences.length&&<p className="office-empty">這一週尚無排班或手動出勤紀錄。</p>}<small>差異只供流程練習，不是薪資或合法工時判定。</small></div><div className="office-time-list">{visibleAttendance.map(row=><div key={row.id}><span className="office-list-date">{taipeiDate(row.start_at)}</span>{timeRow(row,true)}</div>)}</div>{!visibleAttendance.length&&empty('這一週與目前狀態尚無出勤紀錄。可新增手動出勤，或切換有效與作廢紀錄。')}</>}
    {tab==='requests'&&<><div className="office-request-filters"><label>申請類型<select data-testid="office-request-type-filter" value={requestType} onChange={event=>setRequestType(event.target.value)}><option value="">全部類型</option>{optionNames(requestNames).map(row=><option key={row.value} value={row.value}>{row.label}</option>)}</select></label><label>申請狀態<select data-testid="office-request-status-filter" value={requestStatus} onChange={event=>setRequestStatus(event.target.value)}><option value="">全部狀態</option>{['draft','submitted','returned','withdrawn','prepared_unreviewed'].map(value=><option key={value} value={value}>{officeStatus[value]}</option>)}</select></label></div><div className="office-cards">{visibleRequests.map(row=><article className="office-card office-request-card" key={row.id} data-testid="office-request" data-record-id={row.id} data-highlighted={row.id===highlighted}><span className="office-card-type">{requestNames[row.type]} · {unitName(row.unit_id)} · {staffName(row.staff_id)}</span><h2>{row.title}</h2>{statusBadge(row.status)}{row.description&&<p>{row.description}</p>}{row.type==='leave'?<p>{formatDateTime(row.start_at)} 至 {formatDateTime(row.end_at)}</p>:row.amount_minor>0&&<strong className="office-amount">{formatSIM(row.amount_minor)}</strong>}{row.processing_note&&<p className="office-processing-note">最新退回原因：{row.processing_note}</p>}{row.status==='prepared_unreviewed'&&<p className="office-unreviewed">已整理，尚未覆核；不代表准假、採購或付款。</p>}{stamp(row)}<RequestHistory request={row}/><div className="office-actions">{(row.status==='draft'||row.status==='returned')&&<>{actionButton('edit-request','編輯申請',()=>start({title:'編輯模擬申請',action:'office.request.update',description:'申請類型、組織與假員工保留原紀錄。',base:idField(row),fields:[{key:'title',label:'申請標題',required:true,value:row.title,maxLength:100},{key:'description',label:'申請內容（限模擬內容）',type:'textarea',value:row.description,maxLength:1000},...(row.type==='leave'?timeFields.map(field=>({...field,value:localInput(row[field.key as 'start_at'|'end_at'])})):[{key:'amount_sim',label:'測試幣金額（SIM）',type:'number' as const,required:true,min:row.type==='general'?0:0.01,max:1e7,step:'0.01',value:(row.amount_minor/100).toFixed(2)}])]}))}{actionButton('submit-request','送出申請',()=>confirm('office.request.submit','送出申請',row,'送出後進入待整理清單，沒有任何正式核准。'))}</>}{row.status==='submitted'&&<>{actionButton('return-request','退回補件',()=>confirm('office.request.return','退回補件',row,'填寫要補齊的模擬內容，保留退回紀錄。',[{key:'processing_note',label:'補件說明',type:'textarea',required:true,maxLength:1000}]))}{actionButton('prepare-request','整理完成（未覆核）',()=>confirm('office.request.prepare','整理完成（未覆核）',row,'只標記整理完成，仍未經獨立覆核；不會扣測試幣、准假或建立採購。'))}</>}{['draft','submitted','returned'].includes(row.status)&&actionButton('withdraw-request','撤回申請',()=>confirm('office.request.withdraw','撤回申請',row,'保留原申請與撤回狀態。'))}</div></article>)}{!visibleRequests.length&&empty('還沒有這個範圍的申請。建立一份草稿，再練習送出、補件與整理。')}</div></>}
    {tab==='equipment'&&<div className="office-cards">{visibleEquipment.map(row=>{const reservations=data.reservations.filter(booking=>booking.equipment_id===row.id&&booking.status==='reserved'),current=reservations.find(booking=>Date.parse(booking.start_at)<=now&&Date.parse(booking.end_at)>now);return <article className="office-card" key={row.id} data-testid="office-equipment" data-record-id={row.id} data-highlighted={row.id===highlighted}><span className="office-card-type">{row.code} · {unitName(row.unit_id)}</span><h2>{row.name}</h2>{statusBadge(row.state)}<p>{current?`目前預約：${staffName(current.staff_id)}，至 ${formatDateTime(current.end_at)}`:`目前沒有進行中的預約 · ${reservations.filter(booking=>Date.parse(booking.start_at)>now).length} 筆未來預約`}</p>{stamp(row)}<div className="office-actions">{actionButton('edit-equipment','編輯設備',()=>start({title:'編輯設備',action:'office.equipment.update',description:'代號與組織保留原紀錄；預約與歸還記錄也會保留。',base:idField(row),fields:[{key:'name',label:'設備名稱',required:true,value:row.name,maxLength:80},{key:'state',label:'設備狀態',type:'select',required:true,value:row.state,options:[{value:'available',label:'可借用'},{value:'maintenance',label:'維修中'},{value:'retired',label:'已停用'}]}]}))}</div></article>})}{!visibleEquipment.length&&empty('新增模擬設備，才能練習預約與歸還。')}</div>}
    {tab==='reservations'&&<div className="office-cards">{visibleReservations.map(row=><article className="office-card" key={row.id} data-testid="office-reservation" data-record-id={row.id} data-highlighted={row.id===highlighted}><span className="office-card-type">{staffName(row.staff_id)}</span><h2>{equipmentName(row.equipment_id)}</h2>{statusBadge(row.status==='returned'?'reservation_returned':row.status)}<p>{formatDateTime(row.start_at)} 至 {formatDateTime(row.end_at)}</p>{row.purpose&&<p>{row.purpose}</p>}{stamp(row)}<RecordHistory changes={data.changes.filter(change=>change.record_id===row.id)}/>{row.status==='reserved'&&<div className="office-actions">{actionButton('edit-reservation','更改預約',()=>editReservation(row))}{actionButton('return-reservation','記錄歸還',()=>confirm('office.reservation.return','記錄歸還',row,'保留預約時段與用途，記錄設備已歸還。'))}{actionButton('cancel-reservation','取消預約',()=>confirm('office.reservation.cancel','取消預約',row,'保留原預約與取消紀錄。'))}</div>}</article>)}{!visibleReservations.length&&empty('先建立設備與假員工，再預約一段借用時間。')}</div>}
    {tab==='notices'&&<div className="office-notice-grid">{visibleNotices.map(row=><article className={`office-notice ${!row.archived&&row.pinned?'is-pinned':''}`} key={row.id} data-testid="office-notice" data-record-id={row.id} data-highlighted={row.id===highlighted}><div className="office-notice-top"><span>{!row.archived&&row.pinned?'置頂 · ':''}{unitName(row.unit_id)}{row.archived?' · 已封存':''}</span>{row.due_at&&<span className={Date.parse(row.due_at)<now?'office-deadline-past':'office-deadline'}>{Date.parse(row.due_at)<now?'已截止':'截止'} {formatDateTime(row.due_at)}</span>}</div><h2>{row.title}</h2><p>{row.body||'未填公告內容'}</p>{stamp(row)}<RecordHistory changes={data.changes.filter(change=>change.record_id===row.id)}/><div className="office-actions">{row.archived? actionButton('restore-notice','還原公告',()=>confirm('office.notice.restore','還原公告',row,'讓公告回到發布中清單，保留原內容、截止時間與封存紀錄。')):<>{actionButton('archive-notice','封存公告',()=>confirm('office.notice.archive','封存公告',row,'從發布中與置頂清單移除，保留原公告及封存紀錄。'))}{actionButton('edit-notice','編輯公告',()=>start({title:'編輯公告',action:'office.notice.update',description:'公告修改後保留建立時間，更新截止時間與內容。',base:idField(row),fields:noticeFields.map(field=>({...field,value:field.key==='due_at'?localInput(row.due_at):(row as any)[field.key]??'',options:field.key==='unit_id'?[...unitOptions,...(row.unit_id&&!activeUnits.some(organization=>organization.id===row.unit_id)?[{value:row.unit_id,label:unitName(row.unit_id)}]:[])]:field.options}))}))}</>}</div></article>)}{!visibleNotices.length&&empty('貼一份模擬公告，設定對象、置頂與截止時間。')}</div>}
   </section>
  </>}
  {enabled&&<section className="office-print-sheet" data-testid="office-print-sheet"><h1>SIM 行政紀錄：{label}</h1><dl>{reportScope.map(([key,value])=><div key={key}><dt>{key}</dt><dd>{value}</dd></div>)}</dl><p>產出時間：{formatDateTime(new Date().toISOString())}（臺北）。排班與出勤依各段開始日歸週，跨夜分鐘完整計入；取消班次、作廢出勤不計入有效分鐘。僅供模擬流程練習，申請未覆核，不作薪資或法定工時依據。</p><table><thead><tr>{report.headers.map(header=><th key={header}>{header}</th>)}</tr></thead><tbody>{report.rows.map((row,index)=><tr key={index}>{row.map((value,column)=><td key={column}>{value}</td>)}</tr>)}</tbody></table><p>目前篩選共 {report.rows.length} 筆。金額單位為 SIM 測試幣；沒有真實付款或正式核准。</p></section>}
  {pending&&<p className="office-pending" role="status">原操作結果尚未確認。請先使用頁面上方的「確認原操作結果」，再新增或修改資料。</p>}
  <p className="office-scope-note">SIM 行政紀錄只屬於這個訪客工作區。請用假員工暱稱及模擬內容。</p>
  {form&&<OfficeDialog config={form} data={data} locked={locked} closeLocked={busy||saving} pending={pending} onClose={()=>{if(!busy&&!saving)setForm(null)}} onSubmit={execute}/>}
 </section>;
}

function StatusFilter({label,id,value,onChange,options}:{label:string;id:string;value:string;onChange:(value:string)=>void;options:Option[]}){
 return <div className="office-status-filters office-screen-only"><label>{label}<select data-testid={`office-${id}`} value={value} onChange={event=>onChange(event.target.value)}>{options.map(option=><option value={option.value} key={option.value}>{option.label}</option>)}</select></label></div>;
}
const changeNames:Record<OfficeChange['kind'],string>={'shift.update':'班次時段更正','attendance.update':'手動出勤更正','attendance.void':'手動出勤作廢','reservation.update':'設備預約更改','notice.archive':'公告封存','notice.restore':'公告還原'};
function historyFields(change:OfficeChange):{key:string;label:string;format:(value:any)=>string}[]{
 const text=(value:any)=>value==null||value===''?'未填寫':String(value),date=(value:any)=>formatDateTime(value||null);
 if(change.kind.startsWith('notice.'))return [{key:'archived',label:'公告狀態',format:value=>value?'已封存':'發布中'},{key:'pinned',label:'置頂設定',format:value=>value?'置頂':'一般'},{key:'due_at',label:'截止時間',format:date}];
 if(change.kind==='reservation.update')return [{key:'start_at',label:'開始時間',format:date},{key:'end_at',label:'結束時間',format:date},{key:'purpose',label:'借用用途',format:text}];
 return [{key:'start_at',label:'開始時間',format:date},{key:'end_at',label:'結束時間',format:date},{key:'break_minutes',label:'休息分鐘',format:text},{key:'note',label:'備註',format:text},...(change.kind.startsWith('attendance.')?[{key:'voided',label:'出勤紀錄',format:(value:any)=>value?'已作廢':'有效紀錄'}]:[])];
}
function RecordHistory({changes}:{changes:OfficeChange[]}){
 if(!changes.length)return null;
 return <details className="office-record-history" data-testid="office-record-history"><summary>更正與保留紀錄<span>{changes.length} 筆</span></summary><ol>{changes.map(change=><li key={change.id} data-testid="office-record-change"><header><strong>{changeNames[change.kind]}</strong><time dateTime={change.at}>{formatDateTime(change.at)}（臺北）</time></header><p>原因：{change.reason}</p><div className="office-history-comparison"><div className="office-history-header"><span>欄位</span><span>原值</span><span>更正後</span></div>{historyFields(change).map(field=><div key={field.key}><strong>{field.label}</strong><span>{field.format(change.before[field.key])}</span><span>{field.format(change.after[field.key])}</span></div>)}</div></li>)}</ol></details>;
}
function officeReport(tab:OfficeTab,records:OfficeRow[],data:OfficeData):{headers:string[];rows:(string|number)[][]}{
 const unit=(id:string|null)=>data.units.find(row=>row.id===id)?.name||(id?'原組織':'全體'),staff=(id:string|null)=>data.staff.find(row=>row.id===id)?.alias||'未指定',equipment=(id:string)=>data.equipment.find(row=>row.id===id)?.name||'原設備';
 const common=['建立時間（臺北）','更新時間（臺北）','更正與保留紀錄'];
 const history=(id:string)=>data.changes.filter(change=>change.record_id===id).map(change=>`${formatDateTime(change.at)} ${changeNames[change.kind]}：${change.reason}；${historyFields(change).map(field=>`${field.label} ${field.format(change.before[field.key])} → ${field.format(change.after[field.key])}`).join('；')}`).join('\n');
 const tails=(row:OfficeRow)=>[formatDateTime(row.created_at),formatDateTime(row.updated_at),history(row.id)];
 const rows=records as any[];
 const result:{headers:string[];rows:(string|number)[][]}=tab==='units'?{headers:['紀錄編號','組織名稱','類型','所屬門市','狀態'],rows:rows.map(row=>[row.id,row.name,row.kind==='branch'?'門市':'部門',row.parent_id?unit(row.parent_id):'獨立組織',row.active?'使用中':'停用',...tails(row)])}:
 tab==='staff'?{headers:['紀錄編號','假員工代號','假員工暱稱','組織','職務稱呼','狀態'],rows:rows.map(row=>[row.id,row.code,row.alias,unit(row.unit_id),row.role_label,officeStatus[row.status],...tails(row)])}:
 tab==='shifts'||tab==='attendance'?{headers:['紀錄編號','假員工','組織','開始時間（臺北）','結束時間（臺北）','休息分鐘','原段淨分鐘','有效分鐘','狀態','備註'],rows:rows.map(row=>[row.id,staff(row.staff_id),unit(row.unit_id),formatDateTime(row.start_at),formatDateTime(row.end_at),row.break_minutes,netMinutes(row),row.status==='cancelled'||row.voided?0:netMinutes(row),tab==='attendance'?(row.voided?'已作廢':'有效紀錄'):officeStatus[row.status],row.note,...tails(row)])}:
 tab==='requests'?{headers:['紀錄編號','申請類型','組織','假員工','標題','內容','SIM 測試幣金額','開始時間（臺北）','結束時間（臺北）','狀態','最新退回原因','申請狀態紀錄'],rows:rows.map(row=>[row.id,requestNames[row.type as keyof typeof requestNames],unit(row.unit_id),staff(row.staff_id),row.title,row.description,(row.amount_minor/100).toFixed(2),formatDateTime(row.start_at),formatDateTime(row.end_at),officeStatus[row.status],row.processing_note,(row.transitions||[]).map((event:OfficeRequest['transitions'][number])=>`${formatDateTime(event.at)} ${officeStatus[event.status]}${event.note?'：'+event.note:''}`).join('\n'),...tails(row)])}:
 tab==='equipment'?{headers:['紀錄編號','設備代號','設備名稱','組織','狀態'],rows:rows.map(row=>[row.id,row.code,row.name,unit(row.unit_id),officeStatus[row.state],...tails(row)])}:
 tab==='reservations'?{headers:['紀錄編號','設備','假員工','開始時間（臺北）','結束時間（臺北）','借用用途','狀態'],rows:rows.map(row=>[row.id,equipment(row.equipment_id),staff(row.staff_id),formatDateTime(row.start_at),formatDateTime(row.end_at),row.purpose,row.status==='returned'?'已歸還':officeStatus[row.status],...tails(row)])}:
 {headers:['紀錄編號','公告標題','內容','公告對象','置頂設定','截止時間（臺北）','公告狀態'],rows:rows.map(row=>[row.id,row.title,row.body,unit(row.unit_id),row.pinned?'置頂':'一般',formatDateTime(row.due_at),row.archived?'已封存':'發布中',...tails(row)])};
 return {headers:[...result.headers,...common],rows:result.rows};
}

function RequestHistory({request}:{request:OfficeRequest}){
 const transitions=request.transitions||[];
 return <details className="office-request-history" data-testid="office-request-history">
  <summary>狀態與退回紀錄<span>{transitions.length} 筆</span></summary>
  {transitions.length?<ol>{transitions.map((transition,index)=><li key={`${transition.at}:${index}`} data-testid="office-request-transition">
   <div><strong>狀態：{officeStatus[transition.status]||transition.status}</strong><time dateTime={transition.at}>{formatDateTime(transition.at)}</time></div>
   {transition.note&&<p>退回原因：{transition.note}</p>}
  </li>)}</ol>:<p>尚無狀態紀錄。</p>}
 </details>;
}

function OfficeDialog({config,data,locked,closeLocked,pending,onClose,onSubmit}:{config:FormConfig;data:OfficeData;locked:boolean;closeLocked:boolean;pending:boolean;onClose:()=>void;onSubmit:(action:string,payload:Record<string,any>)=>Promise<boolean>}){
 const ref=useRef<HTMLDialogElement>(null),submitLock=useRef(false);
 const [values,setValues]=useState<Record<string,any>>(()=>Object.fromEntries(config.fields.map(field=>[field.key,field.value??(field.type==='checkbox'?false:'')]))),[error,setError]=useState('');
 useEffect(()=>{const previous=document.activeElement as HTMLElement|null,dialog=ref.current;dialog?.showModal();(dialog?.querySelector<HTMLElement>('input,select,textarea')||dialog?.querySelector<HTMLElement>('button'))?.focus();return()=>{dialog?.close();if(previous?.isConnected)previous.focus();else document.querySelector<HTMLElement>('.office-tabs [aria-selected=true]')?.focus()}},[]);
 const requestCreate=config.action==='office.request.create',leave=requestCreate&&values.type==='leave',expense=requestCreate&&(values.type==='purchase'||values.type==='expense');
 let fields=config.fields;
 if(requestCreate){fields=fields.map(field=>field.key==='staff_id'?{...field,label:leave?'假員工':'假員工（選填）',required:leave,options:field.options?.filter(option=>!values.unit_id||data.staff.find(person=>person.id===option.value)?.unit_id===values.unit_id)}:field);if(leave)fields=[...fields,...timeFields];else fields=[...fields,{key:'amount_sim',label:'測試幣金額（SIM）',type:'number',required:true,min:expense?0.01:0,max:1e7,step:'0.01',value:expense?'':'0'}]}
 const change=(key:string,value:any)=>{setError('');setValues(current=>({...current,[key]:value,...(key==='unit_id'?{staff_id:''}:{}),...(key==='type'?{amount_sim:value==='general'?'0':'',start_at:'',end_at:''}:{})}))};
 async function submit(event:FormEvent<HTMLFormElement>){
  event.preventDefault();if(locked||submitLock.current)return;setError('');
  try{
   const payload:Record<string,any>={...config.base};
   for(const field of fields){const value=values[field.key]??field.value??'';if(field.required&&field.type!=='checkbox'&&!String(value).trim())throw new Error(`請填寫${field.label}。`);if(field.type==='checkbox')payload[field.key]=!!value;else if(field.key==='amount_sim'){payload.amount_minor=simMinor(String(value||'0'));if(payload.amount_minor<Math.round((field.min??0)*100))throw new Error('請填寫大於零的測試幣金額。');if(field.max!==undefined&&payload.amount_minor>field.max*100)throw new Error('單筆申請最多登錄 10,000,000 SIM 測試幣。')}else if(field.type==='number'){const number=Number(value);if(!Number.isSafeInteger(number)||number<(field.min??0)||number>(field.max??Number.MAX_SAFE_INTEGER))throw new Error(`${field.label}須填範圍內的整數。`);payload[field.key]=number}else if(field.type==='datetime-local'){payload[field.key]=value?inputToISO(String(value)):null}else payload[field.key]=value===''&&field.nullable?null:String(value).trim();}
   if(config.action==='office.shift.create'||config.action==='office.attendance.create'){const person=data.staff.find(row=>row.id===payload.staff_id);if(!person)throw new Error('請選擇假員工。');payload.unit_id=person.unit_id;}
   if(['office.shift.update','office.attendance.update','office.reservation.update'].includes(config.action)){
    const changed=config.fields.filter(field=>field.key!=='reason').some(field=>{const original=field.type==='datetime-local'?inputToISO(String(field.value)):field.type==='number'?Number(field.value):String(field.value??'').trim();return payload[field.key]!==original});
    if(!changed)throw new Error('請至少修改一個時段、休息分鐘或內容，再填寫更正原因。');
   }
   if(requestCreate&&leave)payload.amount_minor=0;
   if(payload.start_at&&payload.end_at){const minutes=(Date.parse(payload.end_at)-Date.parse(payload.start_at))/60000,shortTime=config.action.startsWith('office.shift.')||config.action.startsWith('office.attendance.'),maximum=shortTime?2880:31*1440;if(minutes<=0||minutes>maximum)throw new Error(`結束時間須晚於開始時間，時段最長 ${shortTime?'48 小時':'31 日'}。`);if(payload.break_minutes!==undefined&&payload.break_minutes>=minutes)throw new Error('休息分鐘須小於整段時間。');}
   if(config.action==='office.demo.create'&&!validMonday(payload.week_start))throw new Error('示範週須選有效的星期一。');
   if(config.action==='office.shift.copy_week'&&(!validMonday(payload.from_date)||!validMonday(payload.to_date)||payload.from_date===payload.to_date))throw new Error('來源與目的須為不同週的有效星期一。');
   submitLock.current=true;const completed=await onSubmit(config.action,payload);if(!completed)setError('操作未完成。請核對頁面上的錯誤或原操作結果，資料尚未確認儲存。');
  }catch(cause){setError(cause instanceof Error?cause.message:'操作未完成，請核對資料後再試。')}
  finally{submitLock.current=false}
 }
 return <dialog ref={ref} className="office-dialog" data-testid="office-dialog" aria-labelledby="office-dialog-title" aria-describedby={`office-dialog-description${pending?' office-pending-help':''}`} onCancel={event=>{if(closeLocked||submitLock.current)event.preventDefault();else onClose()}}><form onSubmit={event=>void submit(event)} data-testid="office-form"><div className="office-dialog-heading"><div><span className="eyebrow">SIM · 確認行政操作</span><h2 id="office-dialog-title">{config.title}</h2></div><button type="button" aria-label={pending?'關閉並確認原操作結果':'關閉行政表單'} disabled={closeLocked} onClick={onClose}>×</button></div><p id="office-dialog-description">{config.description}</p>{pending&&<p id="office-pending-help" className="office-form-error" data-testid="office-pending-help" role="alert">原操作內容已保留。請關閉表單，再使用頁面上方的「確認原操作結果」。原操作確認前，不能編輯或重新送出。</p>}<div className="office-form-fields">{fields.map(field=><label key={field.key} className={field.type==='checkbox'?'office-checkbox':''}>{field.type==='checkbox'?<><input type="checkbox" data-testid={`office-field-${field.key}`} name={field.key} checked={!!values[field.key]} disabled={locked} onChange={event=>change(field.key,event.target.checked)}/><span>{field.label}</span></>:<><span>{field.label}{field.required&&<b aria-hidden="true"> *</b>}</span>{field.type==='select'?<select data-testid={`office-field-${field.key}`} name={field.key} required={field.required} disabled={locked} value={values[field.key]??field.value??''} onChange={event=>change(field.key,event.target.value)}><option value="">{field.required?'請選擇':'不指定'}</option>{field.options?.map(option=><option key={option.value} value={option.value}>{option.label}</option>)}</select>:field.type==='textarea'?<textarea data-testid={`office-field-${field.key}`} name={field.key} required={field.required} disabled={locked} maxLength={field.maxLength??1000} rows={3} value={values[field.key]??''} onChange={event=>change(field.key,event.target.value)}/>:<input data-testid={`office-field-${field.key}`} name={field.key} type={field.type||'text'} required={field.required} disabled={locked} maxLength={field.maxLength??120} min={field.min} max={field.max} step={field.type==='number'?field.step||'1':field.type==='datetime-local'?'60':undefined} value={values[field.key]??field.value??''} onChange={event=>change(field.key,event.target.value)}/>}</>}</label>)}</div>{error&&<p className="office-form-error" data-testid="office-error" role="alert">{error}</p>}<div className="office-dialog-actions"><button type="button" data-testid="office-cancel" disabled={closeLocked} onClick={onClose}>{pending?'關閉並確認原操作結果':'取消'}</button><button type="submit" className="primary" data-testid="office-save" disabled={locked}>{pending?'待確認原操作結果':locked?'處理中…':'確認模擬操作'}</button></div></form></dialog>;
}
