import React,{useRef,useState} from 'react';
import type {Workspace} from './api';
import {Icon} from './icons';
import {capabilities,capabilityStatuses,filterCapabilities,capabilityDestination,type CapabilityStatus} from './capabilities';
import './capability-map.css';

export default function CapabilityMap({workspace,onNavigate}:{workspace:Workspace|null;onNavigate:(module:string)=>void}){
 const [query,setQuery]=useState(''),[group,setGroup]=useState(''),[status,setStatus]=useState('');
 const input=useRef<HTMLInputElement>(null);
 const found=filterCapabilities(query,group,status);
 function reset(){setQuery('');setGroup('');setStatus('');input.current?.focus();}
 return <section className="capability-map" data-testid="capability-map" aria-labelledby="capability-heading"><div className="page-heading"><div><span className="eyebrow">自由 ERP CRM · 功能地圖</span><h1 id="capability-heading">先找到工作，再開啟功能。</h1><p>對照 Business Central、NetSuite 與 Odoo 19 的主要工作領域，列出本系統目前可做與待建的範圍。</p></div><button type="button" data-testid="capability-back" onClick={()=>onNavigate(workspace?'overview':'build')}>{workspace?'回到工作總覽':'開始建立我的系統'}<Icon name="arrow"/></button></div>
  <p className="capability-scope">「已可用」只代表卡片列出的 SIM 功能。未完成的企業能力會顯示待建置；參考產品的完整能力、授權與版本並不等同本系統。</p>
  <div className="capability-summary">{(['ready','partial','planned'] as CapabilityStatus[]).map(value=><button type="button" key={value} data-testid={`capability-summary-${value}`} aria-pressed={status===value} onClick={()=>setStatus(status===value?'':value)}><strong>{capabilities.filter(row=>row.status===value).length}</strong><span>{capabilityStatuses[value]}</span></button>)}</div>
  <div className="capability-tools"><label>找工作或功能<input ref={input} type="search" data-testid="capability-search" value={query} maxLength={120} placeholder="例如：排班、庫存、報價、發票" onChange={event=>setQuery(event.target.value)}/></label><label>工作領域<select data-testid="capability-group" value={group} onChange={event=>setGroup(event.target.value)}><option value="">全部領域</option>{[...new Set(capabilities.map(row=>row.group))].map(value=><option key={value}>{value}</option>)}</select></label><label>完成程度<select data-testid="capability-status" value={status} onChange={event=>setStatus(event.target.value)}><option value="">全部程度</option>{(['ready','partial','planned'] as CapabilityStatus[]).map(value=><option key={value} value={value}>{capabilityStatuses[value]}</option>)}</select></label><button type="button" data-testid="capability-reset" onClick={reset}>清除篩選</button></div>
  <p className="capability-count" role="status">顯示 {found.length}／{capabilities.length} 項功能</p>
  <div className="capability-cards">{found.map(row=>{const destination=capabilityDestination(row,workspace?.modules||null);return <article key={row.id} className={`capability-card is-${row.status}`} data-testid={`capability-${row.id}`}><div className="capability-card-label"><span>{row.group}</span><strong>{capabilityStatuses[row.status]}</strong></div><h2>{row.title}</h2><p>{row.available}</p><p className="capability-gap"><strong>範圍與限制</strong>{row.gap}</p>{row.requires&&<p className="capability-requires">需要功能：{(row.routes?row.routes.map(route=>route.requires.map(key=>({inventory:'商品庫存',sales:'模擬訂單',wallets:'測試幣流水',crm:'客戶與商機',services:'報價與服務',administration:'行政工作台'} as Record<string,string>)[key]).join('＋')).join('，或 '):row.requires.map(key=>({inventory:'商品庫存',sales:'模擬訂單',wallets:'測試幣流水',crm:'客戶與商機',services:'報價與服務',manufacturing:'BOM 與製造',projects:'任務與里程碑',administration:'行政工作台'} as Record<string,string>)[key]).join('、'))}</p>}<div className="capability-card-action">{destination?<button type="button" data-testid={`capability-open-${row.id}`} onClick={()=>onNavigate(destination)}>{destination==='build'?(workspace?'檢視另一套建置計畫':'建立系統後使用'):row.status==='partial'?'查看已實作部分':'開啟功能'}<Icon name="arrow"/></button>:<a data-testid={`capability-plan-${row.id}`} href="/enterprise-plan.html">查看建置藍圖 ↗</a>}</div></article>})}</div>
  {!found.length&&<div className="capability-empty"><h2>找不到符合的功能</h2><p>換一個關鍵字，或清除工作領域與完成程度。</p><button type="button" onClick={reset}>顯示全部功能</button></div>}
  <details className="capability-references"><summary>參考產品與設計來源</summary><p>我們使用公開資料研究操作方式，再自行撰寫程式。功能地圖沒有連線到這些產品或匯入它們的程式。</p><a href="https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-designing-role-centers" target="_blank" rel="noreferrer">Business Central 角色工作台 ↗</a><a href="https://docs.oracle.com/en/cloud/saas/netsuite/ns-online-help/section_1511800348.html" target="_blank" rel="noreferrer">NetSuite SuiteSuccess ↗</a><a href="https://www.odoo.com/documentation/19.0/" target="_blank" rel="noreferrer">Odoo 19 官方文件 ↗</a><a href="https://github.com/mars-tw/freedom-erp-crm/blob/main/docs/erp-reference-map.md" target="_blank" rel="noreferrer">完整能力對照與驗收規格 ↗</a></details>
 </section>;
}
