import {useEffect,useId,useRef,useState} from 'react';
import {designTemplates,type DesignTemplateId} from './design-templates';
import './design-studio.css';

type DesignTemplate=(typeof designTemplates)[number];
type Category='all'|'business'|'store'|'creative'|'factory';
const categories:{id:Category;name:string}[]=[{id:'all',name:'全部模板'},{id:'business',name:'商務'},{id:'store',name:'店家'},{id:'creative',name:'創意'},{id:'factory',name:'工廠'}];
const categoryName=(category:DesignTemplate['category'])=>categories.find(item=>item.id===category)?.name||category;
const layoutNames={rail:'左側導覽',top:'上方導覽',floating:'浮動導覽'};
const templateById=(id:DesignTemplateId)=>designTemplates.find(template=>template.id===id)||designTemplates[0];
const returnFocus=(id:DesignTemplateId,action:'preview'|'apply')=>window.requestAnimationFrame(()=>{const target=document.querySelector<HTMLButtonElement>(`[data-testid="design-${action}-${id}"]`),fallback=document.querySelector<HTMLButtonElement>(`[data-testid="design-preview-${id}"]`);(target&&!target.disabled?target:fallback)?.focus({preventScroll:true})});

export interface DesignStudioProps {
 applied:DesignTemplateId;
 preview:DesignTemplateId|null;
 onPreview:(id:DesignTemplateId)=>void;
 onApply:(id:DesignTemplateId)=>void;
 onCancelPreview:()=>void;
 onOpenWorkspace:()=>void;
 volatile:boolean;
}

export default function DesignStudio({applied,preview,onPreview,onApply,onCancelPreview,onOpenWorkspace,volatile}:DesignStudioProps){
 const [category,setCategory]=useState<Category>('all'),[query,setQuery]=useState(''),[featuredId,setFeaturedId]=useState<DesignTemplateId>(preview||applied);
 const searchRef=useRef<HTMLInputElement>(null);
 const active=templateById(applied),featured=templateById(featuredId);
 useEffect(()=>{setFeaturedId(preview||applied)},[preview,applied]);
 const keyword=query.trim().toLocaleLowerCase();
 const visible=designTemplates.filter(template=>(category==='all'||template.category===category)&&[template.name,template.englishName,template.description,template.signature,...template.tags,categoryName(template.category),layoutNames[template.layout]].join(' ').toLocaleLowerCase().includes(keyword));
 const showPreview=(id:DesignTemplateId)=>{setFeaturedId(id);onPreview(id)};
 const apply=(id:DesignTemplateId)=>{onApply(id);returnFocus(id,'apply')};
 const clear=()=>{setQuery('');setCategory('all');searchRef.current?.focus()};
 return <section className={`design-studio ${preview?'is-previewing':''}`} data-testid="design-studio">
  <header className="design-studio-heading">
   <div><span className="design-kicker">工作台外觀 · 原創設計系列</span><h1>挑一套外觀，試看你的工作台。</h1><p>八種版面，各有不同的導覽、字體、色彩與卡片形狀。帶著目前資料試看，喜歡再套用。</p></div>
   <div className="design-applied"><span className="design-applied-mark" aria-hidden="true">✓</span><div><small>目前套用</small><strong data-testid="design-active-name">{active.name}</strong><span>{active.englishName}</span></div></div>
  </header>
  {volatile&&<p className="design-storage-note" role="status">這次外觀偏好暫存於本分頁。瀏覽器目前無法保存，關閉分頁後可能恢復原設定。</p>}
  <section className="design-featured" aria-labelledby="design-featured-heading">
   <div className="design-featured-art"><DesignThumbnail template={featured}/><span className="design-feature-label">精選展示 · {layoutNames[featured.layout]}</span></div>
   <div className="design-featured-copy"><span className="design-kicker">從版面的個性開始選</span><span className="design-featured-english">{featured.englishName}</span><h2 id="design-featured-heading">{featured.name}</h2><p>{featured.description}</p><div className="design-signature"><span>設計特色</span><strong>{featured.signature}</strong></div><div className="design-featured-actions"><button type="button" className="design-button-primary" data-testid="design-open-workspace" onClick={()=>{onPreview(featured.id);onOpenWorkspace()}}>到工作台看效果 <span aria-hidden="true">↗</span></button><span>只試看外觀；資料保留原樣。</span></div><div className="design-featured-switches" aria-label="選擇精選展示">{(['harbor','atelier','industrial'] as DesignTemplateId[]).map(id=>{const template=templateById(id);return <button type="button" key={id} aria-pressed={featuredId===id} onClick={()=>setFeaturedId(id)}>{template.englishName}</button>})}</div></div>
  </section>
  <div className="design-gallery-heading"><div><span className="design-kicker">每一套都有自己的結構</span><h2>設計模板圖庫</h2></div><p>點「試看這套」即時切換外觀，再進工作台看實際效果。取消試看會回到目前套用的模板。</p></div>
  <div className="design-gallery-tools"><div className="design-category-filters" role="group" aria-label="設計模板分類">{categories.map(item=><button type="button" key={item.id} data-testid={`design-filter-${item.id}`} aria-pressed={category===item.id} onClick={()=>setCategory(item.id)}>{item.name}<span>{item.id==='all'?designTemplates.length:designTemplates.filter(template=>template.category===item.id).length}</span></button>)}</div><label className="design-search"><span className="design-search-icon" aria-hidden="true"><svg viewBox="0 0 20 20" fill="none"><circle cx="8.5" cy="8.5" r="5.5"/><path d="m12.5 12.5 4 4"/></svg></span><span className="design-sr-only">搜尋設計模板</span><input ref={searchRef} type="search" data-testid="design-search" value={query} maxLength={100} placeholder="搜尋名稱、風格或導覽" onChange={event=>setQuery(event.target.value)}/></label></div>
  <div className="design-result-line" aria-live="polite"><span>顯示 {visible.length}／{designTemplates.length} 套 · {categories.find(item=>item.id===category)?.name}</span>{(keyword||category!=='all')&&<button type="button" onClick={clear}>清除篩選</button>}</div>
  {visible.length?<div className="design-gallery-grid">{visible.map(template=>{
   const current=applied===template.id,trying=preview===template.id;
   return <article key={template.id} className={`design-template-card ${current?'is-applied':''} ${trying?'is-preview':''}`} data-testid={`design-card-${template.id}`} data-template-id={template.id} data-layout={template.layout}>
    <figure className="design-card-art"><DesignThumbnail template={template}/><div className="design-card-badges"><span>{categoryName(template.category)}</span>{current&&<strong>目前套用</strong>}{trying&&<strong>試看中</strong>}</div><figcaption>版面示意 · {layoutNames[template.layout]}</figcaption></figure>
    <div className="design-card-body"><div className="design-card-title"><div><span>{template.englishName}</span><h3>{template.name}</h3></div><div className="design-palette" aria-label={`${template.name}的主要色彩`}>{template.palette.map((color,index)=><span key={`${color}-${index}`} style={{backgroundColor:color}} title={color}/>)}</div></div><p>{template.description}</p><div className="design-card-signature">{template.signature}</div><ul className="design-card-tags" aria-label="風格標籤">{template.tags.map(tag=><li key={tag}>{tag}</li>)}</ul><div className="design-card-actions"><button type="button" data-testid={`design-preview-${template.id}`} aria-pressed={trying} onClick={()=>showPreview(template.id)}>{trying?'正在試看':'試看這套'} <span aria-hidden="true">↗</span></button><button type="button" className="design-apply-button" data-testid={`design-apply-${template.id}`} disabled={current&&!preview} onClick={()=>apply(template.id)}>{current?(preview?'回到這套':'已套用'):'套用這套'}</button></div></div>
   </article>;
  })}</div>:<div className="design-empty" data-testid="design-empty"><svg aria-hidden="true" viewBox="0 0 64 64" fill="none"><rect x="9" y="12" width="46" height="40" rx="7"/><path d="M9 23h46M22 34h20M22 41h12"/></svg><h3>沒有符合的設計模板。</h3><p>換個名稱或風格關鍵字，也可以回到全部模板重新挑選。</p><button type="button" data-testid="design-clear-search" onClick={clear}>清除搜尋與分類</button></div>}
  <div className="design-studio-footer"><span>八套原創版面，同一份工作資料。</span><p>{volatile?'偏好暫存於本分頁。':'套用結果只儲存在本瀏覽器。'}切換外觀不會變更工作區、模擬交易或行政紀錄；淺深色與資訊密度仍可另外調整。</p>{preview&&<button type="button" className="design-inline-cancel" onClick={()=>{const previous=preview;onCancelPreview();returnFocus(previous,'preview')}}>取消這次試看</button>}</div>
 </section>;
}

export function DesignPreviewBar({id,onApply,onCancel}:{id:DesignTemplateId;onApply:()=>void;onCancel:()=>void}){
 const template=templateById(id);
 return <aside className="design-preview-banner" data-testid="design-preview-banner" data-template-id={id} aria-label="工作台模板試看"><span className="design-preview-swatch" style={{backgroundColor:template.palette[3]}} aria-hidden="true"/><div className="design-preview-copy"><small>外觀試看中</small><strong>{template.name}</strong><span>工作資料保留原樣；確認後才保存外觀偏好。</span></div><div className="design-preview-actions"><button type="button" data-testid="design-preview-cancel" onClick={()=>{onCancel();returnFocus(id,'preview')}}>取消試看</button><button type="button" className="design-button-primary" data-testid="design-preview-apply" onClick={()=>{onApply();returnFocus(id,'apply')}}>套用這個模板</button></div></aside>;
}

function MiniLine({x,y,width,color,opacity=1,height=5}:{x:number;y:number;width:number;color:string;opacity?:number;height?:number}){return <rect x={x} y={y} width={width} height={height} rx={height/2} fill={color} opacity={opacity}/>}
function MiniTile({x,y,width=100,height=72,radius=8,surface,ink,accent}:{x:number;y:number;width?:number;height?:number;radius?:number;surface:string;ink:string;accent:string}){return <g><rect x={x} y={y} width={width} height={height} rx={radius} fill={surface}/><MiniLine x={x+12} y={y+13} width={width*.35} color={accent} height={4}/><MiniLine x={x+12} y={y+28} width={width*.58} color={ink} opacity={.45} height={7}/><MiniLine x={x+12} y={y+height-14} width={width*.66} color={ink} opacity={.13} height={3}/></g>}
function MiniRows({x,y,width,ink,accent,rows=3}:{x:number;y:number;width:number;ink:string;accent:string;rows?:number}){return <g>{Array.from({length:rows},(_,index)=><g key={index}><circle cx={x+4} cy={y+index*22+3} r={3} fill={accent} opacity={index===0?1:.4}/><MiniLine x={x+15} y={y+index*22} width={width*.56} color={ink} opacity={.35} height={4}/><MiniLine x={x+width-32} y={y+index*22} width={26} color={accent} opacity={.5} height={4}/><path d={`M${x} ${y+index*22+15}h${width}`} stroke={ink} opacity={.08}/></g>)}</g>}
function DesignThumbnail({template}:{template:DesignTemplate}){
 const identity=useId().replaceAll(':',''),[background,surface,ink,accent,secondary=accent]=template.palette;
 const text=(value:string,x:number,y:number,size=11,color=ink,serif=false)=><text x={x} y={y} fill={color} fontSize={size} fontWeight={600} fontFamily={serif?'Georgia,serif':'Segoe UI,Microsoft JhengHei,sans-serif'}>{value}</text>;
 const rail=(dark=ink,width=78,round=0)=><g><rect x={12} y={12} width={width} height={276} rx={round} fill={dark}/>{text('F',28,43,22,surface,true)}{[0,1,2,3,4].map(index=><g key={index}><rect x={24} y={64+index*31} width={width-24} height={22} rx={round?5:0} fill={index===1?accent:surface} opacity={index===1?1:.07}/><MiniLine x={33} y={73+index*31} width={width-42} color={surface} opacity={index===1?.95:.55} height={3}/></g>)}</g>;
 let scene;
 if(template.id==='harbor')scene=<><rect width="480" height="300" fill={background}/>{rail(ink,82,12)}<rect x="108" y="12" width="360" height="33" rx="10" fill={ink}/>{text('WORKSPACE',124,33,10,surface)}<rect x="419" y="21" width="35" height="14" rx="7" fill={accent}/><rect x="108" y="58" width="360" height="82" rx="14" fill={ink}/>{text('工作總覽',127,88,20,surface)}<MiniLine x={128} y={105} width={157} color={surface} opacity={.35}/><circle cx="421" cy="99" r="24" fill="none" stroke={accent} strokeWidth="6"/><path d="M421 75a24 24 0 0 1 24 24" stroke={secondary} strokeWidth="6" fill="none"/><MiniTile x={108} y={152} width={174} height={66} surface={surface} ink={ink} accent={accent}/><MiniTile x={294} y={152} width={174} height={66} surface={surface} ink={ink} accent={secondary}/><rect x="108" y="231" width="360" height="57" rx="10" fill={surface}/><MiniRows x={124} y={245} width={328} ink={ink} accent={accent} rows={2}/></>;
 else if(template.id==='executive')scene=<><rect width="480" height="300" fill={background}/>{rail(ink,92)}<rect x="106" y="12" width="362" height="276" fill={surface}/><path d="M124 58h328M124 113h328M124 266h328" stroke={accent} strokeWidth="1"/>{text('Executive',124,47,25,ink,true)}{text('WORKSPACE / OVERVIEW',125,81,9,accent)}<MiniLine x={124} y={94} width={137} color={ink} opacity={.3} height={4}/><rect x="124" y="129" width="203" height="121" fill={background}/><rect x="340" y="129" width="112" height="121" fill={ink}/>{text('工作紀錄',139,153,12)}<MiniRows x={139} y={169} width={170} ink={ink} accent={accent}/>{text('今日安排',352,154,10,surface)}<MiniLine x={352} y={176} width={64} color={secondary}/><MiniLine x={352} y={193} width={81} color={surface} opacity={.4}/><MiniLine x={352} y={210} width={55} color={surface} opacity={.2}/></>;
 else if(template.id==='atelier')scene=<><rect width="480" height="300" fill={background}/>{text('A.',22,33,23,ink,true)}{[0,1,2,3].map(index=><g key={index}><rect x={172+index*71} y="14" width="64" height="25" rx="13" fill={index===0?ink:surface}/><MiniLine x={185+index*71} y={25} width={37} color={index===0?surface:ink} opacity={.7} height={3}/></g>)}{text('Atelier',22,112,61,ink)}<circle cx="427" cy="96" r="28" fill={secondary}/><path d="m415 107 23-23m-22 0h22v22" stroke={ink} strokeWidth="2" fill="none"/><rect x="22" y="136" width="281" height="143" rx="30" fill={accent}/><rect x="317" y="136" width="141" height="143" rx="30" fill={surface}/><path d="M192 136v143M22 218h281" stroke={surface} opacity={.25}/>{text('工作紀錄',43,166,16,surface)}<MiniLine x={44} y={188} width={118} color={surface} opacity={.45}/><circle cx="247" cy="185" r="32" fill={secondary}/><MiniRows x={41} y={235} width={242} ink={surface} accent={surface} rows={2}/>{text('安排',337,166,14)}<rect x="337" y="185" width="100" height="20" rx="10" fill={background}/><rect x="337" y="219" width="74" height="38" rx="19" fill={secondary}/></>;
 else if(template.id==='commerce')scene=<><rect width="480" height="300" fill={background}/><rect width="480" height="44" fill={accent}/>{text('F / STORE',20,28,16,surface)}{[0,1,2].map(index=><rect key={index} x={264+index*65} y="14" width="54" height="17" rx="9" fill={index===0?secondary:surface} opacity={index===0?1:.2}/>)}{text('店務工作台',20,82,24,ink)}<rect x="374" y="61" width="86" height="27" rx="14" fill={secondary}/>{[0,1,2].map(index=><g key={index}><rect x={20+index*150} y="105" width="140" height="149" rx="12" fill={surface}/><rect x={30+index*150} y="115" width="120" height="73" rx="8" fill={index===1?accent:background}/>{index===0?<circle cx="90" cy="151" r="22" fill={secondary}/>:index===1?<path d="m231 132 15 10v21l-15 9-15-9v-21z" fill={surface}/>:<rect x="361" y="131" width="39" height="41" rx="8" fill={accent}/>}<MiniLine x={32+index*150} y={204} width={80} color={ink} opacity={.6}/><MiniLine x={32+index*150} y={222} width={105} color={ink} opacity={.15}/><rect x={32+index*150} y="236" width="47" height="8" rx="4" fill={accent} opacity={.2}/></g>)}<path d="M20 276h440" stroke={ink} opacity={.12}/></>;
 else if(template.id==='industrial')scene=<><rect width="480" height="300" fill={background}/>{rail(ink,57)}<path d="M88 12h380v276H88z" fill={surface} stroke={ink} strokeOpacity={.22}/><rect x="88" y="12" width="380" height="28" fill={ink}/>{text('CONTROL / WORKSPACE',101,31,11,surface)}<rect x="422" y="20" width="32" height="11" fill={accent}/>{text('工作控制室',102, 74,20)}<path d="M102 87h352" stroke={ink} opacity={.3}/>{[0,1,2].map(index=><g key={index}><rect x={102+index*118} y="102" width="108" height="49" fill={background} stroke={ink} strokeOpacity={.2}/><rect x={102+index*118} y="102" width="4" height="49" fill={index===1?secondary:accent}/><MiniLine x={114+index*118} y={115} width={44} color={ink} opacity={.45} height={4}/><MiniLine x={114+index*118} y={131} width={70} color={accent} height={6}/></g>)}<path d="M102 168h352v103H102zM102 191h352M102 218h352M102 244h352M211 168v103M341 168v103" stroke={ink} strokeOpacity={.2} fill="none"/><rect x="102" y="168" width="352" height="23" fill={ink} opacity={.08}/><MiniRows x={113} y={202} width={325} ink={ink} accent={accent} rows={3}/></>;
 else if(template.id==='verdant')scene=<><rect width="480" height="300" fill={background}/><rect x="18" y="15" width="444" height="35" rx="18" fill={surface}/>{text('F / VERDANT',35,38,13,accent)}<circle cx="436" cy="32" r="10" fill={accent}/><rect x="18" y="65" width="73" height="217" rx="25" fill={surface}/>{[0,1,2,3].map(index=><g key={index}><circle cx="55" cy={98+index*44} r="13" fill={index===0?accent:background}/><MiniLine x={35} y={118+index*44} width={40} color={ink} opacity={.16} height={3}/></g>)}<rect x="109" y="65" width="353" height="105" rx="27" fill={accent}/>{text('店務，慢慢整理好。',133,104,24,surface)}<MiniLine x={134} y={129} width={187} color={surface} opacity={.45}/><path d="M430 86c-36 2-48 19-42 44 29 1 48-16 42-44ZM404 151v-37" stroke={secondary} strokeWidth="3" fill="none"/><MiniTile x={109} y={188} width={169} height={94} radius={20} surface={surface} ink={ink} accent={accent}/><MiniTile x={293} y={188} width={169} height={94} radius={20} surface={surface} ink={ink} accent={secondary}/></>;
 else if(template.id==='editorial')scene=<><rect width="480" height="300" fill={background}/><rect x="18" y="15" width="444" height="270" fill={surface}/>{text('Editorial',34,49,31,ink,true)}{text('WORKSPACE',360,46,10,accent)}<path d="M34 63h412M34 94h412M34 133h412M34 267h412" stroke={ink} opacity={.45}/>{['總覽','紀錄','安排','設定'].map((item,index)=>text(item,35+index*112,83,11,ink))}{text('把工作放回清楚的位置。',34,119,20,ink,true)}<path d="M288 149v100" stroke={ink} opacity={.25}/><rect x="34" y="149" width="237" height="47" fill={accent}/>{text('工作紀錄',48,177,15,surface)}<MiniRows x={35} y={211} width={233} ink={ink} accent={accent} rows={2}/>{text('安排與筆記',307,166,14,ink,true)}<MiniLine x={309} y={184} width={122} color={secondary} height={8}/><MiniLine x={309} y={208} width={113} color={ink} opacity={.15}/><MiniLine x={309} y={227} width={97} color={ink} opacity={.15}/></>;
 else scene=<><rect width="480" height="300" fill={background}/>{rail(ink,71)}<path d="M96 12h372v276H96z" fill={ink}/><path d="M112 41h340M112 270h340" stroke={accent} strokeWidth="1"/>{text('MIDNIGHT / WORKSPACE',113,31,11,surface)}{text('工作總覽',113,79,21,surface)}<MiniLine x={113} y={96} width={168} color={surface} opacity={.3}/>{[0,1,2].map(index=><g key={index}><path d={`M${113+index*115} 119h95l10 10v58h-105z`} fill={accent} fillOpacity={.16} stroke={index===1?secondary:accent} strokeOpacity={.8}/><MiniLine x={125+index*115} y={133} width={43} color={surface} opacity={.6}/><MiniLine x={125+index*115} y={151} width={67} color={index===1?secondary:surface} opacity={.8} height={9}/></g>)}<path d="M113 207h339v47H113z" fill={surface} fillOpacity={.06} stroke={accent} strokeOpacity={.35}/><MiniRows x={125} y={220} width={311} ink={surface} accent={secondary} rows={1}/><circle cx="438" cy="73" r="10" fill="none" stroke={secondary} strokeWidth="2"/></>;
 return <svg className={`design-thumbnail thumbnail-${template.id}`} viewBox="0 0 480 300" aria-hidden="true" focusable="false"><defs><clipPath id={`design-clip-${identity}`}><rect width="480" height="300" rx="5"/></clipPath></defs><g clipPath={`url(#design-clip-${identity})`}>{scene}</g></svg>;
}
