import type {RecordData,Workspace} from './api';
import {isLearningSession,type LearningSession} from './learning';
export type RecordKind='customer'|'deal'|'contact'|'case'|'quote'|'product'|'wallet'|'order'|'service'|'bom'|'workOrder'|'task'|'milestone';
export interface WorkspaceTarget {module:string;kind:RecordKind;id:string}
export interface WorkbenchRecord {target:WorkspaceTarget;title:string;description:string;status?:string;searchText:string}
export interface WorkQueueItem {id:string;target:WorkspaceTarget;title:string;description:string;priority:'attention'|'next';label:string}
const collections:Record<RecordKind,string>={customer:'customers',deal:'deals',contact:'contacts',case:'cases',quote:'quotes',product:'products',wallet:'wallets',order:'orders',service:'services',bom:'boms',workOrder:'workOrders',task:'tasks',milestone:'milestones'};
const moduleFor=(w:Workspace,kind:RecordKind)=>kind==='quote'?(w.modules.includes('services')?'services':'crm'):({customer:'crm',deal:'crm',contact:'crm',case:'crm',product:'inventory',wallet:'wallets',order:'sales',service:'services',bom:'manufacturing',workOrder:'manufacturing',task:'projects',milestone:'projects'} as Partial<Record<RecordKind,string>>)[kind]!;
const rows=(w:Workspace,kind:RecordKind):RecordData[]=>w[collections[kind]]??[];
const find=(w:Workspace,kind:RecordKind,id:unknown)=>rows(w,kind).find(v=>v.id===id);
const target=(w:Workspace,kind:RecordKind,id:string):WorkspaceTarget=>({module:moduleFor(w,kind),kind,id});
export const recordLabel=(kind:RecordKind)=>({customer:'客戶',deal:'商機',contact:'聯絡人',case:'案件',quote:'模擬報價',product:'商品',wallet:'測試幣錢包',order:'模擬訂單',service:'模擬服務',bom:'BOM',workOrder:'製作單',task:'任務',milestone:'里程碑'})[kind];
const labels:Record<string,string>={draft:'草稿',issued:'已發出',superseded:'已取代',simulated_confirmed:'已模擬確認',pending:'待付款',partially_paid:'部分付款',paid:'已付款',partially_shipped:'部分出貨',shipped:'已出貨',partially_returned:'部分退貨',returned:'已退貨',cancelled:'已取消',confirmed:'已確認',submitted:'待驗收',changes_requested:'需補件',accepted:'已驗收',planned:'計畫中',reserved:'已備料',started:'製作中',completed:'已完工',done:'已完成',todo:'待辦',in_progress:'進行中',open:'進行中',new:'待聯繫',won:'已成交',lost:'未成交',closed:'已結案'};
export const statusLabel=(status:string)=>labels[status]??status;
const money=(n:number)=>`${(n/100).toLocaleString('zh-TW',{maximumFractionDigits:2})} SIM`;
const title=(kind:RecordKind,r:RecordData)=>String(r.name??r.title??r.sku??`${recordLabel(kind)} ${String(r.id).slice(0,8)}`);
const normalize=(v:string)=>v.normalize('NFKC').toLocaleLowerCase().replace(/\s+/g,' ').trim();
export function validTarget(w:Workspace,value:unknown):value is WorkspaceTarget{if(!value||typeof value!=='object'||Array.isArray(value))return false;const t=value as WorkspaceTarget;return Object.hasOwn(collections,t.kind)&&typeof t.id==='string'&&t.module===moduleFor(w,t.kind)&&w.modules.includes(t.module)&&!!find(w,t.kind,t.id);}
function relations(w:Workspace,kind:RecordKind,r:RecordData):string[]{const text:string[]=[];const add=(k:RecordKind,id:unknown)=>{const v=find(w,k,id);if(v)text.push(title(k,v),...(typeof v.sku==='string'?[v.sku]:[]));};
 if(['contact','deal','case','task','milestone'].includes(kind)&&r.customer_id)add('customer',r.customer_id);
 if(['quote','service','task','milestone'].includes(kind)&&r.case_id){add('case',r.case_id);const c=find(w,'case',r.case_id);if(c?.customer_id)add('customer',c.customer_id);}
 if(kind==='order'){add('wallet',r.buyer_wallet_id);for(const l of r.lines??[]){add('product',l.product_id);if(l.name)text.push(l.name);}}
 if(kind==='bom'||kind==='workOrder'){const b=kind==='bom'?r:r.bom_snapshot; if(b){add('product',b.product_id);for(const c of b.components??[])add('product',c.product_id);}if(kind==='workOrder'){const b=find(w,'bom',r.bom_id);if(b)text.push(`BOM 第 ${b.revision} 版`);}}
 return [...new Set(text)];}
export function indexWorkspace(w:Workspace):WorkbenchRecord[]{const out:WorkbenchRecord[]=[];for(const kind of Object.keys(collections)as RecordKind[]){const module=moduleFor(w,kind);if(!w.modules.includes(module))continue;for(const r of rows(w,kind)){const linked=relations(w,kind,r);const status=typeof r.status==='string'?r.status:kind==='product'?(r.active?'啟用中':'停用中'):undefined;const description=[recordLabel(kind),status?statusLabel(status):'',...linked].filter(Boolean).join(' · ');const strings=['name','title','sku','notes','email','phone','lost_reason'].map(k=>typeof r[k]==='string'?r[k]:'');out.push({target:{module,kind,id:r.id},title:title(kind,r),description,status,searchText:normalize([title(kind,r),description,...strings].join(' '))});}}return out;}
export function searchWorkspace(w:Workspace,query:string):WorkbenchRecord[]{const tokens=normalize(String(query)).split(' ').filter(Boolean);return tokens.length?indexWorkspace(w).filter(r=>tokens.every(t=>r.searchText.includes(t))):[];}
export function readiness(w:Workspace,kind:RecordKind,row:RecordData):{summary:string;blockers:{message:string;target:WorkspaceTarget}[]}{const t=target(w,kind,row.id);if(!validTarget(w,t))return {summary:'這筆紀錄不在目前啟用的工作區。',blockers:[]};const r=find(w,kind,row.id)!;const blockers:{message:string;target:WorkspaceTarget}[]=[];const block=(message:string,k:RecordKind,id:string)=>{const to=target(w,k,id);blockers.push({message,target:validTarget(w,to)?to:t});};
 if(kind==='order'){if(['cancelled','returned'].includes(r.status))return {summary:'這筆訂單已取消或全部退貨，不列為一般待辦。',blockers};const remaining=r.total_minor-r.paid_minor;if(remaining>0){const buyer=find(w,'wallet',r.buyer_wallet_id);if(!buyer||buyer.balance_minor<=0)block(`買家沒有可用測試幣，尚欠 ${money(remaining)}。`,'wallet',buyer?.id??r.buyer_wallet_id);return {summary:buyer?.balance_minor>0?`尚欠 ${money(remaining)}，目前可先支付最多 ${money(Math.min(remaining,buyer!.balance_minor))}；允許部分付款。`:`尚欠 ${money(remaining)}，請先準備買家測試幣。`,blockers};}const unshipped=(r.lines??[]).filter((l:RecordData)=>l.shipped_quantity<l.quantity);for(const l of unshipped){const p=find(w,'product',l.product_id);if(!p||p.on_hand<l.quantity-l.shipped_quantity||p.reserved<l.quantity-l.shipped_quantity)block('本筆訂單的現有庫存或預留數量不足。','product',l.product_id);}return {summary:unshipped.length?'已付清測試幣，可依訂單剩餘數量出貨。':'已全部出貨，不再建議出貨。',blockers};}
 if(kind==='workOrder'){const b=r.bom_snapshot;if(['completed','cancelled'].includes(r.status))return {summary:r.status==='completed'?`已完工 ${r.quantity} 件，實際材料成本 ${money(r.actual_cost_minor)}。`:'工單已取消，不列為待辦。',blockers};for(const c of b?.components??[]){const p=find(w,'product',c.product_id),need=c.quantity*r.quantity;const available=r.status==='planned'?(p?.on_hand??0)-(p?.reserved??0):Math.min(p?.on_hand??0,p?.reserved??0);if(available<need)block(`「${p?.name??'材料'}」需要 ${need} 件，目前${r.status==='planned'?'可用':'已預留'} ${available} 件；依本工單凍結的 BOM。`,'product',c.product_id);}return {summary:r.status==='planned'?'依凍結 BOM 核對共享庫存；材料足夠後可備料。':r.status==='reserved'?'材料已為本工單預留，可開工。':'製作中；完工才消耗材料並轉入成品成本。',blockers};}
 if(kind==='service'){if(r.status==='draft')return {summary:'服務草稿，確認內容後才能提交交付物。',blockers};if(r.status==='confirmed'||r.status==='changes_requested')return {summary:r.status==='confirmed'?'已確認服務，可提交第一版交付物。':'需要補件；請提交新版本，舊版本不可作為最新驗收依據。',blockers};const d=(r.deliveries??[]).find((d:RecordData)=>d.id===r.latest_delivery_id);if(!d||typeof d.digest!=='string'||!d.digest)block('找不到最新交付與摘要，請核對服務版本。','service',r.id);if(r.status==='submitted')return {summary:'請以最新交付識別與正確摘要進行模擬驗收。',blockers};if(r.status==='accepted'&&r.paid_minor<r.amount_minor){const buyers=w.wallets.filter(v=>v.kind==='buyer'&&v.balance_minor>0);if(!buyers.length){const buyer=w.wallets.find(v=>v.kind==='buyer');block('沒有買家可用測試幣；請選擇並補充付款錢包。','wallet',buyer?.id??r.id);}return {summary:`已驗收，尚欠 ${money(r.amount_minor-r.paid_minor)}；付款時需明確選擇買家錢包，可部分付款。`,blockers};}return {summary:'服務測試幣已收足，不列為收款待辦。',blockers};}
 if(kind==='quote')return {summary:r.status==='issued'?`報價已凍結，確認時需使用正確摘要；有效期限 ${r.expires_at}。`:r.status==='draft'?'草稿可發出；發出後內容凍結。':'這份報價已確認或被取代，不列為待辦。',blockers};
 return {summary:kind==='product'?`共用庫存：現有 ${r.on_hand} 件、預留 ${r.reserved} 件、可用 ${r.on_hand-r.reserved} 件。`:kind==='wallet'?`可用餘額 ${money(r.balance_minor)}，只提供 SIM 測試幣。`:`${recordLabel(kind)}${r.status?'：'+statusLabel(r.status):'可在對應模組查看及更新'}。`,blockers};}
export function workQueue(w:Workspace,now=Date.now()):WorkQueueItem[]{const result:WorkQueueItem[]=[];const add=(kind:RecordKind,r:RecordData,operation:string,label:string,to=target(w,kind,r.id),attention=false)=>{if(!validTarget(w,to))return;const ready=readiness(w,kind,r);result.push({id:`${kind}:${r.id}:${operation}`,target:to,title:title(kind,r),description:operation==='expired'?'報價已過期，請回到原案件重新起草模擬報價。':(kind==='task'||kind==='milestone')&&attention?('期限 '+new Date(r.due_at).toLocaleString('zh-TW')+' 已過；'+ready.summary):ready.blockers.map(v=>v.message).join(' ')||ready.summary,priority:attention?'attention':'next',label});};
 if(w.modules.includes('sales'))for(const o of w.orders){if(['cancelled','returned'].includes(o.status))continue;if(o.paid_minor<o.total_minor){const buyer=find(w,'wallet',o.buyer_wallet_id);add('order',o,'pay',buyer?.balance_minor>0?'支付測試幣':'準備買家測試幣',buyer?.balance_minor>0?target(w,'order',o.id):target(w,'wallet',o.buyer_wallet_id),!(buyer?.balance_minor>0));}else if(o.lines.some((l:RecordData)=>l.shipped_quantity<l.quantity)){const ready=readiness(w,'order',o);add('order',o,'ship','核對並出貨',ready.blockers[0]?.target??target(w,'order',o.id),ready.blockers.length>0);}}
 if(w.modules.includes('manufacturing'))for(const o of w.workOrders){if(!['planned','reserved','started'].includes(o.status))continue;const ready=readiness(w,'workOrder',o);add('workOrder',o,o.status,ready.blockers.length?'補足工單材料':o.status==='planned'?'預留材料':o.status==='reserved'?'開始製作':'完成製作',ready.blockers[0]?.target??target(w,'workOrder',o.id),ready.blockers.length>0);}
 if(w.modules.includes('services'))for(const s of w.services){if(!['draft','confirmed','changes_requested','submitted','accepted'].includes(s.status)||s.status==='accepted'&&s.paid_minor>=s.amount_minor)continue;const ready=readiness(w,'service',s);add('service',s,s.status,({draft:'確認服務',confirmed:'提交交付物',changes_requested:'提交補件',submitted:'驗收最新交付',accepted:'收取測試幣'} as Record<string,string>)[s.status],ready.blockers[0]?.target??target(w,'service',s.id),ready.blockers.length>0||s.status==='changes_requested');}
 if(w.modules.includes(moduleFor(w,'quote')))for(const q of w.quotes)if(q.status==='issued'&&Number.isFinite(Date.parse(q.expires_at))&&Date.parse(q.expires_at)<=now){const c=find(w,'case',q.case_id);add('quote',q,'expired','重新起草報價',c?target(w,'case',c.id):target(w,'quote',q.id),true);}
 if(w.modules.includes('projects'))for(const kind of ['task','milestone']as const)for(const r of rows(w,kind)){if(['done','completed','cancelled','closed'].includes(r.status))continue;const due=typeof r.due_at==='string'?Date.parse(r.due_at):NaN;const overdue=Number.isFinite(due)&&due<now;add(kind,r,'progress',overdue?'處理逾期待辦':'更新進度',target(w,kind,r.id),overdue);}
 return result.sort((a,b)=>Number(b.priority==='attention')-Number(a.priority==='attention'));}
export function learningRecordTarget(w:Workspace,s:LearningSession,stepId:string):WorkspaceTarget|undefined{if(!isLearningSession(s,w))return;const c=s.checkpoints.find(v=>v.stepId===stepId);if(!c||!w.history?.some((h:RecordData)=>h.action===c.action&&h.result===c.result&&h.version===c.version))return;let kind:RecordKind,id:string;
 if(c.action==='wallet.fund'){const l=w.ledger?.find((v:RecordData)=>v.id===c.result&&v.kind==='wallet.fund');if(!l?.entries?.some((e:RecordData)=>e.wallet_id===c.payload.wallet_id&&e.amount_minor===c.payload.amount_minor))return;kind='wallet';id=c.payload.wallet_id;}
 else if(c.action==='inventory.receive'){const p=w.purchases?.find((v:RecordData)=>v.id===c.result&&v.product_id===c.payload.product_id);if(!p)return;kind='product';id=p.product_id;}
 else{const prefix=c.action.split('.')[0];if(!Object.hasOwn(collections,prefix))return;kind=prefix as RecordKind;id=c.result;}const to=target(w,kind,id);return validTarget(w,to)?to:undefined;}
